import { paramCase } from 'src/utils/change-case';

import { _id, _postTitles } from 'src/_mock/assets';

// ----------------------------------------------------------------------

const MOCK_ID = _id[1];

const MOCK_TITLE = _postTitles[2];

const ROOTS = {
  AUTH: '/auth',
  AUTH_DEMO: '/auth-demo',
  DASHBOARD: '/dashboard',
};

// ----------------------------------------------------------------------

export const paths = {
  comingSoon: '/coming-soon',
  maintenance: '/maintenance',
  pricing: '/pricing',
  payment: '/payment',
  about: '/about-us',
  contact: '/contact-us',
  spa1: {
    root: '/spa1',
    about: '/spa1/about',
    services: '/spa1/services',
    serviceDetails: (slug: string) => `/spa1/services/${slug}`,
    training: '/spa1/training',
    blog: '/spa1/blog',
    blogDetails: (slug: string) => `/spa1/blog/${slug}`,
    careers: '/spa1/careers',
    booking: '/spa1/booking',
    contact: '/spa1/contact',
    offers: '/spa1/offers',
    feedback: '/spa1/feedback',
    promotions: '/spa1/promotions',
    branches: '/spa1/branches',
    account: '/spa1/account',
    partners: '/spa1/partners',
    treatments: '/spa1/treatments',
    beforeAfter: '/spa1/before-after',
    faq: '/spa1/faq',
    policy: '/spa1/policy',
    gallery: '/spa1/gallery',
  },
  spa2: {
    root: '/spa2',
    about: '/spa2/about',
    services: '/spa2/services',
    serviceDetails: (slug: string) => `/spa2/services/${slug}`,
    training: '/spa2/training',
    blog: '/spa2/blog',
    blogDetails: (slug: string) => `/spa2/blog/${slug}`,
    careers: '/spa2/careers',
    careerDetails: (id: number) => `/spa2/careers/${id}`,
    booking: '/spa2/booking',
    contact: '/spa2/contact',
    offers: '/spa2/offers',
    feedback: '/spa2/feedback',
    promotions: '/spa2/promotions',
    branches: '/spa2/branches',
    account: '/spa2/account',
    partners: '/spa2/partners',
    treatments: '/spa2/treatments',
    beforeAfter: '/spa2/before-after',
    faq: '/spa2/faq',
    policy: '/spa2/policy',
    gallery: '/spa2/gallery',
    membership: '/spa2/membership',
    giftCard: '/spa2/gift-card',
    wellnessPackage: '/spa2/wellness-package',
    skinQuiz: '/spa2/skin-quiz',
    corporate: '/spa2/corporate',
    shop: '/spa2/shop',
    sustainability: '/spa2/sustainability',
    events: '/spa2/events',
    referral: '/spa2/referral',
    appDownload: '/spa2/app-download',
    specialOccasions: '/spa2/special-occasions',
    homeService: '/spa2/home-service',
    skinDiary: '/spa2/skin-diary',
    mindfulness: '/spa2/mindfulness',
    medicalSpa: '/spa2/medical-spa',
    spaEtiquette: '/spa2/spa-etiquette',
    loyaltyRewards: '/spa2/loyalty-rewards',
    review: '/spa2/review',
    seasonalPackage: '/spa2/seasonal-package',
    nutrition: '/spa2/nutrition',
    consultation: '/spa2/consultation',
    vipRoom: '/spa2/vip-room',
    packageBuilder: '/spa2/package-builder',
    appointment: '/spa2/appointment',
    newsletter: '/spa2/newsletter',
    press: '/spa2/press',
    affiliate: '/spa2/affiliate',
    spaFinder: '/spa2/spa-finder',
    spaMenu: '/spa2/spa-menu',
    ingredientGuide: '/spa2/ingredient-guide',
    skinSchool: '/spa2/skin-school',
    therapistProfile: '/spa2/therapist-profile',
    sleepWellness: '/spa2/sleep-wellness',
    prenatalSpa: '/spa2/prenatal-spa',
    wellnessAssessment: '/spa2/wellness-assessment',
    menSpa: '/spa2/men-spa',
    hairBeauty: '/spa2/hair-beauty',
    kidsSpa: '/spa2/kids-spa',
    antiAging: '/spa2/anti-aging',
    waterTherapy: '/spa2/water-therapy',
    ayurveda: '/spa2/ayurveda',
    spaHotel: '/spa2/spa-hotel',
    community: '/spa2/community',
  },
  spa3: {
    root: '/spa3',
    about: '/spa3/about',
    services: '/spa3/services',
    serviceDetails: (slug: string) => `/spa3/services/${slug}`,
    training: '/spa3/training',
    blog: '/spa3/blog',
    blogDetails: (slug: string) => `/spa3/blog/${slug}`,
    careers: '/spa3/careers',
    careerDetails: (id: number) => `/spa3/careers/${id}`,
    booking: '/spa3/booking',
    contact: '/spa3/contact',
    offers: '/spa3/offers',
    feedback: '/spa3/feedback',
    promotions: '/spa3/promotions',
    branches: '/spa3/branches',
    account: '/spa3/account',
    partners: '/spa3/partners',
    treatments: '/spa3/treatments',
    beforeAfter: '/spa3/before-after',
    faq: '/spa3/faq',
    policy: '/spa3/policy',
    gallery: '/spa3/gallery',
  },
  spa7: {
    root: '/spa7',
    about: '/spa7/about',
    services: '/spa7/services',
    serviceDetails: (slug: string) => `/spa7/services/${slug}`,
    training: '/spa7/training',
    blog: '/spa7/blog',
    blogDetails: (slug: string) => `/spa7/blog/${slug}`,
    careers: '/spa7/careers',
    careerDetails: (id: number) => `/spa7/careers/${id}`,
    booking: '/spa7/booking',
    contact: '/spa7/contact',
    offers: '/spa7/offers',
    feedback: '/spa7/feedback',
    promotions: '/spa7/promotions',
    branches: '/spa7/branches',
    account: '/spa7/account',
    partners: '/spa7/partners',
    treatments: '/spa7/treatments',
    beforeAfter: '/spa7/before-after',
    faq: '/spa7/faq',
    policy: '/spa7/policy',
    gallery: '/spa7/gallery',
  },
  spa11: {
    root: '/spa11',
    about: '/spa11/about',
    services: '/spa11/services',
    serviceDetails: (slug: string) => `/spa11/services/${slug}`,
    training: '/spa11/training',
    blog: '/spa11/blog',
    blogDetails: (slug: string) => `/spa11/blog/${slug}`,
    careers: '/spa11/careers',
    careerDetails: (id: number) => `/spa11/careers/${id}`,
    booking: '/spa11/booking',
    contact: '/spa11/contact',
    offers: '/spa11/offers',
    feedback: '/spa11/feedback',
    promotions: '/spa11/promotions',
    branches: '/spa11/branches',
    account: '/spa11/account',
    partners: '/spa11/partners',
    treatments: '/spa11/treatments',
    beforeAfter: '/spa11/before-after',
    faq: '/spa11/faq',
    policy: '/spa11/policy',
    gallery: '/spa11/gallery',
  },
  spa14: {
    root: '/spa14',
    about: '/spa14/about',
    services: '/spa14/services',
    serviceDetails: (slug: string) => `/spa14/services/${slug}`,
    training: '/spa14/training',
    blog: '/spa14/blog',
    blogDetails: (slug: string) => `/spa14/blog/${slug}`,
    careers: '/spa14/careers',
    careerDetails: (id: number) => `/spa14/careers/${id}`,
    booking: '/spa14/booking',
    contact: '/spa14/contact',
    offers: '/spa14/offers',
    feedback: '/spa14/feedback',
    promotions: '/spa14/promotions',
    branches: '/spa14/branches',
    account: '/spa14/account',
    partners: '/spa14/partners',
    treatments: '/spa14/treatments',
    beforeAfter: '/spa14/before-after',
    faq: '/spa14/faq',
    policy: '/spa14/policy',
    gallery: '/spa14/gallery',
  },
  spa16: {
    root: '/spa16',
    about: '/spa16/about',
    services: '/spa16/services',
    serviceDetails: (slug: string) => `/spa16/services/${slug}`,
    training: '/spa16/training',
    blog: '/spa16/blog',
    blogDetails: (slug: string) => `/spa16/blog/${slug}`,
    careers: '/spa16/careers',
    careerDetails: (id: number) => `/spa16/careers/${id}`,
    booking: '/spa16/booking',
    contact: '/spa16/contact',
    offers: '/spa16/offers',
    feedback: '/spa16/feedback',
    promotions: '/spa16/promotions',
    branches: '/spa16/branches',
    account: '/spa16/account',
    partners: '/spa16/partners',
    treatments: '/spa16/treatments',
    beforeAfter: '/spa16/before-after',
    faq: '/spa16/faq',
    policy: '/spa16/policy',
    gallery: '/spa16/gallery',
  },
  spa17: {
    root: '/spa17',
    about: '/spa17/about',
    services: '/spa17/services',
    serviceDetails: (slug: string) => `/spa17/services/${slug}`,
    training: '/spa17/training',
    blog: '/spa17/blog',
    blogDetails: (slug: string) => `/spa17/blog/${slug}`,
    careers: '/spa17/careers',
    careerDetails: (id: number) => `/spa17/careers/${id}`,
    booking: '/spa17/booking',
    contact: '/spa17/contact',
    offers: '/spa17/offers',
    feedback: '/spa17/feedback',
    promotions: '/spa17/promotions',
    branches: '/spa17/branches',
    account: '/spa17/account',
    partners: '/spa17/partners',
    treatments: '/spa17/treatments',
    beforeAfter: '/spa17/before-after',
    faq: '/spa17/faq',
    policy: '/spa17/policy',
    gallery: '/spa17/gallery',
  },
  spa18: {
    root: '/spa18',
    about: '/spa18/about',
    services: '/spa18/services',
    serviceDetails: (slug: string) => `/spa18/services/${slug}`,
    training: '/spa18/training',
    blog: '/spa18/blog',
    blogDetails: (slug: string) => `/spa18/blog/${slug}`,
    careers: '/spa18/careers',
    careerDetails: (id: number) => `/spa18/careers/${id}`,
    booking: '/spa18/booking',
    contact: '/spa18/contact',
    offers: '/spa18/offers',
    feedback: '/spa18/feedback',
    promotions: '/spa18/promotions',
    branches: '/spa18/branches',
    account: '/spa18/account',
    partners: '/spa18/partners',
    treatments: '/spa18/treatments',
    beforeAfter: '/spa18/before-after',
    faq: '/spa18/faq',
    policy: '/spa18/policy',
    gallery: '/spa18/gallery',
  },
  spa4: {
    root: '/spa4',
    about: '/spa4/about',
    services: '/spa4/services',
    serviceDetails: (slug: string) => `/spa4/services/${slug}`,
    training: '/spa4/training',
    blog: '/spa4/blog',
    blogDetails: (slug: string) => `/spa4/blog/${slug}`,
    careers: '/spa4/careers',
    booking: '/spa4/booking',
    contact: '/spa4/contact',
    offers: '/spa4/offers',
    feedback: '/spa4/feedback',
    promotions: '/spa4/promotions',
    branches: '/spa4/branches',
    account: '/spa4/account',
    partners: '/spa4/partners',
    packages: '/spa4/packages',
    beforeAfter: '/spa4/before-after',
    faq: '/spa4/faq',
    policy: '/spa4/policy',
    gallery: '/spa4/gallery',
  },
  spa5: {
    root: '/spa5',
    about: '/spa5/about',
    services: '/spa5/services',
    serviceDetails: (slug: string) => `/spa5/services/${slug}`,
    training: '/spa5/training',
    blog: '/spa5/blog',
    blogDetails: (slug: string) => `/spa5/blog/${slug}`,
    careers: '/spa5/careers',
    booking: '/spa5/booking',
    contact: '/spa5/contact',
    offers: '/spa5/offers',
    feedback: '/spa5/feedback',
    promotions: '/spa5/promotions',
    branches: '/spa5/branches',
    account: '/spa5/account',
    partners: '/spa5/partners',
    packages: '/spa5/packages',
    beforeAfter: '/spa5/before-after',
    faq: '/spa5/faq',
    policy: '/spa5/policy',
    gallery: '/spa5/gallery',
  },
  spa6: {
    root: '/spa6',
    about: '/spa6/about',
    services: '/spa6/services',
    serviceDetails: (slug: string) => `/spa6/services/${slug}`,
    training: '/spa6/training',
    blog: '/spa6/blog',
    blogDetails: (slug: string) => `/spa6/blog/${slug}`,
    careers: '/spa6/careers',
    booking: '/spa6/booking',
    contact: '/spa6/contact',
    offers: '/spa6/offers',
    feedback: '/spa6/feedback',
    promotions: '/spa6/promotions',
    branches: '/spa6/branches',
    account: '/spa6/account',
    partners: '/spa6/partners',
    packages: '/spa6/packages',
    beforeAfter: '/spa6/before-after',
    faq: '/spa6/faq',
    policy: '/spa6/policy',
    gallery: '/spa6/gallery',
  },
  spa8: {
    root: '/spa8',
    about: '/spa8/about',
    services: '/spa8/services',
    serviceDetails: (slug: string) => `/spa8/services/${slug}`,
    training: '/spa8/training',
    blog: '/spa8/blog',
    blogDetails: (slug: string) => `/spa8/blog/${slug}`,
    careers: '/spa8/careers',
    booking: '/spa8/booking',
    contact: '/spa8/contact',
    offers: '/spa8/offers',
    feedback: '/spa8/feedback',
    promotions: '/spa8/promotions',
    branches: '/spa8/branches',
    account: '/spa8/account',
    partners: '/spa8/partners',
    packages: '/spa8/packages',
    beforeAfter: '/spa8/before-after',
    faq: '/spa8/faq',
    policy: '/spa8/policy',
    gallery: '/spa8/gallery',
  },
  spa9: {
    root: '/spa9',
    about: '/spa9/about',
    services: '/spa9/services',
    serviceDetails: (slug: string) => `/spa9/services/${slug}`,
    training: '/spa9/training',
    blog: '/spa9/blog',
    blogDetails: (slug: string) => `/spa9/blog/${slug}`,
    careers: '/spa9/careers',
    booking: '/spa9/booking',
    contact: '/spa9/contact',
    offers: '/spa9/offers',
    feedback: '/spa9/feedback',
    promotions: '/spa9/promotions',
    branches: '/spa9/branches',
    account: '/spa9/account',
    partners: '/spa9/partners',
    packages: '/spa9/packages',
    beforeAfter: '/spa9/before-after',
    faq: '/spa9/faq',
    policy: '/spa9/policy',
    gallery: '/spa9/gallery',
  },
  spa10: {
    root: '/spa10',
    about: '/spa10/about',
    services: '/spa10/services',
    serviceDetails: (slug: string) => `/spa10/services/${slug}`,
    training: '/spa10/training',
    blog: '/spa10/blog',
    blogDetails: (slug: string) => `/spa10/blog/${slug}`,
    careers: '/spa10/careers',
    booking: '/spa10/booking',
    contact: '/spa10/contact',
    offers: '/spa10/offers',
    feedback: '/spa10/feedback',
    promotions: '/spa10/promotions',
    branches: '/spa10/branches',
    account: '/spa10/account',
    partners: '/spa10/partners',
    packages: '/spa10/packages',
    beforeAfter: '/spa10/before-after',
    faq: '/spa10/faq',
    policy: '/spa10/policy',
    gallery: '/spa10/gallery',
  },
  spa12: {
    root: '/spa12',
    about: '/spa12/about',
    services: '/spa12/services',
    serviceDetails: (slug: string) => `/spa12/services/${slug}`,
    training: '/spa12/training',
    blog: '/spa12/blog',
    blogDetails: (slug: string) => `/spa12/blog/${slug}`,
    careers: '/spa12/careers',
    booking: '/spa12/booking',
    contact: '/spa12/contact',
    offers: '/spa12/offers',
    feedback: '/spa12/feedback',
    promotions: '/spa12/promotions',
    branches: '/spa12/branches',
    account: '/spa12/account',
    partners: '/spa12/partners',
    packages: '/spa12/packages',
    beforeAfter: '/spa12/before-after',
    faq: '/spa12/faq',
    policy: '/spa12/policy',
    gallery: '/spa12/gallery',
  },
  spa13: {
    root: '/spa13',
    about: '/spa13/about',
    services: '/spa13/services',
    serviceDetails: (slug: string) => `/spa13/services/${slug}`,
    training: '/spa13/training',
    blog: '/spa13/blog',
    blogDetails: (slug: string) => `/spa13/blog/${slug}`,
    careers: '/spa13/careers',
    booking: '/spa13/booking',
    contact: '/spa13/contact',
    offers: '/spa13/offers',
    feedback: '/spa13/feedback',
    promotions: '/spa13/promotions',
    branches: '/spa13/branches',
    account: '/spa13/account',
    partners: '/spa13/partners',
    packages: '/spa13/packages',
    beforeAfter: '/spa13/before-after',
    faq: '/spa13/faq',
    policy: '/spa13/policy',
    gallery: '/spa13/gallery',
  },
  spa15: {
    root: '/spa15',
    about: '/spa15/about',
    services: '/spa15/services',
    serviceDetails: (slug: string) => `/spa15/services/${slug}`,
    training: '/spa15/training',
    blog: '/spa15/blog',
    blogDetails: (slug: string) => `/spa15/blog/${slug}`,
    careers: '/spa15/careers',
    booking: '/spa15/booking',
    contact: '/spa15/contact',
    offers: '/spa15/offers',
    feedback: '/spa15/feedback',
    promotions: '/spa15/promotions',
    branches: '/spa15/branches',
    account: '/spa15/account',
    partners: '/spa15/partners',
    packages: '/spa15/packages',
    beforeAfter: '/spa15/before-after',
    faq: '/spa15/faq',
    policy: '/spa15/policy',
    gallery: '/spa15/gallery',
  },
  spa: {
    about: '/about-us',
    services: '/services',
    serviceDetails: (slug: string) => `/services/${slug}`,
    training: '/training',
    blog: '/blog',
    blogDetails: (slug: string) => `/blog/${slug}`,
    careers: '/careers',
    offers: '/offers',
    contact: '/contact',
    booking: '/booking-online',
    gallery: '/gallery',
    wellness: '/wellness-library',
    membership: '/membership',
  },
  faqs: '/faqs',
  page403: '/error/403',
  page404: '/error/404',
  page500: '/error/500',
  components: '/components',
  docs: 'https://docs.minimals.cc',
  changelog: 'https://docs.minimals.cc/changelog',
  zoneStore: 'https://mui.com/store/items/zone-landing-page/',
  minimalStore: 'https://mui.com/store/items/minimal-dashboard/',
  freeUI: 'https://mui.com/store/items/minimal-dashboard-free/',
  figmaUrl: 'https://www.figma.com/design/cAPz4pYPtQEXivqe11EcDE/%5BPreview%5D-Minimal-Web.v6.0.0',
  product: {
    root: `/product`,
    checkout: `/product/checkout`,
    details: (id: string) => `/product/${id}`,
    demo: { details: `/product/${MOCK_ID}` },
  },
  post: {
    root: `/post`,
    details: (title: string) => `/post/${paramCase(title)}`,
    demo: { details: `/post/${paramCase(MOCK_TITLE)}` },
  },
  // AUTH
  auth: {
    amplify: {
      signIn: `${ROOTS.AUTH}/amplify/sign-in`,
      verify: `${ROOTS.AUTH}/amplify/verify`,
      signUp: `${ROOTS.AUTH}/amplify/sign-up`,
      updatePassword: `${ROOTS.AUTH}/amplify/update-password`,
      resetPassword: `${ROOTS.AUTH}/amplify/reset-password`,
    },
    jwt: {
      signIn: `${ROOTS.AUTH}/jwt/sign-in`,
      signUp: `${ROOTS.AUTH}/jwt/sign-up`,
    },
    firebase: {
      signIn: `${ROOTS.AUTH}/firebase/sign-in`,
      verify: `${ROOTS.AUTH}/firebase/verify`,
      signUp: `${ROOTS.AUTH}/firebase/sign-up`,
      resetPassword: `${ROOTS.AUTH}/firebase/reset-password`,
    },
    auth0: {
      signIn: `${ROOTS.AUTH}/auth0/sign-in`,
    },
    supabase: {
      signIn: `${ROOTS.AUTH}/supabase/sign-in`,
      verify: `${ROOTS.AUTH}/supabase/verify`,
      signUp: `${ROOTS.AUTH}/supabase/sign-up`,
      updatePassword: `${ROOTS.AUTH}/supabase/update-password`,
      resetPassword: `${ROOTS.AUTH}/supabase/reset-password`,
    },
  },
  authDemo: {
    split: {
      signIn: `${ROOTS.AUTH_DEMO}/split/sign-in`,
      signUp: `${ROOTS.AUTH_DEMO}/split/sign-up`,
      resetPassword: `${ROOTS.AUTH_DEMO}/split/reset-password`,
      updatePassword: `${ROOTS.AUTH_DEMO}/split/update-password`,
      verify: `${ROOTS.AUTH_DEMO}/split/verify`,
    },
    centered: {
      signIn: `${ROOTS.AUTH_DEMO}/centered/sign-in`,
      signUp: `${ROOTS.AUTH_DEMO}/centered/sign-up`,
      resetPassword: `${ROOTS.AUTH_DEMO}/centered/reset-password`,
      updatePassword: `${ROOTS.AUTH_DEMO}/centered/update-password`,
      verify: `${ROOTS.AUTH_DEMO}/centered/verify`,
    },
  },
  // DASHBOARD
  dashboard: {
    root: ROOTS.DASHBOARD,
    mail: `${ROOTS.DASHBOARD}/mail`,
    chat: `${ROOTS.DASHBOARD}/chat`,
    blank: `${ROOTS.DASHBOARD}/blank`,
    kanban: `${ROOTS.DASHBOARD}/kanban`,
    calendar: `${ROOTS.DASHBOARD}/calendar`,
    fileManager: `${ROOTS.DASHBOARD}/file-manager`,
    permission: `${ROOTS.DASHBOARD}/permission`,
    general: {
      app: `${ROOTS.DASHBOARD}/app`,
      ecommerce: `${ROOTS.DASHBOARD}/ecommerce`,
      analytics: `${ROOTS.DASHBOARD}/analytics`,
      banking: `${ROOTS.DASHBOARD}/banking`,
      booking: `${ROOTS.DASHBOARD}/booking`,
      file: `${ROOTS.DASHBOARD}/file`,
      course: `${ROOTS.DASHBOARD}/course`,
    },
    user: {
      root: `${ROOTS.DASHBOARD}/user`,
      new: `${ROOTS.DASHBOARD}/user/new`,
      list: `${ROOTS.DASHBOARD}/user/list`,
      cards: `${ROOTS.DASHBOARD}/user/cards`,
      profile: `${ROOTS.DASHBOARD}/user/profile`,
      account: `${ROOTS.DASHBOARD}/user/account`,
      edit: (id: string) => `${ROOTS.DASHBOARD}/user/${id}/edit`,
      demo: {
        edit: `${ROOTS.DASHBOARD}/user/${MOCK_ID}/edit`,
      },
    },
    product: {
      root: `${ROOTS.DASHBOARD}/product`,
      new: `${ROOTS.DASHBOARD}/product/new`,
      details: (id: string) => `${ROOTS.DASHBOARD}/product/${id}`,
      edit: (id: string) => `${ROOTS.DASHBOARD}/product/${id}/edit`,
      demo: {
        details: `${ROOTS.DASHBOARD}/product/${MOCK_ID}`,
        edit: `${ROOTS.DASHBOARD}/product/${MOCK_ID}/edit`,
      },
    },
    invoice: {
      root: `${ROOTS.DASHBOARD}/invoice`,
      new: `${ROOTS.DASHBOARD}/invoice/new`,
      details: (id: string) => `${ROOTS.DASHBOARD}/invoice/${id}`,
      edit: (id: string) => `${ROOTS.DASHBOARD}/invoice/${id}/edit`,
      demo: {
        details: `${ROOTS.DASHBOARD}/invoice/${MOCK_ID}`,
        edit: `${ROOTS.DASHBOARD}/invoice/${MOCK_ID}/edit`,
      },
    },
    post: {
      root: `${ROOTS.DASHBOARD}/post`,
      new: `${ROOTS.DASHBOARD}/post/new`,
      details: (title: string) => `${ROOTS.DASHBOARD}/post/${paramCase(title)}`,
      edit: (title: string) => `${ROOTS.DASHBOARD}/post/${paramCase(title)}/edit`,
      demo: {
        details: `${ROOTS.DASHBOARD}/post/${paramCase(MOCK_TITLE)}`,
        edit: `${ROOTS.DASHBOARD}/post/${paramCase(MOCK_TITLE)}/edit`,
      },
    },
    order: {
      root: `${ROOTS.DASHBOARD}/order`,
      details: (id: string) => `${ROOTS.DASHBOARD}/order/${id}`,
      demo: {
        details: `${ROOTS.DASHBOARD}/order/${MOCK_ID}`,
      },
    },
    job: {
      root: `${ROOTS.DASHBOARD}/job`,
      new: `${ROOTS.DASHBOARD}/job/new`,
      details: (id: string) => `${ROOTS.DASHBOARD}/job/${id}`,
      edit: (id: string) => `${ROOTS.DASHBOARD}/job/${id}/edit`,
      demo: {
        details: `${ROOTS.DASHBOARD}/job/${MOCK_ID}`,
        edit: `${ROOTS.DASHBOARD}/job/${MOCK_ID}/edit`,
      },
    },
    tour: {
      root: `${ROOTS.DASHBOARD}/tour`,
      new: `${ROOTS.DASHBOARD}/tour/new`,
      details: (id: string) => `${ROOTS.DASHBOARD}/tour/${id}`,
      edit: (id: string) => `${ROOTS.DASHBOARD}/tour/${id}/edit`,
      demo: {
        details: `${ROOTS.DASHBOARD}/tour/${MOCK_ID}`,
        edit: `${ROOTS.DASHBOARD}/tour/${MOCK_ID}/edit`,
      },
    },
    spa2: {
      root: `${ROOTS.DASHBOARD}/spa2`,
      about: `${ROOTS.DASHBOARD}/spa2/about`,
      services: `${ROOTS.DASHBOARD}/spa2/services`,
      serviceDetails: (id: string) => `${ROOTS.DASHBOARD}/spa2/services/${id}`,
      training: `${ROOTS.DASHBOARD}/spa2/training`,
      blog: `${ROOTS.DASHBOARD}/spa2/blog`,
      blogDetails: (id: string) => `${ROOTS.DASHBOARD}/spa2/blog/${id}`,
      careers: `${ROOTS.DASHBOARD}/spa2/careers`,
      careerDetails: (id: number) => `${ROOTS.DASHBOARD}/spa2/careers/${id}`,
      booking: `${ROOTS.DASHBOARD}/spa2/booking`,
      contact: `${ROOTS.DASHBOARD}/spa2/contact`,
      offers: `${ROOTS.DASHBOARD}/spa2/offers`,
      feedback: `${ROOTS.DASHBOARD}/spa2/feedback`,
      promotions: `${ROOTS.DASHBOARD}/spa2/promotions`,
      branches: `${ROOTS.DASHBOARD}/spa2/branches`,
      account: `${ROOTS.DASHBOARD}/spa2/account`,
      partners: `${ROOTS.DASHBOARD}/spa2/partners`,
      treatments: `${ROOTS.DASHBOARD}/spa2/treatments`,
      beforeAfter: `${ROOTS.DASHBOARD}/spa2/before-after`,
      faq: `${ROOTS.DASHBOARD}/spa2/faq`,
      policy: `${ROOTS.DASHBOARD}/spa2/policy`,
      gallery: `${ROOTS.DASHBOARD}/spa2/gallery`,
      membership: `${ROOTS.DASHBOARD}/spa2/membership`,
      giftCard: `${ROOTS.DASHBOARD}/spa2/gift-card`,
      wellnessPackage: `${ROOTS.DASHBOARD}/spa2/wellness-package`,
      skinQuiz: `${ROOTS.DASHBOARD}/spa2/skin-quiz`,
      corporate: `${ROOTS.DASHBOARD}/spa2/corporate`,
      shop: `${ROOTS.DASHBOARD}/spa2/shop`,
      sustainability: `${ROOTS.DASHBOARD}/spa2/sustainability`,
      events: `${ROOTS.DASHBOARD}/spa2/events`,
      referral: `${ROOTS.DASHBOARD}/spa2/referral`,
      appDownload: `${ROOTS.DASHBOARD}/spa2/app-download`,
      specialOccasions: `${ROOTS.DASHBOARD}/spa2/special-occasions`,
      homeService: `${ROOTS.DASHBOARD}/spa2/home-service`,
      skinDiary: `${ROOTS.DASHBOARD}/spa2/skin-diary`,
      mindfulness: `${ROOTS.DASHBOARD}/spa2/mindfulness`,
      medicalSpa: `${ROOTS.DASHBOARD}/spa2/medical-spa`,
      spaEtiquette: `${ROOTS.DASHBOARD}/spa2/spa-etiquette`,
      loyaltyRewards: `${ROOTS.DASHBOARD}/spa2/loyalty-rewards`,
      review: `${ROOTS.DASHBOARD}/spa2/review`,
      seasonalPackage: `${ROOTS.DASHBOARD}/spa2/seasonal-package`,
      nutrition: `${ROOTS.DASHBOARD}/spa2/nutrition`,
      consultation: `${ROOTS.DASHBOARD}/spa2/consultation`,
      vipRoom: `${ROOTS.DASHBOARD}/spa2/vip-room`,
      packageBuilder: `${ROOTS.DASHBOARD}/spa2/package-builder`,
      appointment: `${ROOTS.DASHBOARD}/spa2/appointment`,
      newsletter: `${ROOTS.DASHBOARD}/spa2/newsletter`,
      press: `${ROOTS.DASHBOARD}/spa2/press`,
      affiliate: `${ROOTS.DASHBOARD}/spa2/affiliate`,
      spaFinder: `${ROOTS.DASHBOARD}/spa2/spa-finder`,
      spaMenu: `${ROOTS.DASHBOARD}/spa2/spa-menu`,
      ingredientGuide: `${ROOTS.DASHBOARD}/spa2/ingredient-guide`,
      skinSchool: `${ROOTS.DASHBOARD}/spa2/skin-school`,
      therapistProfile: `${ROOTS.DASHBOARD}/spa2/therapist-profile`,
      sleepWellness: `${ROOTS.DASHBOARD}/spa2/sleep-wellness`,
      prenatalSpa: `${ROOTS.DASHBOARD}/spa2/prenatal-spa`,
      wellnessAssessment: `${ROOTS.DASHBOARD}/spa2/wellness-assessment`,
      menSpa: `${ROOTS.DASHBOARD}/spa2/men-spa`,
      hairBeauty: `${ROOTS.DASHBOARD}/spa2/hair-beauty`,
      kidsSpa: `${ROOTS.DASHBOARD}/spa2/kids-spa`,
      antiAging: `${ROOTS.DASHBOARD}/spa2/anti-aging`,
      waterTherapy: `${ROOTS.DASHBOARD}/spa2/water-therapy`,
      ayurveda: `${ROOTS.DASHBOARD}/spa2/ayurveda`,
      spaHotel: `${ROOTS.DASHBOARD}/spa2/spa-hotel`,
      community: `${ROOTS.DASHBOARD}/spa2/community`,
      demo: {
        details: `${ROOTS.DASHBOARD}/job/${MOCK_ID}`,
        edit: `${ROOTS.DASHBOARD}/job/${MOCK_ID}/edit`,
      },
    },
  },
};
