export * from 'src/sections/spa2/view/spa2-view';
export * from 'src/sections/spa2/view/spa2-content-pages';
export * from 'src/sections/spa2/view/spa2-content-pages2';
export * from 'src/sections/spa2/view/spa2-content-pages3';
export * from 'src/sections/spa2/view/spa2-content-pages4';
export * from 'src/sections/spa2/view/spa2-content-pages5';
export * from 'src/sections/spa2/view/spa2-content-pages6';
export * from 'src/sections/spa2/view/spa2-content-pages8';
export * from 'src/sections/spa2/view/spa2-content-pages9';
