// ----------------------------------------------------------------------

export type Spa6Lang = 'en' | 'vi' | 'fr' | 'cn' | 'ar';

export const SPA6_IMAGES = {
  hero: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1920&q=80',
  heroOverlay: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=400&q=80',
  about: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80',
  ritual1: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80',
  ritual2: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
  ritual3: 'https://images.unsplash.com/photo-1611073615830-9f2f0508d72f?w=800&q=80',
  ritual4: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&q=80',
  retreat: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=1200&q=80',
};

export const SPA6_HERO_SLIDES = [
  {
    src: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1920&q=80',
    alt: 'Ayurveda wellness',
  },
  {
    src: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=1920&q=80',
    alt: 'Nature retreat',
  },
  {
    src: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=1920&q=80',
    alt: 'Forest bathing',
  },
  {
    src: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=1920&q=80',
    alt: 'Healing space',
  },
];

export const SPA6_RITUALS = [
  {
    title: {
      vi: 'Abhyanga Oil Ritual',
      en: 'Abhyanga Oil Ritual',
      fr: 'Abhyanga Oil Ritual',
      cn: 'Abhyanga 油疗仪式',
      ar: 'طقوس زيت أبهيانجا',
    },
    origin: {
      vi: 'Ayurveda — Ấn Độ',
      en: 'Ayurveda — India',
      fr: 'Ayurveda — Inde',
      cn: '阿育吠陀 — 印度',
      ar: 'الأيورفيدا — الهند',
    },
    description: {
      vi: 'Massage toàn thân bằng dầu thảo mộc ấm được chọn theo Dosha cá nhân. Kỹ thuật đẩy ngược chiều lông để kích thích tuần hoàn bạch huyết, đẩy toxin ra khỏi tế bào và nuôi dưỡng da từ sâu bên trong.',
      en: 'Full-body massage with warm herbal oils selected by your personal Dosha. Counter-grain strokes stimulate lymphatic flow, push toxins out of cells and deeply nourish the skin.',
      fr: 'Massage du corps entier aux huiles végétales chaudes choisies selon votre Dosha personnel. Les mouvements à contre-poil stimulent la circulation lymphatique, éliminent les toxines des cellules et nourrissent la peau en profondeur.',
      cn: '使用根据您个人体质（Dosha）选配的温热草本油进行全身按摩。逆毛流手法刺激淋巴循环，将毒素排出细胞，并由内而外深层滋养肌肤。',
      ar: 'تدليك للجسم بالكامل بزيوت عشبية دافئة مختارة حسب الدوشا الخاص بك. تحفّز الحركات العكسية تدفق اللمف وتطرد السموم من الخلايا وتغذّي البشرة من العمق.',
    },
    duration: { vi: '90 phút', en: '90 min', fr: '90 min', cn: '90 分钟', ar: '90 دقيقة' },
    price: {
      vi: 'từ 950.000₫',
      en: 'from 950,000₫',
      fr: 'à partir de 950 000₫',
      cn: '￥950,000 起',
      ar: 'من 950,000₫',
    },
    icon: 'solar:sun-bold-duotone',
    color: '#C1440E',
    bg: '#FFF3EE',
    image: SPA6_IMAGES.ritual1,
  },
  {
    title: {
      vi: 'Forest Bathing',
      en: 'Forest Bathing',
      fr: 'Forest Bathing',
      cn: '森林浴',
      ar: 'الاستحمام في الغابة',
    },
    origin: {
      vi: 'Shinrin-yoku — Nhật Bản',
      en: 'Shinrin-yoku — Japan',
      fr: 'Shinrin-yoku — Japon',
      cn: '森林浴 — 日本',
      ar: 'شينرين يوكو — اليابان',
    },
    description: {
      vi: 'Tắm rừng trong không gian xanh mát với tinh dầu lá tre, hương thông và tiếng suối chảy. Thực hành thở sâu cùng âm nhạc tự nhiên, giảm cortisol hiệu quả và phục hồi hệ thần kinh tự chủ.',
      en: 'Forest bathing in a lush green space with bamboo leaf essential oil, pine fragrance and the sound of flowing water. Deep breathing practice with natural soundscapes, effectively reducing cortisol and restoring the autonomic nervous system.',
      fr: 'Bain de forêt dans un espace verdoyant avec huile essentielle de feuille de bambou, parfum de pin et bruit de l’eau qui coule. Pratique de respiration profonde au son de la nature, réduisant efficacement le cortisol et restaurant le système nerveux autonome.',
      cn: '在郁郁葱葱的绿色空间中进行森林浴，伴有竹叶精油、松木香气与流水声。在自然音景中练习深呼吸，有效降低皮质醇并恢复自主神经系统。',
      ar: 'الاستحمام في الغابة في مساحة خضراء وارفة مع زيت أوراق الخيزران العطري ورائحة الصنوبر وصوت المياه الجارية. تمارين تنفّس عميق مع أصوات الطبيعة تقلّل الكورتيزول بفعالية وتعيد توازن الجهاز العصبي اللاإرادي.',
    },
    duration: { vi: '75 phút', en: '75 min', fr: '75 min', cn: '75 分钟', ar: '75 دقيقة' },
    price: {
      vi: 'từ 780.000₫',
      en: 'from 780,000₫',
      fr: 'à partir de 780 000₫',
      cn: '￥780,000 起',
      ar: 'من 780,000₫',
    },
    icon: 'solar:leaf-bold-duotone',
    color: '#2D5016',
    bg: '#F0F7E9',
    image: SPA6_IMAGES.ritual2,
  },
  {
    title: {
      vi: 'Boreh Bali Ritual',
      en: 'Boreh Bali Ritual',
      fr: 'Boreh Bali Ritual',
      cn: 'Boreh 巴厘岛仪式',
      ar: 'طقوس بوريه بالي',
    },
    origin: {
      vi: 'Boreh — Bali, Indonesia',
      en: 'Boreh — Bali, Indonesia',
      fr: 'Boreh — Bali, Indonésie',
      cn: 'Boreh — 印度尼西亚巴厘岛',
      ar: 'بوريه — بالي، إندونيسيا',
    },
    description: {
      vi: 'Hỗn hợp gia vị Bali truyền thống (đinh hương, gừng, nghệ, bã cà phê) đắp toàn thân, giúp tăng tuần hoàn, sưởi ấm cơ thể và thải độc mạnh mẽ. Kết thúc bằng tắm hoa và dưỡng thể với dầu dừa tinh khiết.',
      en: 'A blend of traditional Balinese spices (cloves, ginger, turmeric, coffee grounds) applied all over the body, boosting circulation, warming deep muscles and powerfully detoxifying. Concludes with a flower bath and coconut oil body moisturiser.',
      fr: 'Un mélange d’épices balinaises traditionnelles (clous de girofle, gingembre, curcuma, marc de café) appliqué sur tout le corps, stimulant la circulation, réchauffant les muscles profonds et détoxifiant puissamment. Se termine par un bain de fleurs et un soin du corps à l’huile de coco.',
      cn: '将传统巴厘岛香料（丁香、生姜、姜黄、咖啡渣）调和敷于全身，促进循环、温暖深层肌肉并强力排毒。最后以鲜花浴和纯椰子油身体护理收尾。',
      ar: 'مزيج من التوابل البالية التقليدية (القرنفل والزنجبيل والكركم وتفل القهوة) يوضع على الجسم بالكامل لتعزيز الدورة الدموية وتدفئة العضلات العميقة والتخلص من السموم بقوة. ينتهي بحمام أزهار وترطيب للجسم بزيت جوز الهند.',
    },
    duration: { vi: '100 phút', en: '100 min', fr: '100 min', cn: '100 分钟', ar: '100 دقيقة' },
    price: {
      vi: 'từ 1.100.000₫',
      en: 'from 1,100,000₫',
      fr: 'à partir de 1 100 000₫',
      cn: '￥1,100,000 起',
      ar: 'من 1,100,000₫',
    },
    icon: 'solar:flower-bold-duotone',
    color: '#8B4513',
    bg: '#FFF8F0',
    image: SPA6_IMAGES.ritual3,
  },
  {
    title: {
      vi: 'Herbal Steam Lodge',
      en: 'Herbal Steam Lodge',
      fr: 'Herbal Steam Lodge',
      cn: '草本蒸汽屋',
      ar: 'كوخ البخار العشبي',
    },
    origin: {
      vi: 'Xông hơi thảo mộc — Việt Nam',
      en: 'Herbal steam — Vietnam',
      fr: 'Vapeur d’herbes — Vietnam',
      cn: '草本蒸汽 — 越南',
      ar: 'البخار العشبي — فيتنام',
    },
    description: {
      vi: 'Liệu pháp xông hơi toàn thân bằng 12 loại thảo dược quý: ngải cứu, sả, gừng, lá ổi, tía tô và bồ kết. Thanh lọc hô hấp, giải cảm, kháng viêm và tăng sức đề kháng. Phương pháp dân gian được y học hiện đại xác nhận.',
      en: 'Whole-body herbal steam therapy using 12 precious herbs: mugwort, lemongrass, ginger, guava leaf, perilla and blackberry lily. Cleanses the respiratory system, fights inflammation and boosts immunity. A traditional folk method validated by modern medicine.',
      fr: 'Thérapie de vapeur d’herbes pour tout le corps utilisant 12 herbes précieuses : armoise, citronnelle, gingembre, feuille de goyave, périlla et lis. Purifie le système respiratoire, combat l’inflammation et renforce l’immunité. Une méthode traditionnelle validée par la médecine moderne.',
      cn: '采用 12 种珍贵草药（艾草、香茅、生姜、番石榴叶、紫苏与皂荚）进行全身草本蒸汽疗法。清洁呼吸系统、抗炎并增强免疫力。这是一种经现代医学验证的传统民间疗法。',
      ar: 'علاج بالبخار العشبي للجسم بالكامل باستخدام 12 عشبة ثمينة: الشيح والليمون العشبي والزنجبيل وأوراق الجوافة والبريلا وزنبق الزعفران. ينقّي الجهاز التنفسي ويكافح الالتهاب ويعزّز المناعة. طريقة شعبية تقليدية أثبتها الطب الحديث.',
    },
    duration: { vi: '60 phút', en: '60 min', fr: '60 min', cn: '60 分钟', ar: '60 دقيقة' },
    price: {
      vi: 'từ 650.000₫',
      en: 'from 650,000₫',
      fr: 'à partir de 650 000₫',
      cn: '￥650,000 起',
      ar: 'من 650,000₫',
    },
    icon: 'solar:cloud-bold-duotone',
    color: '#5B7A3F',
    bg: '#F4F8EE',
    image: SPA6_IMAGES.ritual4,
  },
];

export const SPA6_PACKAGES = [
  {
    name: {
      vi: 'Cuối Tuần Chữa Lành',
      en: 'Healing Weekend',
      fr: 'Week-end de Guérison',
      cn: '疗愈周末',
      ar: 'عطلة نهاية أسبوع للشفاء',
    },
    duration: {
      vi: '2 ngày 1 đêm',
      en: '2 days 1 night',
      fr: '2 jours 1 nuit',
      cn: '2 天1 夜',
      ar: 'يومان وليلة',
    },
    price: {
      vi: '3.500.000₫',
      en: '3,500,000₫',
      fr: '3 500 000₫',
      cn: '￥3,500,000',
      ar: '3,500,000₫',
    },
    popular: false,
    color: '#2D5016',
    description: {
      vi: 'Bước đầu tiên vào thế giới thiên nhiên trị liệu',
      en: 'Your first step into the world of natural therapy',
      fr: 'Votre premier pas dans le monde de la thérapie naturelle',
      cn: '踏入自然疗愈世界的第一步',
      ar: 'خطوتك الأولى إلى عالم العلاج الطبيعي',
    },
    includes: {
      vi: [
        '1 liệu trình Abhyanga (90 phút)',
        '1 buổi Yoga buổi sáng',
        'Bữa ăn chay organic 2 bữa',
        'Phòng ngủ giường đôi',
        'Tư vấn Dosha cá nhân',
      ],
      en: [
        '1 Abhyanga treatment (90 min)',
        '1 morning yoga session',
        '2 organic vegetarian meals',
        'Double room',
        'Personal Dosha consultation',
      ],
      fr: [
        '1 soin Abhyanga (90 min)',
        '1 séance de yoga matinale',
        '2 repas végétariens bio',
        'Chambre double',
        'Consultation Dosha personnalisée',
      ],
      cn: [
        '1 次 Abhyanga 疗程（90 分钟）',
        '1 次晨间瑶伽',
        '2 餐有机素食',
        '双人房',
        '个人体质（Dosha）咨询',
      ],
      ar: [
        'جلسة أبهيانجا واحدة (90 دقيقة)',
        'جلسة يوجا صباحية واحدة',
        'وجبتان نباتيتان عضويتان',
        'غرفة مزدوجة',
        'استشارة دوشا شخصية',
      ],
    },
  },
  {
    name: {
      vi: 'Retreat Chuyển Hóa 5 Ngày',
      en: '5-Day Transformation Retreat',
      fr: 'Retraite Transformation 5 Jours',
      cn: '5 天蜕变静修',
      ar: 'خلوة التحول 5 أيام',
    },
    duration: {
      vi: '5 ngày 4 đêm',
      en: '5 days 4 nights',
      fr: '5 jours 4 nuits',
      cn: '5 天4 夜',
      ar: '5 أيام و4 ليالٍ',
    },
    price: {
      vi: '12.500.000₫',
      en: '12,500,000₫',
      fr: '12 500 000₫',
      cn: '￥12,500,000',
      ar: '12,500,000₫',
    },
    popular: true,
    color: '#C1440E',
    description: {
      vi: 'Chương trình chuyển hóa toàn diện được nhiều khách yêu thích',
      en: 'The comprehensive transformation program our guests love most',
      fr: 'Le programme de transformation complet que nos clients préfèrent',
      cn: '深受客人喜爱的全面蜕变计划',
      ar: 'برنامج التحول الشامل الأكثر تفضيلاً لدى ضيوفنا',
    },
    includes: {
      vi: [
        '5 liệu trình (tự chọn)',
        '2 buổi Forest Bathing',
        'Ăn 3 bữa/ngày chế độ Sattvic',
        'Phòng Deluxe có ban công',
        'Lớp học nấu ăn thảo dược',
        'Bộ sản phẩm terra mang về',
      ],
      en: [
        '5 treatments (your choice)',
        '2 Forest Bathing sessions',
        '3 Sattvic meals/day',
        'Deluxe room with balcony',
        'Herbal cooking class',
        'Terra take-home product kit',
      ],
      fr: [
        '5 soins (au choix)',
        '2 séances de Forest Bathing',
        '3 repas Sattvic/jour',
        'Chambre Deluxe avec balcon',
        'Cours de cuisine aux herbes',
        'Kit de produits terra à emporter',
      ],
      cn: [
        '5 次疗程（自选）',
        '2 次森林浴',
        '每日 3 餐萨提瓦饮食',
        '带阳台豪华房',
        '草本烹饪课',
        'terra 伴手礼产品套装',
      ],
      ar: [
        '5 جلسات (باختيارك)',
        'جلستا استحمام في الغابة',
        '3 وجبات ساتفية يومياً',
        'غرفة ديلوكس مع شرفة',
        'درس طبخ بالأعشاب',
        'مجموعة منتجات terra للمنزل',
      ],
    },
  },
  {
    name: {
      vi: 'Panchakarma 7 Ngày',
      en: '7-Day Panchakarma',
      fr: 'Panchakarma 7 Jours',
      cn: '7 天五业排毒',
      ar: 'بانشاكارما 7 أيام',
    },
    duration: {
      vi: '7 ngày 6 đêm',
      en: '7 days 6 nights',
      fr: '7 jours 6 nuits',
      cn: '7 天6 夜',
      ar: '7 أيام و6 ليالٍ',
    },
    price: {
      vi: '21.000.000₫',
      en: '21,000,000₫',
      fr: '21 000 000₫',
      cn: '￥21,000,000',
      ar: '21,000,000₫',
    },
    popular: false,
    color: '#5B3A29',
    description: {
      vi: 'Chương trình detox toàn diện theo y học Ayurveda cổ đại',
      en: 'Complete detox program based on ancient Ayurvedic medicine',
      fr: 'Programme de détox complet basé sur la médecine ayurvédique ancienne',
      cn: '基于古老阿育吠陀医学的全面排毒计划',
      ar: 'برنامج تخلص من السموم شامل قائم على طب الأيورفيدا القديم',
    },
    includes: {
      vi: [
        '7 liệu trình cao cấp hàng ngày',
        'Panchakarma đầy đủ 5 bước',
        'Chế độ ăn Ayurveda tùy chỉnh',
        'Phòng Suite riêng tư',
        'Thiền hàng ngày với thầy',
        'Tư vấn dinh dưỡng 6 tuần sau',
        'Bộ thảo dược tại nhà trọn gói',
      ],
      en: [
        '7 premium daily treatments',
        'Complete 5-step Panchakarma',
        'Custom Ayurvedic diet plan',
        'Private suite',
        'Daily meditation with master',
        '6-week post-retreat nutrition consult',
        'Full home herbal kit',
      ],
      fr: [
        '7 soins premium quotidiens',
        'Panchakarma complet en 5 étapes',
        'Plan alimentaire ayurvédique personnalisé',
        'Suite privée',
        'Méditation quotidienne avec un maître',
        'Suivi nutritionnel 6 semaines après la retraite',
        'Kit d’herbes complet à la maison',
      ],
      cn: [
        '每日 7 次高端疗程',
        '完整 5 步五业排毒',
        '定制阿育吠陀饮食计划',
        '私人套房',
        '每日与大师冥想',
        '静修后 6 周营养咨询',
        '全套居家草本包',
      ],
      ar: [
        '7 جلسات علاج فاخرة يومياً',
        'بانشاكارما كاملة من 5 خطوات',
        'خطة غذائية أيورفيدية مخصصة',
        'جناح خاص',
        'تأمل يومي مع معلّم',
        'استشارة تغذية لمدة 6 أسابيع بعد الخلوة',
        'مجموعة أعشاب منزلية كاملة',
      ],
    },
  },
];

export const SPA6_TESTIMONIALS = [
  {
    name: 'Trần Lê Bảo Châu',
    role: {
      vi: 'Bác sĩ, Hà Nội',
      en: 'Doctor, Hanoi',
      fr: 'Médecin, Hanoï',
      cn: '医生，河内',
      ar: 'طبيبة، هانوي',
    },
    quote: {
      vi: 'Tôi đến với Terra Heal trong tình trạng kiệt sức sau 3 năm COVID. Chương trình 5 ngày không chỉ phục hồi thể chất mà còn giúp tôi tái kết nối với bản thân. Đây là liệu pháp y tế tôi tự kê đơn cho mình.',
      en: 'I came to Terra Heal in a state of exhaustion after 3 years of COVID work. The 5-day program not only restored my body but helped me reconnect with myself. This is the medical therapy I prescribed for myself.',
      fr: 'Je suis arrivée à Terra Heal dans un état d’épuisement après 3 ans de travail lié au COVID. Le programme de 5 jours a non seulement restauré mon corps, mais m’a aidée à me reconnecter à moi-même. C’est la thérapie médicale que je me suis prescrite.',
      cn: '经过三年的新冠疫情工作，我带着精疲力竭来到 Terra Heal。这个 5 天的计划不仅修复了我的身体，还帮助我重新连接自我。这是我为自己开的医疗处方。',
      ar: 'جئت إلى Terra Heal في حالة إنهاك بعد 3 سنوات من العمل خلال جائحة كوفيد. لم يعد برنامج الخمسة أيام جسدي فحسب، بل ساعدني على إعادة التواصل مع ذاتي. هذا هو العلاج الطبي الذي وصفته لنفسي.',
    },
    beforeAfter: {
      vi: 'Sau Retreat 5 Ngày',
      en: 'After 5-Day Retreat',
      fr: 'Après la retraite de 5 jours',
      cn: '5 天静修之后',
      ar: 'بعد خلوة 5 أيام',
    },
    improvement: {
      vi: 'Giảm 80% lo âu mãn tính',
      en: '80% reduction in chronic anxiety',
      fr: 'Réduction de 80% de l’anxiété chronique',
      cn: '慢性焦虑减少 80%',
      ar: 'انخفاض القلق المزمن بنسبة 80%',
    },
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&q=80',
  },
  {
    name: 'Phạm Đức Minh',
    role: {
      vi: 'Kỹ sư xây dựng, TP.HCM',
      en: 'Civil Engineer, HCMC',
      fr: 'Ingénieur civil, Hô Chi Minh-Ville',
      cn: '土木工程师，胡志明市',
      ar: 'مهندس مدني، مدينة هو تشي منه',
    },
    quote: {
      vi: 'Forest Bathing nghe có vẻ đơn giản nhưng tác động của nó rất sâu. Lần đầu tiên sau 5 năm, tôi ngủ được liên tục 8 tiếng không cần thuốc. Thầy hướng dẫn thiền của Terra Heal thực sự xuất sắc.',
      en: 'Forest Bathing sounds simple but its effects run deep. For the first time in 5 years, I slept continuously for 8 hours without medication. The meditation instructor at Terra Heal is truly exceptional.',
      fr: 'Le Forest Bathing semble simple, mais ses effets sont profonds. Pour la première fois en 5 ans, j’ai dormi 8 heures d’affilée sans médicament. L’instructeur de méditation de Terra Heal est vraiment exceptionnel.',
      cn: '森林浴听起来很简单，但其效果极为深远。五年来我第一次在不服药的情况下连续睡了 8 个小时。Terra Heal 的冥想导师真的非凡。',
      ar: 'يبدو الاستحمام في الغابة بسيطاً لكن تأثيره عميق. لأول مرة منذ 5 سنوات، نمت 8 ساعات متواصلة دون دواء. مدرّب التأمل في Terra Heal استثنائي حقاً.',
    },
    beforeAfter: {
      vi: 'Sau 3 buổi Forest Bathing',
      en: 'After 3 Forest Bathing sessions',
      fr: 'Après 3 séances de Forest Bathing',
      cn: '3 次森林浴之后',
      ar: 'بعد 3 جلسات استحمام في الغابة',
    },
    improvement: {
      vi: 'Ngủ sâu trở lại',
      en: 'Deep sleep restored',
      fr: 'Sommeil profond retrouvé',
      cn: '恢复深度睡眠',
      ar: 'استعادة النوم العميق',
    },
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&q=80',
  },
  {
    name: 'Lê Thị Thanh Mai',
    role: {
      vi: 'Giáo viên yoga, Đà Nẵng',
      en: 'Yoga Teacher, Da Nang',
      fr: 'Professeure de yoga, Da Nang',
      cn: '瑶伽老师，峘港',
      ar: 'مدرّبة يوجا، دا نانغ',
    },
    quote: {
      vi: 'Là người làm trong ngành wellness, tôi rất kỹ tính khi chọn spa. Terra Heal vượt qua mọi kỳ vọng của tôi. Boreh Bali Ritual của họ chính xác như ở Ubud — chất lượng nguyên liệu, kỹ thuật và không gian đều đạt đỉnh.',
      en: 'As someone who works in wellness, I am very particular about choosing a spa. Terra Heal exceeded all my expectations. Their Boreh Bali Ritual is exactly as in Ubud — the quality of ingredients, technique and space are all at their peak.',
      fr: 'En tant que professionnelle du bien-être, je suis très exigeante dans le choix d’un spa. Terra Heal a dépassé toutes mes attentes. Leur Boreh Bali Ritual est exactement comme à Ubud — la qualité des ingrédients, la technique et l’espace sont au sommet.',
      cn: '作为从事养生行业的人，我选择 spa 非常挑剔。Terra Heal 超出了我所有的期望。他们的 Boreh 巴厘岛仪式与乌布布的一模一样 — 原料品质、手法与环境都达到巅峰。',
      ar: 'بصفتي أعمل في مجال العافية، أنا دقيقة جداً في اختيار السبا. لقد تجاوز Terra Heal كل توقعاتي. طقوس بوريه بالي لديهم مطابقة تماماً لما في أوبود — جودة المكونات والتقنية والمكان كلها في أوجها.',
    },
    beforeAfter: {
      vi: 'Khách thường xuyên',
      en: 'Regular guest',
      fr: 'Cliente régulière',
      cn: '常客',
      ar: 'ضيفة دائمة',
    },
    improvement: {
      vi: 'Ghé thăm hàng tháng',
      en: 'Monthly visits',
      fr: 'Visites mensuelles',
      cn: '每月到访',
      ar: 'زيارات شهرية',
    },
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&q=80',
  },
];

export const SPA6_BOOKING_CONCERNS = {
  vi: [
    'Stress & Lo âu',
    'Mất ngủ',
    'Đau lưng & Cơ khớp',
    'Da xấu & Lão hóa',
    'Suy nhược cơ thể',
    'Rối loạn tiêu hóa',
    'Cần detox tổng thể',
    'Khác',
  ],
  en: [
    'Stress & Anxiety',
    'Insomnia',
    'Back pain & Joints',
    'Skin & Ageing',
    'Physical exhaustion',
    'Digestive issues',
    'General detox',
    'Other',
  ],
  fr: [
    'Stress et anxiété',
    'Insomnie',
    'Douleurs dorsales et articulaires',
    'Peau et vieillissement',
    'Épuisement physique',
    'Problèmes digestifs',
    'Détox générale',
    'Autre',
  ],
  cn: [
    '压力与焦虑',
    '失眠',
    '背痛与关节',
    '肌肤与衰老',
    '身体衰弱',
    '消化问题',
    '全身排毒',
    '其他',
  ],
  ar: [
    'التوتر والقلق',
    'الأرق',
    'آلام الظهر والمفاصل',
    'البشرة والشيخوخة',
    'الإرهاق الجسدي',
    'مشاكل الهضم',
    'التخلص العام من السموم',
    'أخرى',
  ],
};

export const SPA6_HOW_HEAR = {
  vi: ['Bạn bè giới thiệu', 'Mạng xã hội', 'Google', 'Báo/Tạp chí', 'Sự kiện wellness', 'Khác'],
  en: ['Friend referral', 'Social media', 'Google', 'Press / Magazine', 'Wellness event', 'Other'],
  fr: [
    'Recommandation d’un ami',
    'Réseaux sociaux',
    'Google',
    'Presse / Magazine',
    'Événement bien-être',
    'Autre',
  ],
  cn: ['朋友推荐', '社交媒体', 'Google', '报刊 / 杂志', '养生活动', '其他'],
  ar: ['توصية صديق', 'وسائل التواصل الاجتماعي', 'Google', 'صحف / مجلات', 'فعالية عافية', 'أخرى'],
};
