// ----------------------------------------------------------------------

export type Spa4Lang = 'en' | 'vi' | 'fr' | 'cn' | 'ar';

export const SPA4_IMAGES = {
  hero1: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=800&q=80',
  hero2: 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=800&q=80',
  philosophy1: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80',
  philosophy2: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80',
  philosophy3: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=80',
  treat1: 'https://images.unsplash.com/photo-1583416750470-965b2707b355?w=800&q=80',
  treat2: 'https://images.unsplash.com/photo-1552693673-1bf958298935?w=800&q=80',
  treat3: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=800&q=80',
  treat4: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&q=80',
  team1: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80',
  team2: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80',
  team3: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80',
  team4: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80',
  booking: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1200&q=80',
};

export const SPA4_TREATMENTS = [
  {
    title: {
      vi: 'K-Beauty Glow Ritual',
      en: 'K-Beauty Glow Ritual',
      fr: 'K-Beauty Glow Ritual',
      cn: 'K-Beauty Glow Ritual',
      ar: 'K-Beauty Glow Ritual',
    },
    category: {
      vi: 'Chăm Sóc Da',
      en: 'Skin Care',
      fr: 'Soin de la Peau',
      cn: '护肤',
      ar: 'العناية بالبشرة',
    },
    description: {
      vi: '10 bước chăm sóc da Hàn Quốc chuyên sâu: tẩy tế bào chết, đắp mặt nạ collagen, serum vitamin C và dưỡng ẩm cao cấp giúp da căng bóng, rạng rỡ tức thì.',
      en: 'A 10-step intensive Korean skincare ritual: exfoliation, collagen mask, vitamin C serum and premium moisturizer for instantly plump, radiant skin.',
      fr: 'Un rituel coréen intensif en 10 étapes : exfoliation, masque au collagène, sérum à la vitamine C et hydratant premium pour une peau instantanément repulpée et éclatante.',
      cn: '十步韩式深层护肤仪式：去角质、胶原蛋白面膜、维生素C精华和高级保湿霜，让肌肤即刻饱满亮泽。',
      ar: 'طقوس عناية كورية مكثفة من 10 خطوات: تقشير، وقناع الكولاجين، وسيروم فيتامين C، ومرطب فاخر لبشرة ممتلئة ومشرقة على الفور.',
    },
    icon: 'solar:star-shine-bold-duotone',
    duration: { vi: '90 phút', en: '90 min', fr: '90 min', cn: '90 min', ar: '90 min' },
    price: {
      vi: '1.200.000₫',
      en: '1,200,000₫',
      fr: '1,200,000₫',
      cn: '1,200,000₫',
      ar: '1,200,000₫',
    },
    badge: {
      vi: 'Bán chạy nhất',
      en: 'Best seller',
      fr: 'Meilleure vente',
      cn: '热销',
      ar: 'الأكثر مبيعاً',
    },
    image: SPA4_IMAGES.treat1,
    color: '#E8F5E9',
  },
  {
    title: {
      vi: 'Jade Stone Massage',
      en: 'Jade Stone Massage',
      fr: 'Jade Stone Massage',
      cn: 'Jade Stone Massage',
      ar: 'Jade Stone Massage',
    },
    category: { vi: 'Massage', en: 'Massage', fr: 'Massage', cn: '按摩', ar: 'تدليك' },
    description: {
      vi: 'Đá ngọc bích tự nhiên kết hợp kỹ thuật massage kinh lạc Đông Phương, cân bằng khí huyết, giảm căng cơ và phục hồi năng lượng từ sâu bên trong.',
      en: 'Natural jade stones combined with Eastern meridian massage techniques to balance energy flow, relieve muscle tension, and restore vitality from within.',
      fr: 'Des pierres de jade naturelles associées aux techniques de massage des méridiens orientaux pour équilibrer la circulation de l’énergie, soulager les tensions musculaires et restaurer la vitalité de l’intérieur.',
      cn: '天然玉石结合东方经络按摩技法，平衡气血运行，缓解肌肉紧张，由内而外恢复活力。',
      ar: 'أحجار اليشم الطبيعية مع تقنيات تدليك خطوط الطاقة الشرقية لموازنة تدفق الطاقة وتخفيف توتر العضلات واستعادة الحيوية من الداخل.',
    },
    icon: 'solar:leaf-bold-duotone',
    duration: { vi: '75 phút', en: '75 min', fr: '75 min', cn: '75 min', ar: '75 min' },
    price: {
      vi: '980.000₫',
      en: '980,000₫',
      fr: '980,000₫',
      cn: '980,000₫',
      ar: '980,000₫',
    },
    badge: { vi: 'Độc quyền', en: 'Exclusive', fr: 'Exclusif', cn: '独家', ar: 'حصري' },
    image: SPA4_IMAGES.treat2,
    color: '#F3E5F5',
  },
  {
    title: {
      vi: 'Sakura Blossom Body Wrap',
      en: 'Sakura Blossom Body Wrap',
      fr: 'Sakura Blossom Body Wrap',
      cn: 'Sakura Blossom Body Wrap',
      ar: 'Sakura Blossom Body Wrap',
    },
    category: {
      vi: 'Liệu Pháp Body',
      en: 'Body Therapy',
      fr: 'Thérapie Corporelle',
      cn: '身体护理',
      ar: 'علاج الجسم',
    },
    description: {
      vi: 'Gói ủ cơ thể với tinh chất hoa anh đào Nhật Bản và bùn khoáng núi lửa, tẩy da chết, dưỡng trắng và săn chắc toàn thân hiệu quả.',
      en: 'Full-body wrap with Japanese cherry blossom extract and volcanic mineral mud for exfoliation, brightening and firming skin all over.',
      fr: 'Enveloppement complet du corps à l’extrait de fleur de cerisier japonais et à la boue minérale volcanique pour exfolier, illuminer et raffermir toute la peau.',
      cn: '采用日本樱花精华与火山矿物泥的全身裹敷，去角质、提亮并紧致全身肌肤。',
      ar: 'لفّ كامل للجسم بخلاصة أزهار الكرز اليابانية والطين المعدني البركاني للتقشير وتفتيح وشدّ البشرة بالكامل.',
    },
    icon: 'solar:flower-bold-duotone',
    duration: { vi: '110 phút', en: '110 min', fr: '110 min', cn: '110 min', ar: '110 min' },
    price: {
      vi: '1.450.000₫',
      en: '1,450,000₫',
      fr: '1,450,000₫',
      cn: '1,450,000₫',
      ar: '1,450,000₫',
    },
    badge: { vi: 'Mới nhất', en: 'New', fr: 'Nouveau', cn: '最新', ar: 'جديد' },
    image: SPA4_IMAGES.treat3,
    color: '#FFF3E0',
  },
  {
    title: {
      vi: 'Scalp & Hair Detox',
      en: 'Scalp & Hair Detox',
      fr: 'Scalp & Hair Detox',
      cn: 'Scalp & Hair Detox',
      ar: 'Scalp & Hair Detox',
    },
    category: {
      vi: 'Chăm Sóc Tóc',
      en: 'Hair Care',
      fr: 'Soin des Cheveux',
      cn: '护发',
      ar: 'العناية بالشعر',
    },
    description: {
      vi: 'Liệu trình detox da đầu với dầu argan Morocco và gừng tươi, massage kích thích mọc tóc, phục hồi mái tóc hư tổn và tăng cường độ bóng tự nhiên.',
      en: 'Scalp detox treatment with Moroccan argan oil and fresh ginger, stimulating hair growth massage, restoring damaged hair and boosting natural shine.',
      fr: 'Traitement détox du cuir chevelu à l’huile d’argan marocaine et au gingembre frais, massage stimulant la pousse des cheveux, réparant les cheveux abîmés et ravivant la brillance naturelle.',
      cn: '采用摩洛哥坚果油与新鲜生姜的头皮排毒护理，按摩刺激发根生长，修复受损发质并提升自然光泽。',
      ar: 'علاج لإزالة سموم فروة الرأس بزيت الأرغان المغربي والزنجبيل الطازج، وتدليك يحفّز نمو الشعر ويعيد إصلاح الشعر التالف ويعزّز لمعانه الطبيعي.',
    },
    icon: 'solar:sun-bold-duotone',
    duration: { vi: '60 phút', en: '60 min', fr: '60 min', cn: '60 min', ar: '60 min' },
    price: {
      vi: '750.000₫',
      en: '750,000₫',
      fr: '750,000₫',
      cn: '750,000₫',
      ar: '750,000₫',
    },
    badge: null,
    image: SPA4_IMAGES.treat4,
    color: '#E3F2FD',
  },
];

export const SPA4_SPECIALISTS = [
  {
    name: 'Minh Châu',
    title: {
      vi: 'Chuyên gia K-Beauty',
      en: 'K-Beauty Specialist',
      fr: 'Spécialiste K-Beauty',
      cn: 'K-Beauty 专家',
      ar: 'أخصائية K-Beauty',
    },
    experience: '8',
    specialty: {
      vi: 'Chăm sóc da Hàn Quốc',
      en: 'Korean Skincare',
      fr: 'Soin de la peau coréen',
      cn: '韩式护肤',
      ar: 'العناية بالبشرة الكورية',
    },
    image: SPA4_IMAGES.team1,
    rating: 4.9,
    reviews: 234,
  },
  {
    name: 'Lan Anh',
    title: {
      vi: 'Massage Therapist',
      en: 'Massage Therapist',
      fr: 'Massothérapeute',
      cn: '按摩理疗师',
      ar: 'أخصائية تدليك',
    },
    experience: '10',
    specialty: {
      vi: 'Đá ngọc & Kinh lạc',
      en: 'Jade Stone & Meridian',
      fr: 'Pierre de jade & méridiens',
      cn: '玉石与经络',
      ar: 'حجر اليشم وخطوط الطاقة',
    },
    image: SPA4_IMAGES.team2,
    rating: 4.8,
    reviews: 189,
  },
  {
    name: 'Thùy Dương',
    title: {
      vi: 'Body Treatment Expert',
      en: 'Body Treatment Expert',
      fr: 'Experte en soins du corps',
      cn: '身体护理专家',
      ar: 'خبيرة علاجات الجسم',
    },
    experience: '6',
    specialty: {
      vi: 'Liệu pháp Nhật Bản',
      en: 'Japanese Therapy',
      fr: 'Thérapie japonaise',
      cn: '日式疗法',
      ar: 'العلاج الياباني',
    },
    image: SPA4_IMAGES.team3,
    rating: 5.0,
    reviews: 156,
  },
  {
    name: 'Hà Phương',
    title: {
      vi: 'Trichology Specialist',
      en: 'Trichology Specialist',
      fr: 'Spécialiste en trichologie',
      cn: '毛发学专家',
      ar: 'أخصائية علم الشعر',
    },
    experience: '7',
    specialty: {
      vi: 'Phục hồi tóc & da đầu',
      en: 'Hair & Scalp Restoration',
      fr: 'Restauration cheveux & cuir chevelu',
      cn: '头发与头皮修复',
      ar: 'استعادة الشعر وفروة الرأس',
    },
    image: SPA4_IMAGES.team4,
    rating: 4.9,
    reviews: 112,
  },
];

export const SPA4_MEMBERSHIPS = [
  {
    tier: { vi: 'Jade', en: 'Jade', fr: 'Jade', cn: 'Jade', ar: 'Jade' },
    color: '#4CAF50',
    price: '2.500.000₫',
    description: {
      vi: 'Lý tưởng cho người mới bắt đầu hành trình làm đẹp',
      en: 'Ideal for those starting their beauty journey',
      fr: 'Idéal pour celles qui débutent leur parcours beauté',
      cn: '适合开启美丽旅程的初学者',
      ar: 'مثالي لمن يبدأن رحلة الجمال',
    },
    features: {
      vi: [
        '2 liệu trình/tháng (tự chọn)',
        'Giảm 10% tất cả dịch vụ',
        'Chào đón: Bộ skincare mini',
        'Ưu tiên đặt lịch online',
      ],
      en: [
        '2 treatments/month (your choice)',
        '10% off all services',
        'Welcome: Mini skincare kit',
        'Priority online booking',
      ],
      fr: [
        '2 soins/mois (au choix)',
        '10 % de réduction sur tous les services',
        'Bienvenue : Mini kit de soins',
        'Réservation en ligne prioritaire',
      ],
      cn: ['每月2次护理（自选）', '所有服务9折优惠', '欢迎礼：迷你护肤套装', '优先在线预约'],
      ar: [
        'علاجان شهرياً (حسب اختيارك)',
        'خصم 10% على جميع الخدمات',
        'هدية ترحيبية: طقم عناية مصغّر',
        'أولوية الحجز عبر الإنترنت',
      ],
    },
    popular: false,
  },
  {
    tier: { vi: 'Blossom', en: 'Blossom', fr: 'Blossom', cn: 'Blossom', ar: 'Blossom' },
    color: '#E91E63',
    price: '4.500.000₫',
    description: {
      vi: 'Trải nghiệm spa trọn vẹn mỗi tuần',
      en: 'Complete spa experience every week',
      fr: 'Une expérience spa complète chaque semaine',
      cn: '每周完整的水疗体验',
      ar: 'تجربة سبا متكاملة كل أسبوع',
    },
    features: {
      vi: [
        '4 liệu trình/tháng (tự chọn)',
        'Giảm 20% tất cả dịch vụ',
        'Tặng 1 liệu trình sinh nhật',
        'Phòng VIP riêng biệt',
        'Nước uống thảo dược cao cấp',
      ],
      en: [
        '4 treatments/month (your choice)',
        '20% off all services',
        'Free birthday treatment',
        'Private VIP room',
        'Premium herbal drinks',
      ],
      fr: [
        '4 soins/mois (au choix)',
        '20 % de réduction sur tous les services',
        'Soin d’anniversaire offert',
        'Salle VIP privée',
        'Boissons aux herbes premium',
      ],
      cn: ['每月4次护理（自选）', '所有服务8折优惠', '免费生日护理', '专属VIP房间', '高级草本饮品'],
      ar: [
        '4 علاجات شهرياً (حسب اختيارك)',
        'خصم 20% على جميع الخدمات',
        'علاج مجاني في عيد الميلاد',
        'غرفة VIP خاصة',
        'مشروبات عشبية فاخرة',
      ],
    },
    popular: true,
  },
  {
    tier: {
      vi: 'Sakura Gold',
      en: 'Sakura Gold',
      fr: 'Sakura Gold',
      cn: 'Sakura Gold',
      ar: 'Sakura Gold',
    },
    color: '#FF9800',
    price: '8.000.000₫',
    description: {
      vi: 'Đỉnh cao của sự sang trọng và chăm sóc',
      en: 'The pinnacle of luxury and care',
      fr: 'Le summum du luxe et du soin',
      cn: '奢华与呵护的巅峰',
      ar: 'قمة الفخامة والعناية',
    },
    features: {
      vi: [
        'Không giới hạn liệu trình',
        'Giảm 30% tất cả dịch vụ',
        'Chuyên gia riêng phục vụ',
        'Xe đưa đón miễn phí',
        'Bộ sản phẩm cao cấp hàng tháng',
        'Ưu tiên tuyệt đối mọi dịch vụ',
      ],
      en: [
        'Unlimited treatments',
        '30% off all services',
        'Dedicated personal specialist',
        'Free shuttle service',
        'Monthly premium product set',
        'Absolute priority for all services',
      ],
      fr: [
        'Soins illimités',
        '30 % de réduction sur tous les services',
        'Spécialiste personnel dédié',
        'Service de navette gratuit',
        'Coffret de produits premium mensuel',
        'Priorité absolue pour tous les services',
      ],
      cn: [
        '无限次护理',
        '所有服务7折优惠',
        '专属私人专家',
        '免费接送服务',
        '每月高级产品套装',
        '所有服务绝对优先',
      ],
      ar: [
        'علاجات غير محدودة',
        'خصم 30% على جميع الخدمات',
        'أخصائية شخصية مخصّصة',
        'خدمة نقل مجانية',
        'مجموعة منتجات فاخرة شهرياً',
        'أولوية مطلقة لجميع الخدمات',
      ],
    },
    popular: false,
  },
];

export const SPA4_TESTIMONIALS = [
  {
    name: 'Nguyễn Thu Hà',
    location: { vi: 'Hà Nội', en: 'Hanoi', fr: 'Hanoï', cn: '河内', ar: 'هانوي' },
    rating: 5,
    comment: {
      vi: 'K-Beauty Glow Ritual thực sự thay đổi làn da của tôi! Chỉ sau 3 buổi, da căng mịn, sáng bóng hơn hẳn. Chị Minh Châu rất chuyên nghiệp và tâm huyết.',
      en: 'K-Beauty Glow Ritual truly transformed my skin! After just 3 sessions, it became visibly firmer, smoother, and brighter. Minh Chau is incredibly professional and dedicated.',
      fr: 'Le K-Beauty Glow Ritual a vraiment transformé ma peau ! Après seulement 3 séances, elle est devenue visiblement plus ferme, plus lisse et plus lumineuse. Minh Chau est incroyablement professionnelle et dévouée.',
      cn: 'K-Beauty Glow Ritual 真正改变了我的肌肤！仅仅3次护理后，肌肤明显更紧致、更光滑、更亮泽。Minh Châu 非常专业且用心。',
      ar: 'لقد غيّر K-Beauty Glow Ritual بشرتي حقاً! بعد ثلاث جلسات فقط، أصبحت أكثر شداً ونعومةً وإشراقاً بشكل ملحوظ. مينه تشاو محترفة ومتفانية بشكل لا يُصدّق.',
    },
    service: {
      vi: 'K-Beauty Glow Ritual',
      en: 'K-Beauty Glow Ritual',
      fr: 'K-Beauty Glow Ritual',
      cn: 'K-Beauty Glow Ritual',
      ar: 'K-Beauty Glow Ritual',
    },
    avatar: 'H',
    avatarColor: '#E8F5E9',
  },
  {
    name: 'Trần Bảo Ngọc',
    location: {
      vi: 'TP. Hồ Chí Minh',
      en: 'Ho Chi Minh City',
      fr: 'Hô Chi Minh-Ville',
      cn: '胡志明市',
      ar: 'مدينة هو تشي منه',
    },
    rating: 5,
    comment: {
      vi: 'Jade Stone Massage khác hoàn toàn với massage thông thường. Cảm giác đá ngọc chạy dọc theo kinh mạch thật kỳ diệu, căng thẳng tan biến hoàn toàn.',
      en: 'Jade Stone Massage is completely different from regular massage. The sensation of jade stones gliding along the meridians is magical — stress just melts away.',
      fr: 'Le Jade Stone Massage est complètement différent d’un massage classique. La sensation des pierres de jade glissant le long des méridiens est magique — le stress s’évapore tout simplement.',
      cn: 'Jade Stone Massage 与普通按摩完全不同。玉石沿着经络滑动的感觉太神奇了——压力瞬间消融。',
      ar: 'تدليك حجر اليشم مختلف تماماً عن التدليك العادي. الإحساس بانزلاق أحجار اليشم على طول خطوط الطاقة ساحر — يذوب التوتر ببساطة.',
    },
    service: {
      vi: 'Jade Stone Massage',
      en: 'Jade Stone Massage',
      fr: 'Jade Stone Massage',
      cn: 'Jade Stone Massage',
      ar: 'Jade Stone Massage',
    },
    avatar: 'N',
    avatarColor: '#F3E5F5',
  },
  {
    name: 'Lê Minh Thư',
    location: { vi: 'Đà Nẵng', en: 'Da Nang', fr: 'Da Nang', cn: '岣港', ar: 'دا نانغ' },
    rating: 5,
    comment: {
      vi: 'Không gian tại Jade Blossom cực kỳ yên tĩnh và thơ mộng. Sakura Body Wrap khiến da tôi mịn như lụa sau khi ủ. Nhất định sẽ quay lại!',
      en: 'The atmosphere at Jade Blossom is incredibly serene and poetic. The Sakura Body Wrap left my skin as smooth as silk. I will definitely return!',
      fr: 'L’atmosphère chez Jade Blossom est incroyablement sereine et poétique. Le Sakura Body Wrap a laissé ma peau douce comme de la soie. Je reviendrai sans hésiter !',
      cn: 'Jade Blossom 的氛围格外宁静而富有诗意。Sakura Body Wrap 让我的肌肤如丝般柔滑。我一定会再来！',
      ar: 'الأجواء في Jade Blossom هادئة وشاعرية بشكل لا يُصدّق. تركت Sakura Body Wrap بشرتي ناعمة كالحرير. سأعود بالتأكيد!',
    },
    service: {
      vi: 'Sakura Blossom Body Wrap',
      en: 'Sakura Blossom Body Wrap',
      fr: 'Sakura Blossom Body Wrap',
      cn: 'Sakura Blossom Body Wrap',
      ar: 'Sakura Blossom Body Wrap',
    },
    avatar: 'T',
    avatarColor: '#FFF3E0',
  },
];

export const SPA4_BOOKING_SERVICES = {
  vi: [
    'K-Beauty Glow Ritual (90 phút)',
    'Jade Stone Massage (75 phút)',
    'Sakura Blossom Body Wrap (110 phút)',
    'Scalp & Hair Detox (60 phút)',
  ],
  en: [
    'K-Beauty Glow Ritual (90 min)',
    'Jade Stone Massage (75 min)',
    'Sakura Blossom Body Wrap (110 min)',
    'Scalp & Hair Detox (60 min)',
  ],
  fr: [
    'K-Beauty Glow Ritual (90 min)',
    'Jade Stone Massage (75 min)',
    'Sakura Blossom Body Wrap (110 min)',
    'Scalp & Hair Detox (60 min)',
  ],
  cn: [
    'K-Beauty Glow Ritual (90 min)',
    'Jade Stone Massage (75 min)',
    'Sakura Blossom Body Wrap (110 min)',
    'Scalp & Hair Detox (60 min)',
  ],
  ar: [
    'K-Beauty Glow Ritual (90 min)',
    'Jade Stone Massage (75 min)',
    'Sakura Blossom Body Wrap (110 min)',
    'Scalp & Hair Detox (60 min)',
  ],
};
