// ----------------------------------------------------------------------
// spa2 sub-pages – Nature & Wellness theme (teal / cream / sage)
// Distinct from spa1 (dark luxury) – soft, organic, airy, eco-friendly.
//
// All sample/demo content lives in src/_mock/_spa2 (the single source of
// truth shared with the dashboard mock API in src/api/spa2/mock). This file
// re-exports that data under its historical names, plus the spa2 theme
// color tokens, so existing imports across the app keep working unchanged.
//
// IMPORTANT: do not import data back from src/_mock/_spa2 into new local
// consts here — that previously created an import cycle. Only theme tokens
// (colors) should be defined in this file.
// ----------------------------------------------------------------------

export {
  spa2Team,
  spa2Faqs,
  spa2Offers,
  spa2Careers,
  spa2Gallery,
  spa2Services,
  spa2Branches,
  spa2Partners,
  spa2Policies,
  spa2Feedbacks,
  spa2Treatments,
  spa2Promotions,
  spa2AboutStory,
  spa2UpsertPost,
  spa2DeletePost,
  spa2BlogBanner,
  spa2AboutBanner,
  spa2ContactInfo,
  spa2ComboOffers,
  spa2JoinReasons,
  spa2Instructors,
  spa2OffersBanner,
  SPA2_PAGE_IMAGES,
  spa2ServiceSteps,
  spa2VideoReviews,
  spa2BeforeAfters,
  spa2QualityCerts,
  spa2Technologies,
  spa2ContactBanner,
  spa2BookingBanner,
  spa2CareersBanner,
  SPA2_SERVICE_META,
  SPA2_PACKAGE_META,
  type Spa2BlogPost,
  spa2VisionMission,
  spa2CareersSlogan,
  spa2ExtraPartners,
  spa2ServicesBanner,
  spa2Certifications,
  spa2Collaborations,
  spa2TrainingBanner,
  spa2AboutStoryImage,
  spa2PartnerProfiles,
  spa2BookingPackages,
  spa2TrainingMission,
  spa2TrainingRoadmap,
  type Spa2BlogBanner,
  spa2TrainingPrograms,
  spa2WorkplaceGallery,
  spa2GraduateShowcase,
  spa2TreatmentProcess,
  spa2TreatmentExperts,
  SPA2_TESTIMONIAL_META,
  spa2ServiceCategories,
  spa2PartnerCategories,
  type Spa2OffersBanner,
  spa2RecruitmentProcess,
  spa2InternalVideo,
  spa2InternalVideoUrl,
  spa2InternalVideoThumb,
  type Spa2BookingBanner,
  type Spa2InternalVideo,
  type Spa2CareersBanner,
  type Spa2ContactBanner,
  type Spa2ServicesBanner,
  type Spa2TrainingBanner,
  spa2TrainingMissionImage,
  type Spa2AdjustableImage,
  type Spa2AboutTeamMember,
  type Spa2TrainingProgram,
  SPA2_BLOG_CATEGORY_NAMES,
  type Spa2TrainingGraduate,
  computeSpa2BlogCategories,
  type Spa2AboutCertification,
  SPA2_POSTS as spa2BlogPosts,
  type Spa2TrainingInstructor,
  type Spa2TrainingRoadmapStage,
  type Spa2AboutVisionMissionItem,
  SPA2_BLOG_CATEGORIES as spa2BlogCategories,
  spa2WorkplaceVideos,
  type Spa2WorkplaceVideo,
  type Spa2ComboStatus,
  SPA2_COMBO_CATEGORIES,
  type Spa2OfferPaymentStatus,
  SPA2_OFFER_REDEMPTIONS,
  SPA2_CONTACT_SUBMISSIONS,
  SPA2_CAREER_APPLICATIONS,
  SPA2_SERVICE_REGISTRATIONS,
  SPA2_TRAINING_REGISTRATIONS,
  type Spa2OfferRedemption,
  type Spa2ContactSubmission,
  type Spa2CareerApplication,
  type Spa2ServiceRegistration,
  type Spa2TrainingRegistration,
  type Spa2OfferRedemptionType,
  type Spa2OfferRedemptionStatus,
  type Spa2ContactSubmissionStatus,
  type Spa2CareerApplicationStatus,
  type Spa2ServiceRegistrationStatus,
  type Spa2TrainingRegistrationStatus,
  spa2FeedbackBanner,
  spa2FlashSale,
  spa2PromotionsBanner,
  spa2BranchesBanner,
  spa2AccountBanner,
  SPA2_ACCOUNT_CONTENT,
  spa2PartnersBanner,
  spa2TreatmentsBanner,
  spa2BeforeAfterBanner,
  spa2FaqBanner,
  spa2FaqCategories,
  spa2PolicyBanner,
  spa2PolicyArticles,
  spa2GalleryBanner,
  spa2PolicyArticleContent,
  type Spa2Branch,
  type Spa2FeedbackStatus,
  type Spa2FeedbackBanner,
  type Spa2Promotion,
  type Spa2FlashSale,
  type Spa2Appointment,
  type Spa2Treatment,
  type Spa2BeforeAfter,
  type Spa2PartnerProfile,
  type Spa2PromotionsBanner,
  type Spa2BranchesBanner,
  type Spa2AccountBanner,
  type Spa2AccountContent,
  type Spa2PartnersBanner,
  type Spa2TreatmentsBanner,
  type Spa2BeforeAfterStatus,
  type Spa2BeforeAfterBanner,
  type Spa2Faq,
  type Spa2FaqStat,
  type Spa2FaqBanner,
  type Spa2FaqCategory,
  type Spa2PolicyCard,
  type Spa2PolicyTier,
  type Spa2PolicyAlert,
  type Spa2PolicyBanner,
  type Spa2PolicyArticle,
  type Spa2GalleryBanner,
  type Spa2PolicyCertChip,
  type Spa2PolicyTableRow,
  type Spa2PolicyHighlight,
  type Spa2QualityCert,
  type Spa2Collaboration,
  type Spa2PartnerCategory,
  type Spa2PolicyTimelineStep,
  type Spa2PolicyArticleContent,
  spa2MembershipTiers,
  spa2MembershipBanner,
  SPA2_MEMBERSHIP_SIGNUPS,
  spa2MembershipCompareRows,
  spa2GiftCardBanner,
  spa2GiftCardReasons,
  spa2GiftCardDesigns,
  SPA2_GIFT_CARD_ORDERS,
  spa2GiftCardDenominations,
  spa2WellnessAddons,
  spa2WellnessPackages,
  spa2WellnessPackageBanner,
  type Spa2MembershipTier,
  type Spa2MembershipBanner,
  type Spa2MembershipSignup,
  type Spa2MembershipCompareRow,
  type Spa2MembershipSignupStatus,
  type Spa2GiftCardBanner,
  type Spa2GiftCardDesign,
  type Spa2GiftCardOrder,
  type Spa2GiftCardReason,
  type Spa2GiftCardOrderStatus,
  type Spa2WellnessAddon,
  type Spa2WellnessPackageItem,
  type Spa2WellnessPackageBanner,
  spa2ShopBanner,
  spa2ShopProducts,
  spa2ShopCategories,
  spa2CorporateBanner,
  spa2CorporatePlans,
  spa2CorporateBenefits,
  spa2SkinQuizBanner,
  spa2SkinQuizResults,
  spa2SkinQuizQuestions,
  spa2CorporateServiceChannels,
  type Spa2ShopBanner,
  type Spa2ShopProduct,
  type Spa2ShopCategory,
  type Spa2CorporateBanner,
  type Spa2CorporatePlan,
  type Spa2CorporateBenefit,
  type Spa2SkinQuizBanner,
  type Spa2SkinQuizResult,
  type Spa2SkinQuizQuestion,
  type Spa2CorporateServiceChannel,
} from 'src/_mock/_spa2';

// ---------- Theme tokens ---------------------------------------------

export const SPA2_TEAL = '#2E8B7A';
export const SPA2_TEAL_DARK = '#1D6B5C';
export const SPA2_TEAL_LIGHT = '#5AB5A3';
export const SPA2_CREAM = '#F9F6F1';
export const SPA2_CREAM_DARK = '#EFE8DC';
export const SPA2_SAGE = '#A8C5B8';
export const SPA2_WARM = '#E8DDD3';
export const SPA2_INK = '#1F2A28';
export const SPA2_LEAF = '#7BAE96';
