// ----------------------------------------------------------------------
// spa2 sub-pages – Nature & Wellness theme (teal / cream / sage)
// Distinct from spa1 (dark luxury) – soft, organic, airy, eco-friendly.
//
// All sample/demo content lives in src/_mock/_spa2 (the single source of
// truth shared with the dashboard mock API in src/api/spa2/mock). This file
// re-exports that data under its historical names, plus the spa2 theme
// color tokens, so existing imports across the app keep working unchanged.
//
// IMPORTANT: do not import data back from src/_mock/_spa2 into new local
// consts here — that previously created an import cycle. Only theme tokens
// (colors) should be defined in this file.
// ----------------------------------------------------------------------

export {
  spa2Team,
  spa2Faqs,
  spa2Offers,
  spa2Events,
  spa2Careers,
  spa2Gallery,
  spa2MenFaqs,
  spa2Services,
  spa2Branches,
  spa2Partners,
  spa2Policies,
  type Spa2Faq,
  spa2VipRooms,
  spa2HairTips,
  spa2Feedbacks,
  spa2FlashSale,
  spa2FaqBanner,
  spa2SleepTips,
  spa2Graduates,
  spa2Treatments,
  spa2Promotions,
  spa2AboutStory,
  spa2UpsertPost,
  spa2DeletePost,
  spa2BlogBanner,
  spa2ShopBanner,
  type Spa2Event,
  spa2Therapists,
  spa2GroupTiers,
  spa2VideoItems,
  spa2AboutBanner,
  spa2ContactInfo,
  spa2ComboOffers,
  spa2JoinReasons,
  spa2Instructors,
  type Spa2Branch,
  spa2ReviewStats,
  spa2Consultants,
  spa2PressAwards,
  spa2PressBanner,
  spa2Ingredients,
  spa2MenSpaStats,
  spa2MenServices,
  spa2MenPackages,
  type Spa2MenFaq,
  spa2VoucherFaqs,
  spa2OffersBanner,
  SPA2_PAGE_IMAGES,
  spa2ServiceSteps,
  spa2VideoReviews,
  spa2BeforeAfters,
  spa2QualityCerts,
  spa2Technologies,
  spa2PolicyBanner,
  type Spa2FaqStat,
  spa2ShopProducts,
  spa2EventsBanner,
  spa2HomeServices,
  spa2EtiquetteDos,
  spa2ReviewBanner,
  spa2VipRoomPerks,
  type Spa2VipRoom,
  spa2PressContact,
  spa2MenSpaBanner,
  spa2HairServices,
  type Spa2HairTip,
  spa2KidsServices,
  spa2ContactBanner,
  spa2BookingBanner,
  spa2CareersBanner,
  SPA2_SERVICE_META,
  SPA2_PACKAGE_META,
  type Spa2BlogPost,
  spa2VisionMission,
  spa2CareersSlogan,
  spa2ExtraPartners,
  spa2InternalVideo,
  spa2AccountBanner,
  spa2FaqCategories,
  spa2GalleryBanner,
  spa2ReferralSteps,
  spa2AppDownloadQr,
  spa2ReviewAspects,
  spa2SuperfoodTips,
  spa2VipRoomBanner,
  spa2PressArticles,
  spa2SpaMenuBanner,
  spa2SleepPrograms,
  type Spa2SleepTip,
  spa2AgingConcerns,
  spa2HotelPartners,
  spa2GroupServices,
  type Spa2Graduate,
  spa2WaitlistSlots,
  spa2KidsSpaBanner,
  spa2ServicesBanner,
  spa2Certifications,
  spa2Collaborations,
  spa2TrainingBanner,
  spa2FeedbackBanner,
  spa2BranchesBanner,
  spa2PartnersBanner,
  spa2PolicyArticles,
  type Spa2Promotion,
  type Spa2FlashSale,
  type Spa2Treatment,
  type Spa2FaqBanner,
  spa2GiftCardBanner,
  spa2WellnessAddons,
  spa2ShopCategories,
  spa2CorporatePlans,
  spa2SkinQuizBanner,
  spa2ReferralBanner,
  spa2EtiquetteDonts,
  spa2EtiquetteOffer,
  spa2LoyaltyRewards,
  spa2NutritionPlans,
  spa2NutritionStats,
  spa2AffiliateTiers,
  spa2AffiliateStats,
  spa2AffiliateSteps,
  spa2SkinSchoolQuiz,
  type Spa2Therapist,
  spa2AyurvedaBanner,
  spa2SpaHotelBanner,
  spa2CommunityPosts,
  spa2FranchiseStats,
  spa2FranchiseSteps,
  spa2GroupOccasions,
  type Spa2GroupTier,
  spa2WaitlistBanner,
  type Spa2VideoItem,
  spa2VoucherRecords,
  spa2AboutStoryImage,
  spa2PartnerProfiles,
  spa2BookingPackages,
  spa2TrainingMission,
  spa2TrainingRoadmap,
  type Spa2BlogBanner,
  spa2WorkplaceVideos,
  type Spa2PolicyCard,
  type Spa2PolicyTier,
  spa2MembershipTiers,
  spa2GiftCardReasons,
  spa2GiftCardDesigns,
  spa2CorporateBanner,
  spa2SkinQuizResults,
  type Spa2ShopBanner,
  spa2ReferralProgram,
  spa2EventCategories,
  spa2AppDownloadHero,
  spa2HomeServiceFaqs,
  spa2SkinDiaryBanner,
  spa2EtiquetteGuides,
  spa2SeasonalSeasons,
  type Spa2Consultant,
  spa2NutritionBanner,
  type Spa2PressAward,
  spa2AffiliateBanner,
  spa2SpaFinderBanner,
  spa2SpaMenuSections,
  type Spa2Ingredient,
  spa2PrenatalReasons,
  type Spa2MenSpaStat,
  type Spa2MenService,
  type Spa2MenPackage,
  spa2AntiAgingBanner,
  spa2AntiAgingStages,
  spa2WaterTreatments,
  spa2CommunityBanner,
  spa2FranchiseBanner,
  spa2FranchiseModels,
  spa2PriceListBanner,
  type Spa2VoucherFaq,
  spa2TrainingPrograms,
  spa2WorkplaceGallery,
  spa2GraduateShowcase,
  spa2TreatmentProcess,
  spa2TreatmentExperts,
  spa2InternalVideoUrl,
  type Spa2ComboStatus,
  spa2PromotionsBanner,
  SPA2_ACCOUNT_CONTENT,
  spa2TreatmentsBanner,
  type Spa2Appointment,
  type Spa2BeforeAfter,
  type Spa2FaqCategory,
  type Spa2PolicyAlert,
  type Spa2QualityCert,
  spa2MembershipBanner,
  spa2WellnessPackages,
  type Spa2ShopProduct,
  spa2HomeServiceAreas,
  spa2OccasionPackages,
  type Spa2HomeService,
  spa2SkinDiaryEntries,
  spa2MedicalSpaBanner,
  spa2LoyaltyEarnRules,
  type Spa2ReviewStats,
  spa2SeasonalPackages,
  type Spa2VipRoomPerk,
  type Spa2PressBanner,
  spa2NewsletterConfig,
  spa2NewsletterBanner,
  type Spa2SpaMenuItem,
  spa2SkinSchoolBanner,
  spa2PrenatalServices,
  spa2HairBeautyBanner,
  type Spa2HairService,
  spa2VideoGuideBanner,
  type Spa2KidsService,
  spa2KidsSafetyBadges,
  SPA2_TESTIMONIAL_META,
  spa2ServiceCategories,
  spa2PartnerCategories,
  type Spa2OffersBanner,
  SPA2_COMBO_CATEGORIES,
  spa2BeforeAfterBanner,
  type Spa2PolicyBanner,
  SPA2_GIFT_CARD_ORDERS,
  spa2CorporateBenefits,
  spa2SkinQuizQuestions,
  type Spa2ShopCategory,
  type Spa2EventsBanner,
  type Spa2ReferralStep,
  spa2HomeServiceBanner,
  spa2AppDownloadStores,
  spa2MindfulnessBanner,
  spa2MedicalTreatments,
  type Spa2ReviewAspect,
  type Spa2ReviewBanner,
  type Spa2SuperfoodTip,
  spa2AppointmentBanner,
  type Spa2PressArticle,
  type Spa2PressContact,
  spa2SkinSchoolCourses,
  type Spa2SleepProgram,
  spa2PrenatalSpaBanner,
  spa2WellnessQuestions,
  type Spa2MenSpaBanner,
  type Spa2AgingConcern,
  spa2WaterScienceFacts,
  type Spa2HotelPartner,
  spa2FranchiseBenefits,
  type Spa2GroupService,
  type Spa2WaitlistSlot,
  SPA2_WAITLIST_ENTRIES,
  spa2RecruitmentProcess,
  spa2InternalVideoThumb,
  type Spa2BookingBanner,
  type Spa2InternalVideo,
  type Spa2CareersBanner,
  type Spa2ContactBanner,
  SPA2_OFFER_REDEMPTIONS,
  type Spa2AccountBanner,
  type Spa2PolicyArticle,
  type Spa2GalleryBanner,
  type Spa2Collaboration,
  type Spa2GiftCardOrder,
  type Spa2WellnessAddon,
  type Spa2CorporatePlan,
  type Spa2EventCategory,
  spa2AppDownloadCompats,
  spa2AppDownloadScreens,
  spa2HomeServiceProcess,
  spa2OccasionCategories,
  type Spa2AppDownloadQr,
  spa2AppDownloadReviews,
  type Spa2EtiquetteRule,
  spa2SpaEtiquetteBanner,
  type Spa2LoyaltyReward,
  type Spa2NutritionPlan,
  type Spa2NutritionStat,
  spa2ConsultationBanner,
  type Spa2VipRoomBanner,
  spa2AppointmentHistory,
  type Spa2AffiliateTier,
  type Spa2AffiliateStat,
  type Spa2AffiliateStep,
  spa2NewsletterBenefits,
  type Spa2SpaMenuBanner,
  SPA2_OCCASION_BOOKINGS,
  spa2WaterTherapyBanner,
  spa2AyurvedaTreatments,
  spa2StaycationPackages,
  type Spa2CommunityPost,
  type Spa2FranchiseStat,
  type Spa2FranchiseStep,
  spa2GroupBookingBanner,
  type Spa2GroupOccasion,
  spa2CompletionPrograms,
  spa2VoucherCheckBanner,
  type Spa2VoucherRecord,
  SPA2_THERAPIST_REVIEWS,
  type Spa2WaitlistEntry,
  type Spa2KidsSpaBanner,
  type Spa2ServicesBanner,
  type Spa2TrainingBanner,
  type Spa2WorkplaceVideo,
  type Spa2FeedbackStatus,
  type Spa2FeedbackBanner,
  type Spa2PartnerProfile,
  type Spa2BranchesBanner,
  type Spa2AccountContent,
  type Spa2PartnersBanner,
  type Spa2PolicyCertChip,
  type Spa2PolicyTableRow,
  SPA2_MEMBERSHIP_SIGNUPS,
  type Spa2MembershipTier,
  type Spa2GiftCardBanner,
  type Spa2GiftCardDesign,
  type Spa2GiftCardReason,
  type Spa2SkinQuizBanner,
  type Spa2SkinQuizResult,
  spa2ReferralLeaderboard,
  spa2SustainabilityStats,
  type Spa2ReferralBanner,
  spa2AppDownloadFeatures,
  type Spa2HomeServiceFaq,
  type Spa2SkinDiaryEntry,
  spa2MindfulnessBenefits,
  spa2MindfulnessPrograms,
  type Spa2EtiquetteOffer,
  type Spa2EtiquetteGuide,
  type Spa2SeasonalSeason,
  spa2AppointmentUpcoming,
  spa2SpaFinderTherapists,
  type Spa2SpaMenuSection,
  spa2SleepWellnessBanner,
  type Spa2PrenatalReason,
  type Spa2AntiAgingStage,
  type Spa2WaterTreatment,
  type Spa2AyurvedaBanner,
  type Spa2SpaHotelBanner,
  spa2CommunityChallenges,
  type Spa2FranchiseModel,
  type Spa2WaitlistBanner,
  spa2AccessibilityBanner,
  SPA2_THERAPIST_BOOKINGS,
  spa2TrainingMissionImage,
  type Spa2AdjustableImage,
  type Spa2AboutTeamMember,
  type Spa2TrainingProgram,
  SPA2_BLOG_CATEGORY_NAMES,
  SPA2_CONTACT_SUBMISSIONS,
  SPA2_CAREER_APPLICATIONS,
  type Spa2OfferRedemption,
  spa2PolicyArticleContent,
  type Spa2PolicyHighlight,
  type Spa2PartnerCategory,
  type Spa2CorporateBanner,
  spa2SustainabilityBanner,
  type Spa2ReferralProgram,
  type Spa2AppDownloadHero,
  type Spa2HomeServiceArea,
  type Spa2OccasionPackage,
  type Spa2SkinDiaryBanner,
  spa2MindfulnessChallenge,
  spa2MedicalSpaCategories,
  spa2LoyaltyRewardsBanner,
  spa2LoyaltyPointsBalance,
  type Spa2LoyaltyEarnRule,
  type Spa2ReviewRatingRow,
  type Spa2NutritionBanner,
  spa2ConsultationBookings,
  spa2PackageBuilderBanner,
  type Spa2AffiliateBanner,
  type Spa2SpaFinderBanner,
  SPA2_LOYALTY_REDEMPTIONS,
  type Spa2OccasionBooking,
  spa2PrenatalSafetyBadges,
  type Spa2PrenatalService,
  type Spa2AntiAgingBanner,
  spa2AyurvedaPhilosophies,
  type Spa2CommunityBanner,
  type Spa2FranchiseBanner,
  type Spa2PriceListBanner,
  type Spa2TherapistReview,
  type Spa2KidsSafetyBadge,
  type Spa2TrainingGraduate,
  computeSpa2BlogCategories,
  type Spa2PromotionsBanner,
  type Spa2TreatmentsBanner,
  spa2MembershipCompareRows,
  spa2GiftCardDenominations,
  spa2WellnessPackageBanner,
  type Spa2MembershipBanner,
  type Spa2MembershipSignup,
  type Spa2CorporateBenefit,
  type Spa2SkinQuizQuestion,
  type Spa2AppDownloadStore,
  type Spa2OccasionCategory,
  spa2MedicalSpaCredentials,
  type Spa2MedicalSpaBanner,
  type Spa2MedicalTreatment,
  type Spa2PressArticleType,
  type Spa2NewsletterConfig,
  type Spa2NewsletterBanner,
  spa2IngredientGuideBanner,
  type Spa2IngredientSafety,
  SPA2_MINDFULNESS_BOOKINGS,
  type Spa2SkinSchoolBanner,
  type Spa2SkinSchoolCourse,
  type Spa2WellnessQuestion,
  type Spa2HairBeautyBanner,
  type Spa2WaterScienceFact,
  type Spa2FranchiseBenefit,
  spa2CertificateWallBanner,
  type Spa2VideoGuideBanner,
  spa2AccessibilityFeatures,
  type Spa2TherapistBooking,
  SPA2_SERVICE_REGISTRATIONS,
  type Spa2ContactSubmission,
  type Spa2CareerApplication,
  type Spa2BeforeAfterStatus,
  type Spa2BeforeAfterBanner,
  spa2AppDownloadRatingStats,
  type Spa2HomeServiceBanner,
  spa2SpecialOccasionsBanner,
  type Spa2AppDownloadCompat,
  type Spa2AppDownloadReview,
  type Spa2MindfulnessBanner,
  spa2NutritionQuizQuestions,
  type Spa2AppointmentStatus,
  type Spa2AppointmentRecord,
  type Spa2AppointmentBanner,
  type Spa2NewsletterBenefit,
  SPA2_HOME_SERVICE_BOOKINGS,
  type Spa2LoyaltyRedemption,
  SPA2_INGREDIENT_CATEGORIES,
  spa2TherapistProfileBanner,
  type Spa2PrenatalSpaBanner,
  type Spa2AyurvedaTreatment,
  type Spa2StaycationPackage,
  type Spa2CompletionProgram,
  spa2AccessibilityChecklist,
  spa2SpecialNeedsCategories,
  type Spa2AboutCertification,
  SPA2_POSTS as spa2BlogPosts,
  type Spa2TrainingInstructor,
  type Spa2OfferPaymentStatus,
  SPA2_TRAINING_REGISTRATIONS,
  type Spa2PolicyTimelineStep,
  type Spa2SustainabilityStat,
  type Spa2AppDownloadFeature,
  type Spa2MindfulnessBenefit,
  type Spa2MindfulnessProgram,
  type Spa2MedicalSpaCategory,
  type Spa2SpaEtiquetteBanner,
  spa2LoyaltyRewardCategories,
  type Spa2ConsultationBanner,
  type Spa2SpaFinderTherapist,
  SPA2_PACKAGE_BUILDER_ORDERS,
  type Spa2HomeServiceBooking,
  type Spa2MindfulnessBooking,
  SPA2_NEWSLETTER_SUBSCRIBERS,
  type Spa2IngredientCategory,
  type Spa2WaterTherapyBanner,
  type Spa2AyurvedaPhilosophy,
  type Spa2CommunityChallenge,
  type Spa2GroupBookingBanner,
  type Spa2VoucherCheckBanner,
  SPA2_FRANCHISE_APPLICATIONS,
  SPA2_GROUP_BOOKING_REQUESTS,
  type Spa2ServiceRegistration,
  type Spa2OfferRedemptionType,
  type Spa2GiftCardOrderStatus,
  type Spa2WellnessPackageItem,
  spa2CorporateServiceChannels,
  spa2SustainabilityMilestones,
  type Spa2SeasonalPackageItem,
  type Spa2ConsultationBooking,
  spa2AppointmentLoyaltyPoints,
  type Spa2PackageBuilderOrder,
  SPA2_AFFILIATE_REGISTRATIONS,
  type Spa2SleepWellnessBanner,
  spa2WellnessAssessmentBanner,
  type Spa2AccessibilityBanner,
  type Spa2WaitlistEntryStatus,
  type Spa2GroupBookingRequest,
  type Spa2TrainingRoadmapStage,
  type Spa2TrainingRegistration,
  type Spa2PolicyArticleContent,
  type Spa2MembershipCompareRow,
  spa2SustainabilityCommitments,
  type Spa2SustainabilityBanner,
  type Spa2MindfulnessChallenge,
  type Spa2MedicalSpaCredential,
  type Spa2LoyaltyRewardsBanner,
  type Spa2PackageBuilderBanner,
  type Spa2NewsletterSubscriber,
  type Spa2AccessibilityFeature,
  type Spa2SpecialNeedsCategory,
  type Spa2FranchiseApplication,
  type Spa2OfferRedemptionStatus,
  type Spa2WellnessPackageBanner,
  type Spa2AppDownloadRatingStat,
  type Spa2LoyaltyRewardCategory,
  type Spa2NutritionQuizQuestion,
  type Spa2IngredientGuideBanner,
  type Spa2OccasionBookingStatus,
  type Spa2AffiliateRegistration,
  type Spa2CertificateWallBanner,
  type Spa2TherapistReviewStatus,
  type Spa2AboutVisionMissionItem,
  type Spa2MembershipSignupStatus,
  type Spa2HomeServiceProcessStep,
  type Spa2SpecialOccasionsBanner,
  spa2PackageBuilderDiscountTiers,
  type Spa2SkinSchoolQuizQuestion,
  type Spa2TherapistProfileBanner,
  type Spa2TherapistBookingStatus,
  type Spa2ContactSubmissionStatus,
  type Spa2CareerApplicationStatus,
  type Spa2CorporateServiceChannel,
  type Spa2SustainabilityMilestone,
  type Spa2LoyaltyRedemptionStatus,
  type Spa2ReferralLeaderboardEntry,
  type Spa2SustainabilityCommitment,
  type Spa2HomeServiceBookingStatus,
  type Spa2MindfulnessBookingStatus,
  type Spa2WellnessAssessmentBanner,
  type Spa2ServiceRegistrationStatus,
  type Spa2ConsultationBookingStatus,
  SPA2_MEDICAL_CONSULTATION_BOOKINGS,
  type Spa2MedicalConsultationStatus,
  type Spa2PackageBuilderOrderStatus,
  type Spa2GroupBookingRequestStatus,
  type Spa2TrainingRegistrationStatus,
  type Spa2PackageBuilderDiscountTier,
  type Spa2MedicalConsultationBooking,
  type Spa2NewsletterSubscriberStatus,
  type Spa2AccessibilityChecklistItem,
  type Spa2FranchiseApplicationStatus,
  type Spa2AffiliateRegistrationStatus,
  SPA2_BLOG_CATEGORIES as spa2BlogCategories,
} from 'src/_mock/_spa2';

// ---------- Theme tokens ---------------------------------------------

export const SPA2_TEAL = '#2E8B7A';
export const SPA2_TEAL_DARK = '#1D6B5C';
export const SPA2_TEAL_LIGHT = '#5AB5A3';
export const SPA2_CREAM = '#F9F6F1';
export const SPA2_CREAM_DARK = '#EFE8DC';
export const SPA2_SAGE = '#A8C5B8';
export const SPA2_WARM = '#E8DDD3';
export const SPA2_INK = '#1F2A28';
export const SPA2_LEAF = '#7BAE96';
