export type Spa9Lang = 'en' | 'vi' | 'fr' | 'cn' | 'ar';

export const SPA9_IMAGES = {
  hero: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1920&q=80',
  olive: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80',
  sea: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80',
  sun: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
  stone: 'https://images.unsplash.com/photo-1536237880829-dd873b2305cc?w=800&q=80',
  roman: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=1200&q=80',
};

export const SPA9_HERO_SLIDES = [
  {
    src: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1920&q=80',
    alt: 'Mediterranean beach',
  },
  {
    src: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1920&q=80',
    alt: 'Turquoise waters',
  },
  {
    src: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=1920&q=80',
    alt: 'Roman bath',
  },
  {
    src: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&q=80',
    alt: 'Sun retreat',
  },
];

export const SPA9_PILLARS = [
  {
    greek: 'Θαλασσοθεραπεία',
    titleKey: 'pillars.p1Title',
    descKey: 'pillars.p1Desc',
    color: '#1B6CA8',
    icon: 'solar:waterdrops-bold-duotone',
    image: SPA9_IMAGES.sea,
  },
  {
    greek: 'Ελαιόλαδο',
    titleKey: 'pillars.p2Title',
    descKey: 'pillars.p2Desc',
    color: '#6B8E23',
    icon: 'solar:leaf-bold-duotone',
    image: SPA9_IMAGES.olive,
  },
  {
    greek: 'Ηλιοθεραπεία',
    titleKey: 'pillars.p3Title',
    descKey: 'pillars.p3Desc',
    color: '#F5A623',
    icon: 'solar:sun-bold-duotone',
    image: SPA9_IMAGES.sun,
  },
  {
    greek: 'Λιθοθεραπεία',
    titleKey: 'pillars.p4Title',
    descKey: 'pillars.p4Desc',
    color: '#8B7355',
    icon: 'solar:mountains-bold-duotone',
    image: SPA9_IMAGES.stone,
  },
] as const;

export const SPA9_TREATMENTS = [
  {
    name: {
      vi: 'Roman Bath Ritual',
      en: 'Roman Bath Ritual',
      fr: 'Roman Bath Ritual',
      cn: 'Roman Bath Ritual',
      ar: 'Roman Bath Ritual',
    },
    origin: {
      vi: 'Truyền thống La Mã cổ đại',
      en: 'Ancient Roman tradition',
      fr: 'Tradition romaine antique',
      cn: '古罗马传统',
      ar: 'تقليد روماني قديم',
    },
    description: {
      vi: 'Tái hiện nghi lễ tắm công cộng La Mã 3 bước cổ điển: Tepidarium (ấm, giãn cơ), Caldarium (nóng, mở lỗ chân lông), Frigidarium (lạnh, đóng và săn chắc). Kết thúc với dầu olive và xoa bóp theo phong cách gladiator.',
      en: 'Recreates the classic 3-stage Roman public bathing ritual: Tepidarium (warm, muscle relaxation), Caldarium (hot, pore-opening), Frigidarium (cold, toning and firming). Concludes with olive oil and gladiator-style massage.',
      fr: 'Recrée le rituel classique du bain public romain en 3 étapes : Tepidarium (chaud, relaxation musculaire), Caldarium (très chaud, ouverture des pores), Frigidarium (froid, tonification et raffermissement). Se termine par de l’huile d’olive et un massage façon gladiateur.',
      cn: '重现经典的三段式古罗马公共浴礼：温浴室（温暖、放松肌肉）、热浴室（高温、舒张毛孔）、冷浴室（冷却、紧致塑形）。最后以橄榄油和角斗士式按摩收尾。',
      ar: 'يعيد إحياء طقوس الاستحمام الروماني العام الكلاسيكية بثلاث مراحل: تيبيداريوم (دافئ لإرخاء العضلات)، كالداريوم (حار لفتح المسام)، فريجيداريوم (بارد للشد والتنعيم). يُختتم بزيت الزيتون وتدليك على طريقة المجالدين.',
    },
    duration: { vi: '90 phút', en: '90 min', fr: '90 min', cn: '90 分钟', ar: '90 دقيقة' },
    price: {
      vi: 'từ 1.100.000₫',
      en: 'from 1,100,000₫',
      fr: 'à partir de 1 100 000₫',
      cn: '1,100,000₫ 起',
      ar: 'من 1,100,000₫',
    },
    color: '#F5A623',
    bg: '#FFFBF0',
    icon: 'solar:bath-bold-duotone',
  },
  {
    name: {
      vi: 'Greek Olive Oil Massage',
      en: 'Greek Olive Oil Massage',
      fr: 'Greek Olive Oil Massage',
      cn: 'Greek Olive Oil Massage',
      ar: 'Greek Olive Oil Massage',
    },
    origin: {
      vi: 'Truyền thống Hy Lạp cổ đại',
      en: 'Ancient Greek tradition',
      fr: 'Tradition grecque antique',
      cn: '古希腊传统',
      ar: 'تقليد يوناني قديم',
    },
    description: {
      vi: 'Massage toàn thân với 100% dầu olive Kalamata extra-virgin pha thêm tinh dầu hương thảo và hoa oải hương Provence. Kỹ thuật effleurage và petrissage Hy Lạp làm mềm da, thư giãn cơ và cải thiện tuần hoàn.',
      en: 'Full-body massage with 100% Kalamata extra-virgin olive oil blended with rosemary and Provence lavender essential oils. Greek effleurage and petrissage technique softens skin, relaxes muscles and improves circulation.',
      fr: 'Massage du corps entier à 100 % d’huile d’olive vierge extra de Kalamata enrichie d’huiles essentielles de romarin et de lavande de Provence. Les techniques grecques d’effleurage et de pétrissage adoucissent la peau, détendent les muscles et améliorent la circulation.',
      cn: '采用 100% 卡拉马塔特级初榨橄榄油，调和迷迭香与普罗旺斯薰衣草精油进行全身按摩。希腊式抚摸与揉捏手法软化肌肤、放松肌肉并促进血液循环。',
      ar: 'تدليك كامل للجسم بزيت زيتون كالاماتا البكر الممتاز بنسبة 100% الممزوج بزيوت إكليل الجبل وخزامى بروفانس العطرية. تقنيتا التمسيد والعجن اليونانيتان تنعّمان البشرة وترخيان العضلات وتحسّنان الدورة الدموية.',
    },
    duration: { vi: '75 phút', en: '75 min', fr: '75 min', cn: '75 分钟', ar: '75 دقيقة' },
    price: {
      vi: 'từ 890.000₫',
      en: 'from 890,000₫',
      fr: 'à partir de 890 000₫',
      cn: '890,000₫ 起',
      ar: 'من 890,000₫',
    },
    color: '#6B8E23',
    bg: '#F8FBEE',
    icon: 'solar:leaf-bold-duotone',
  },
  {
    name: {
      vi: 'Mediterranean Sea Salt Scrub',
      en: 'Mediterranean Sea Salt Scrub',
      fr: 'Mediterranean Sea Salt Scrub',
      cn: 'Mediterranean Sea Salt Scrub',
      ar: 'Mediterranean Sea Salt Scrub',
    },
    origin: {
      vi: 'Fleur de Sel từ Camargue, Pháp',
      en: 'Fleur de Sel from Camargue, France',
      fr: 'Fleur de sel de Camargue, France',
      cn: '法国卡马格盐之花',
      ar: 'زهرة الملح من كامارغ، فرنسا',
    },
    description: {
      vi: 'Tẩy tế bào chết toàn thân bằng muối Fleur de Sel thô Camargue pha trộn với dầu ô liu, mật ong Hy Lạp và chiết xuất quả lựu đỏ. Thải độc qua da, làm mềm và sáng đều màu da toàn thân.',
      en: 'Full-body exfoliation with coarse Camargue Fleur de Sel blended with olive oil, Greek honey and pomegranate extract. Skin detoxification, softening and even-toning the entire body.',
      fr: 'Exfoliation du corps entier à la fleur de sel brute de Camargue mélangée à de l’huile d’olive, du miel grec et de l’extrait de grenade. Détoxification de la peau, adoucissement et unification du teint sur tout le corps.',
      cn: '使用粗粒卡马格盐之花混合橄榄油、希腊蜂蜜与红石榴提取物进行全身去角质。促进肌肤排毒、软化并均匀全身肤色。',
      ar: 'تقشير كامل للجسم بزهرة ملح كامارغ الخشنة الممزوجة بزيت الزيتون والعسل اليوناني ومستخلص الرمان. يزيل سموم البشرة وينعّمها ويوحّد لون الجسم بالكامل.',
    },
    duration: { vi: '60 phút', en: '60 min', fr: '60 min', cn: '60 分钟', ar: '60 دقيقة' },
    price: {
      vi: 'từ 780.000₫',
      en: 'from 780,000₫',
      fr: 'à partir de 780 000₫',
      cn: '780,000₫ 起',
      ar: 'من 780,000₫',
    },
    color: '#1B6CA8',
    bg: '#EFF7FF',
    icon: 'solar:stars-bold-duotone',
  },
  {
    name: {
      vi: 'Volcanic Stone Thalasso',
      en: 'Volcanic Stone Thalasso',
      fr: 'Volcanic Stone Thalasso',
      cn: 'Volcanic Stone Thalasso',
      ar: 'Volcanic Stone Thalasso',
    },
    origin: {
      vi: 'Đá núi lửa Santorini',
      en: 'Santorini volcanic rock',
      fr: 'Roche volcanique de Santorin',
      cn: '圣托里尼火山岩',
      ar: 'صخور سانتوريني البركانية',
    },
    description: {
      vi: 'Đắp toàn thân bùn tảo biển Địa Trung Hải ấm 40°C kết hợp với đá núi lửa Santorini đặt trên các huyệt chính. Khoáng biển Aegean ngấm sâu vào da trong 30 phút, sau đó rửa trôi bằng nước biển ấm và dưỡng ẩm dầu olive.',
      en: 'Warm Mediterranean seaweed mud wrap at 40°C combined with Santorini volcanic stones placed on key meridians. Aegean sea minerals penetrate the skin for 30 minutes, rinsed off with warm seawater and finished with olive oil moisturisation.',
      fr: 'Enveloppement du corps entier à la boue d’algues méditerranéennes chaude à 40 °C, associé à des pierres volcaniques de Santorin posées sur les principaux méridiens. Les minéraux de la mer Égée pénètrent la peau pendant 30 minutes, puis sont rincés à l’eau de mer tiède et finis par une hydratation à l’huile d’olive.',
      cn: '以 40°C 温热的地中海海藻泥进行全身包裹，并将圣托里尼火山石置于主要经络之上。爱琴海矿物质渗入肌肤 30 分钟，随后用温海水冲洗，并以橄榄油滋润收尾。',
      ar: 'لفّ كامل للجسم بطين أعشاب البحر المتوسطي الدافئ عند 40°م مع أحجار سانتوريني البركانية الموضوعة على المسارات الرئيسية. تتغلغل معادن بحر إيجه في البشرة لمدة 30 دقيقة، ثم تُشطف بماء البحر الدافئ وتُختتم بترطيب بزيت الزيتون.',
    },
    duration: { vi: '80 phút', en: '80 min', fr: '80 min', cn: '80 分钟', ar: '80 دقيقة' },
    price: {
      vi: 'từ 1.050.000₫',
      en: 'from 1,050,000₫',
      fr: 'à partir de 1 050 000₫',
      cn: '1,050,000₫ 起',
      ar: 'من 1,050,000₫',
    },
    color: '#8B7355',
    bg: '#FAF6F0',
    icon: 'solar:mountains-bold-duotone',
  },
];

export const SPA9_DAY_PACKAGES = [
  {
    name: {
      vi: 'Aurora Mattina',
      en: 'Aurora Mattina',
      fr: 'Aurora Mattina',
      cn: 'Aurora Mattina',
      ar: 'Aurora Mattina',
    },
    subtitle: {
      vi: 'Gói buổi sáng',
      en: 'Morning package',
      fr: 'Forfait matin',
      cn: '上午套餐',
      ar: 'باقة الصباح',
    },
    time: {
      vi: '8:00 — 12:00',
      en: '8:00 — 12:00',
      fr: '8:00 — 12:00',
      cn: '8:00 — 12:00',
      ar: '8:00 — 12:00',
    },
    price: {
      vi: '2.200.000₫',
      en: '2,200,000₫',
      fr: '2 200 000₫',
      cn: '2,200,000₫',
      ar: '2,200,000₫',
    },
    color: '#F5A623',
    textColor: '#7A3800',
    emoji: '🌅',
    includes: {
      vi: [
        'Breakfast Mediterraneo',
        'Roman Bath Circuit (60 phút)',
        'Relaxation Pool access (2 giờ)',
        'Khăn tắm & Dép spa',
      ],
      en: [
        'Mediterraneo Breakfast',
        'Roman Bath Circuit (60 min)',
        'Relaxation Pool access (2 hours)',
        'Bath towel & Spa slippers',
      ],
      fr: [
        'Petit-déjeuner Mediterraneo',
        'Circuit du bain romain (60 min)',
        'Accès à la piscine de relaxation (2 heures)',
        'Serviette de bain & chaussons de spa',
      ],
      cn: ['地中海早餐', '罗马浴循环（60 分钟）', '放松泳池使用（2 小时）', '浴巾与水疗拖鞋'],
      ar: [
        'فطور متوسطي',
        'دورة الحمام الروماني (60 دقيقة)',
        'دخول حوض الاسترخاء (ساعتان)',
        'منشفة استحمام ونعال سبا',
      ],
    },
  },
  {
    name: {
      vi: 'Sole del Mezzogiorno',
      en: 'Sole del Mezzogiorno',
      fr: 'Sole del Mezzogiorno',
      cn: 'Sole del Mezzogiorno',
      ar: 'Sole del Mezzogiorno',
    },
    subtitle: {
      vi: 'Gói trọn ngày',
      en: 'Full day package',
      fr: 'Forfait journée complète',
      cn: '全天套餐',
      ar: 'باقة يوم كامل',
    },
    time: {
      vi: '10:00 — 18:00',
      en: '10:00 — 18:00',
      fr: '10:00 — 18:00',
      cn: '10:00 — 18:00',
      ar: '10:00 — 18:00',
    },
    price: {
      vi: '4.500.000₫',
      en: '4,500,000₫',
      fr: '4 500 000₫',
      cn: '4,500,000₫',
      ar: '4,500,000₫',
    },
    color: '#1B6CA8',
    textColor: '#0A2E4A',
    emoji: '☀️',
    includes: {
      vi: [
        'Bữa trưa Địa Trung Hải 3 món',
        'Bất kỳ 2 liệu trình (tự chọn)',
        'Pool & Steam Room suốt ngày',
        'Greek Olive Oil Snack set',
        'Locker riêng',
      ],
      en: [
        '3-course Mediterranean lunch',
        'Any 2 treatments (your choice)',
        'Pool & Steam Room all day',
        'Greek Olive Oil Snack set',
        'Private locker',
      ],
      fr: [
        'Déjeuner méditerranéen 3 services',
        '2 soins au choix',
        'Piscine & hammam toute la journée',
        'Coffret de collation à l’huile d’olive grecque',
        'Casier privé',
      ],
      cn: [
        '地中海三道式午餐',
        '任选 2 项疗程',
        '全天使用泳池与蒸气房',
        '希腊橄榄油小食套盒',
        '专用储物柜',
      ],
      ar: [
        'غداء متوسطي من ثلاثة أطباق',
        'أي 2 من العلاجات (حسب اختيارك)',
        'المسبح وغرفة البخار طوال اليوم',
        'طقم وجبات خفيفة بزيت الزيتون اليوناني',
        'خزانة خاصة',
      ],
    },
  },
  {
    name: {
      vi: 'Tramonto Serale',
      en: 'Tramonto Serale',
      fr: 'Tramonto Serale',
      cn: 'Tramonto Serale',
      ar: 'Tramonto Serale',
    },
    subtitle: {
      vi: 'Gói hoàng hôn',
      en: 'Sunset package',
      fr: 'Forfait coucher de soleil',
      cn: '日落套餐',
      ar: 'باقة الغروب',
    },
    time: {
      vi: '16:00 — 21:00',
      en: '16:00 — 21:00',
      fr: '16:00 — 21:00',
      cn: '16:00 — 21:00',
      ar: '16:00 — 21:00',
    },
    price: {
      vi: '3.200.000₫',
      en: '3,200,000₫',
      fr: '3 200 000₫',
      cn: '3,200,000₫',
      ar: '3,200,000₫',
    },
    color: '#8B4513',
    textColor: '#3A1200',
    emoji: '🌇',
    includes: {
      vi: [
        'Cocktail Aperitivo chào đón',
        'Sea Salt Scrub (60 phút)',
        'Bể ngâm hoàng hôn view Sunset',
        'Bữa tối nhẹ Antipasto',
        'Candle Massage (45 phút)',
      ],
      en: [
        'Welcome Aperitivo cocktail',
        'Sea Salt Scrub (60 min)',
        'Sunset-view soaking pool',
        'Light Antipasto dinner',
        'Candle Massage (45 min)',
      ],
      fr: [
        'Cocktail Aperitivo de bienvenue',
        'Gommage au sel marin (60 min)',
        'Bassin d’immersion vue coucher de soleil',
        'Dîner léger Antipasto',
        'Massage à la bougie (45 min)',
      ],
      cn: [
        '迎宾开胃鸡尾酒',
        '海盐磨砚（60 分钟）',
        '日落景观浸泡泳池',
        '轻食开胃菜晚餐',
        '烛光按摩（45 分钟）',
      ],
      ar: [
        'كوكتيل أبريتيفو ترحيبي',
        'تقشير بملح البحر (60 دقيقة)',
        'حوض نقع بإطلالة على الغروب',
        'عشاء خفيف من المقبلات',
        'تدليك بالشموع (45 دقيقة)',
      ],
    },
  },
];

export const SPA9_DAY_PASS_OPTIONS = {
  vi: [
    'Aurora Mattina — Gói buổi sáng',
    'Sole del Mezzogiorno — Gói trọn ngày',
    'Tramonto Serale — Gói hoàng hôn',
  ],
  en: [
    'Aurora Mattina — Morning package',
    'Sole del Mezzogiorno — Full day package',
    'Tramonto Serale — Sunset package',
  ],
  fr: [
    'Aurora Mattina — Forfait matin',
    'Sole del Mezzogiorno — Forfait journée complète',
    'Tramonto Serale — Forfait coucher de soleil',
  ],
  cn: [
    'Aurora Mattina — 上午套餐',
    'Sole del Mezzogiorno — 全天套餐',
    'Tramonto Serale — 日落套餐',
  ],
  ar: [
    'Aurora Mattina — باقة الصباح',
    'Sole del Mezzogiorno — باقة يوم كامل',
    'Tramonto Serale — باقة الغروب',
  ],
};
