import type { Spa2ManageConfig } from './spa2-generic-manage-view';

// ─────────────────────────────────────────────────────────────────────────────
// Reusable status presets
const S_PUB = [
  { value: 'Bản nháp', color: 'default' as const },
  { value: 'Đang hiển thị', color: 'success' as const },
  { value: 'Ẩn', color: 'warning' as const },
];
const S_APV = [
  { value: 'Chờ duyệt', color: 'warning' as const },
  { value: 'Đã duyệt', color: 'success' as const },
  { value: 'Từ chối', color: 'error' as const },
];
const S_ORDER = [
  { value: 'Mới', color: 'info' as const },
  { value: 'Đang xử lý', color: 'warning' as const },
  { value: 'Hoàn tất', color: 'success' as const },
  { value: 'Đã huỷ', color: 'error' as const },
];

const img = (seed: string) =>
  `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=400&q=60`;

// ─────────────────────────────────────────────────────────────────────────────

export const SPA2_MANAGE_CONFIGS: Record<string, Spa2ManageConfig> = {
  policy: {
    title: 'Quản lý Chính sách',
    breadcrumbLabel: 'Chính sách',
    addLabel: 'Thêm chính sách',
    publicPath: '/spa2/policy',
    fields: [
      { key: 'title', label: 'Tiêu đề', type: 'text', required: true },
      { key: 'category', label: 'Loại', type: 'select', options: ['Bảo mật', 'Điều khoản', 'Hoàn tiền', 'Đặt lịch'] },
      { key: 'content', label: 'Nội dung', type: 'textarea', showInTable: false },
      { key: 'updatedAt', label: 'Cập nhật', type: 'date' },
    ],
    statuses: S_PUB,
    seed: [
      { title: 'Chính sách bảo mật', category: 'Bảo mật', content: 'Chúng tôi bảo mật thông tin khách hàng...', updatedAt: '2025-01-15', status: 'Đang hiển thị' },
      { title: 'Điều khoản dịch vụ', category: 'Điều khoản', content: 'Quy định sử dụng dịch vụ spa...', updatedAt: '2025-02-01', status: 'Đang hiển thị' },
      { title: 'Chính sách hoàn tiền', category: 'Hoàn tiền', content: 'Hoàn tiền trong vòng 7 ngày...', updatedAt: '2025-02-10', status: 'Bản nháp' },
    ],
  },
  gallery: {
    title: 'Quản lý Thư viện ảnh',
    breadcrumbLabel: 'Thư viện',
    addLabel: 'Thêm ảnh',
    publicPath: '/spa2/gallery',
    fields: [
      { key: 'image', label: 'Ảnh', type: 'image' },
      { key: 'caption', label: 'Chú thích', type: 'text' },
      { key: 'album', label: 'Album', type: 'select', options: ['Không gian', 'Liệu trình', 'Sự kiện', 'Sản phẩm'] },
      { key: 'photographer', label: 'Nhiếp ảnh', type: 'text', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      { image: img('photo-1600334129128-685c5582fd35'), caption: 'Không gian thư giãn', album: 'Không gian', photographer: 'Studio A', status: 'Đang hiển thị' },
      { image: img('photo-1540555700478-4be289fbecef'), caption: 'Massage đá nóng', album: 'Liệu trình', photographer: 'Studio B', status: 'Đang hiển thị' },
      { image: img('photo-1596178065887-1198b6148b2b'), caption: 'Sản phẩm thiên nhiên', album: 'Sản phẩm', photographer: 'Studio A', status: 'Bản nháp' },
    ],
  },
  membership: {
    title: 'Quản lý Gói thành viên',
    breadcrumbLabel: 'Thành viên',
    addLabel: 'Thêm gói',
    publicPath: '/spa2/membership',
    fields: [
      { key: 'name', label: 'Tên gói', type: 'text' },
      { key: 'tier', label: 'Hạng', type: 'select', options: ['Silver', 'Gold', 'Platinum', 'Diamond'] },
      { key: 'price', label: 'Giá (VND)', type: 'number' },
      { key: 'duration', label: 'Thời hạn', type: 'text' },
      { key: 'benefits', label: 'Quyền lợi', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      { name: 'Silver 3 tháng', tier: 'Silver', price: 3000000, duration: '3 tháng', benefits: 'Giảm 10% các liệu trình', status: 'Đang hiển thị' },
      { name: 'Gold 6 tháng', tier: 'Gold', price: 6500000, duration: '6 tháng', benefits: 'Giảm 15%, tặng 2 buổi massage', status: 'Đang hiển thị' },
      { name: 'Platinum 12 tháng', tier: 'Platinum', price: 12000000, duration: '12 tháng', benefits: 'Giảm 20%, VIP room, quà sinh nhật', status: 'Đang hiển thị' },
    ],
  },
  'gift-card': {
    title: 'Quản lý Thẻ quà tặng',
    breadcrumbLabel: 'Thẻ quà tặng',
    addLabel: 'Thêm thẻ',
    publicPath: '/spa2/gift-card',
    fields: [
      { key: 'code', label: 'Mã thẻ', type: 'text' },
      { key: 'value', label: 'Mệnh giá (VND)', type: 'number' },
      { key: 'recipient', label: 'Người nhận', type: 'text' },
      { key: 'expiry', label: 'Hết hạn', type: 'date' },
      { key: 'note', label: 'Ghi chú', type: 'textarea', showInTable: false },
    ],
    statuses: [
      { value: 'Còn hiệu lực', color: 'success' as const },
      { value: 'Đã dùng', color: 'default' as const },
      { value: 'Hết hạn', color: 'error' as const },
    ],
    seed: [
      { code: 'GIFT-001', value: 500000, recipient: 'Nguyễn A', expiry: '2025-12-31', note: 'Sinh nhật', status: 'Còn hiệu lực' },
      { code: 'GIFT-002', value: 1000000, recipient: 'Trần B', expiry: '2025-10-15', note: 'Kỷ niệm', status: 'Còn hiệu lực' },
      { code: 'GIFT-003', value: 300000, recipient: 'Lê C', expiry: '2024-12-01', note: '', status: 'Hết hạn' },
    ],
  },
  'wellness-package': {
    title: 'Quản lý Gói chăm sóc',
    breadcrumbLabel: 'Wellness Package',
    addLabel: 'Thêm gói',
    publicPath: '/spa2/wellness-package',
    fields: [
      { key: 'name', label: 'Tên gói', type: 'text' },
      { key: 'duration', label: 'Thời lượng', type: 'text' },
      { key: 'sessions', label: 'Số buổi', type: 'number' },
      { key: 'price', label: 'Giá (VND)', type: 'number' },
      { key: 'description', label: 'Mô tả', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      { name: 'Detox 5 buổi', duration: '90 phút', sessions: 5, price: 5500000, description: 'Thanh lọc cơ thể', status: 'Đang hiển thị' },
      { name: 'Yoga & Spa', duration: '120 phút', sessions: 10, price: 9800000, description: 'Kết hợp yoga và spa', status: 'Đang hiển thị' },
      { name: 'Signature Wellness', duration: '150 phút', sessions: 8, price: 12000000, description: 'Trải nghiệm cao cấp', status: 'Bản nháp' },
    ],
  },
  'skin-quiz': {
    title: 'Quản lý Câu hỏi Skin Quiz',
    breadcrumbLabel: 'Skin Quiz',
    addLabel: 'Thêm câu hỏi',
    publicPath: '/spa2/skin-quiz',
    fields: [
      { key: 'question', label: 'Câu hỏi', type: 'text' },
      { key: 'category', label: 'Nhóm', type: 'select', options: ['Loại da', 'Vấn đề', 'Thói quen', 'Mục tiêu'] },
      { key: 'options', label: 'Lựa chọn (phân cách ,)', type: 'textarea', showInTable: false },
      { key: 'order', label: 'Thứ tự', type: 'number' },
    ],
    statuses: S_PUB,
    seed: [
      { question: 'Loại da của bạn?', category: 'Loại da', options: 'Khô, Dầu, Hỗn hợp, Nhạy cảm', order: 1, status: 'Đang hiển thị' },
      { question: 'Vấn đề bạn quan tâm?', category: 'Vấn đề', options: 'Mụn, Nám, Lão hoá, Xỉn màu', order: 2, status: 'Đang hiển thị' },
      { question: 'Tần suất chăm sóc da?', category: 'Thói quen', options: 'Hàng ngày, Vài lần/tuần, Hiếm khi', order: 3, status: 'Đang hiển thị' },
    ],
  },
  corporate: {
    title: 'Quản lý Đối tác doanh nghiệp',
    breadcrumbLabel: 'Corporate',
    addLabel: 'Thêm đối tác',
    publicPath: '/spa2/corporate',
    fields: [
      { key: 'company', label: 'Công ty', type: 'text' },
      { key: 'contact', label: 'Người liên hệ', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'employees', label: 'Số nhân viên', type: 'number' },
      { key: 'notes', label: 'Ghi chú', type: 'textarea', showInTable: false },
    ],
    statuses: S_APV,
    approvable: true,
    seed: [
      { company: 'FPT Corp', contact: 'Nguyễn A', email: 'a@fpt.com', employees: 500, notes: 'Chương trình phúc lợi', status: 'Đã duyệt' },
      { company: 'VNG', contact: 'Trần B', email: 'b@vng.com', employees: 200, notes: 'Team building', status: 'Chờ duyệt' },
      { company: 'Momo', contact: 'Lê C', email: 'c@momo.vn', employees: 150, notes: '', status: 'Chờ duyệt' },
    ],
  },
  shop: {
    title: 'Quản lý Sản phẩm',
    breadcrumbLabel: 'Shop',
    addLabel: 'Thêm sản phẩm',
    publicPath: '/spa2/shop',
    fields: [
      { key: 'image', label: 'Ảnh', type: 'image' },
      { key: 'name', label: 'Tên sản phẩm', type: 'text' },
      { key: 'category', label: 'Danh mục', type: 'select', options: ['Skincare', 'Body', 'Aromatherapy', 'Tools'] },
      { key: 'price', label: 'Giá (VND)', type: 'number' },
      { key: 'stock', label: 'Tồn kho', type: 'number' },
      { key: 'description', label: 'Mô tả', type: 'textarea', showInTable: false },
    ],
    statuses: [
      { value: 'Đang bán', color: 'success' as const },
      { value: 'Hết hàng', color: 'error' as const },
      { value: 'Ngưng', color: 'default' as const },
    ],
    seed: [
      { image: img('photo-1556228720-195a672e8a03'), name: 'Serum Vitamin C', category: 'Skincare', price: 850000, stock: 24, description: 'Làm sáng da', status: 'Đang bán' },
      { image: img('photo-1570194065650-d99fb4bedf0a'), name: 'Tinh dầu Lavender', category: 'Aromatherapy', price: 320000, stock: 40, description: 'Thư giãn', status: 'Đang bán' },
      { image: img('photo-1608248543803-ba4f8c70ae0b'), name: 'Body Scrub Muối biển', category: 'Body', price: 450000, stock: 0, description: 'Tẩy tế bào chết', status: 'Hết hàng' },
    ],
  },
  sustainability: {
    title: 'Quản lý Sáng kiến bền vững',
    breadcrumbLabel: 'Sustainability',
    addLabel: 'Thêm sáng kiến',
    publicPath: '/spa2/sustainability',
    fields: [
      { key: 'title', label: 'Sáng kiến', type: 'text' },
      { key: 'pillar', label: 'Trụ cột', type: 'select', options: ['Môi trường', 'Xã hội', 'Quản trị'] },
      { key: 'impact', label: 'Tác động', type: 'text' },
      { key: 'year', label: 'Năm', type: 'number' },
      { key: 'details', label: 'Chi tiết', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      { title: 'Bao bì tái chế', pillar: 'Môi trường', impact: 'Giảm 40% nhựa', year: 2024, details: 'Chuyển đổi 100% bao bì', status: 'Đang hiển thị' },
      { title: 'Nữ giới lãnh đạo', pillar: 'Xã hội', impact: '60% nhân sự nữ', year: 2024, details: 'Chương trình mentoring', status: 'Đang hiển thị' },
      { title: 'Minh bạch nguồn cung', pillar: 'Quản trị', impact: '100% supplier ISO', year: 2025, details: '', status: 'Bản nháp' },
    ],
  },
  events: {
    title: 'Quản lý Sự kiện',
    breadcrumbLabel: 'Sự kiện',
    addLabel: 'Thêm sự kiện',
    publicPath: '/spa2/events',
    fields: [
      { key: 'name', label: 'Tên sự kiện', type: 'text' },
      { key: 'date', label: 'Ngày', type: 'date' },
      { key: 'location', label: 'Địa điểm', type: 'text' },
      { key: 'capacity', label: 'Sức chứa', type: 'number' },
      { key: 'description', label: 'Mô tả', type: 'textarea', showInTable: false },
    ],
    statuses: [
      { value: 'Sắp diễn ra', color: 'info' as const },
      { value: 'Đang diễn ra', color: 'success' as const },
      { value: 'Đã kết thúc', color: 'default' as const },
      { value: 'Đã huỷ', color: 'error' as const },
    ],
    seed: [
      { name: 'Workshop skincare', date: '2025-03-15', location: 'CN Quận 1', capacity: 30, description: 'Chăm sóc da mùa xuân', status: 'Sắp diễn ra' },
      { name: 'Yoga & Wine Night', date: '2025-04-20', location: 'CN Thảo Điền', capacity: 40, description: '', status: 'Sắp diễn ra' },
      { name: 'Grand Opening', date: '2024-12-01', location: 'CN Hà Nội', capacity: 100, description: 'Khai trương chi nhánh', status: 'Đã kết thúc' },
    ],
  },
  referral: {
    title: 'Quản lý Giới thiệu',
    breadcrumbLabel: 'Referral',
    addLabel: 'Thêm mã',
    publicPath: '/spa2/referral',
    fields: [
      { key: 'code', label: 'Mã', type: 'text' },
      { key: 'owner', label: 'Người sở hữu', type: 'text' },
      { key: 'reward', label: 'Ưu đãi', type: 'text' },
      { key: 'usedCount', label: 'Đã dùng', type: 'number' },
    ],
    statuses: [
      { value: 'Hoạt động', color: 'success' as const },
      { value: 'Tạm dừng', color: 'warning' as const },
    ],
    seed: [
      { code: 'REF-ANNA', owner: 'Anna Nguyen', reward: 'Giảm 15%', usedCount: 12, status: 'Hoạt động' },
      { code: 'REF-MINH', owner: 'Minh Tran', reward: 'Tặng buổi facial', usedCount: 5, status: 'Hoạt động' },
      { code: 'REF-JULY', owner: 'July Le', reward: 'Giảm 20%', usedCount: 0, status: 'Tạm dừng' },
    ],
  },
  'app-download': {
    title: 'Quản lý Trang App Download',
    breadcrumbLabel: 'App Download',
    addLabel: 'Thêm nội dung',
    publicPath: '/spa2/app-download',
    fields: [
      { key: 'platform', label: 'Nền tảng', type: 'select', options: ['iOS', 'Android', 'Web'] },
      { key: 'version', label: 'Phiên bản', type: 'text' },
      { key: 'link', label: 'Đường dẫn', type: 'text' },
      { key: 'notes', label: 'Ghi chú release', type: 'textarea', showInTable: false },
    ],
    statuses: [
      { value: 'Đang phát hành', color: 'success' as const },
      { value: 'Beta', color: 'warning' as const },
      { value: 'Đã gỡ', color: 'default' as const },
    ],
    seed: [
      { platform: 'iOS', version: '2.4.0', link: 'https://apps.apple.com/...', notes: 'Bug fixes', status: 'Đang phát hành' },
      { platform: 'Android', version: '2.4.0', link: 'https://play.google.com/...', notes: 'Bug fixes', status: 'Đang phát hành' },
      { platform: 'iOS', version: '2.5.0-beta', link: 'https://testflight.apple.com/...', notes: 'Tính năng đặt lịch mới', status: 'Beta' },
    ],
  },
  'special-occasions': {
    title: 'Quản lý Dịp đặc biệt',
    breadcrumbLabel: 'Special Occasions',
    addLabel: 'Thêm dịp',
    publicPath: '/spa2/special-occasions',
    fields: [
      { key: 'occasion', label: 'Dịp', type: 'text' },
      { key: 'package', label: 'Gói kèm theo', type: 'text' },
      { key: 'discount', label: 'Ưu đãi (%)', type: 'number' },
      { key: 'validUntil', label: 'Đến ngày', type: 'date' },
    ],
    statuses: S_PUB,
    seed: [
      { occasion: 'Valentine', package: 'Couple Spa', discount: 20, validUntil: '2025-02-20', status: 'Đang hiển thị' },
      { occasion: 'Sinh nhật', package: 'Birthday Bliss', discount: 15, validUntil: '2025-12-31', status: 'Đang hiển thị' },
      { occasion: 'Kỷ niệm cưới', package: 'Anniversary', discount: 25, validUntil: '2025-12-31', status: 'Bản nháp' },
    ],
  },
  'home-service': {
    title: 'Quản lý Dịch vụ tại nhà',
    breadcrumbLabel: 'Home Service',
    addLabel: 'Thêm dịch vụ',
    publicPath: '/spa2/home-service',
    fields: [
      { key: 'service', label: 'Dịch vụ', type: 'text' },
      { key: 'duration', label: 'Thời lượng', type: 'text' },
      { key: 'area', label: 'Khu vực', type: 'text' },
      { key: 'price', label: 'Giá (VND)', type: 'number' },
    ],
    statuses: S_PUB,
    seed: [
      { service: 'Massage tại nhà', duration: '90 phút', area: 'Q1, Q3, Q7', price: 1200000, status: 'Đang hiển thị' },
      { service: 'Facial tại nhà', duration: '60 phút', area: 'Q1, Q2', price: 950000, status: 'Đang hiển thị' },
      { service: 'Body scrub tại nhà', duration: '75 phút', area: 'Q7', price: 1400000, status: 'Bản nháp' },
    ],
  },
  'skin-diary': {
    title: 'Quản lý Nhật ký làn da',
    breadcrumbLabel: 'Skin Diary',
    addLabel: 'Thêm bài viết',
    publicPath: '/spa2/skin-diary',
    fields: [
      { key: 'title', label: 'Tiêu đề', type: 'text' },
      { key: 'author', label: 'Tác giả', type: 'text' },
      { key: 'topic', label: 'Chủ đề', type: 'select', options: ['Mụn', 'Nám', 'Lão hoá', 'Dưỡng ẩm'] },
      { key: 'summary', label: 'Tóm tắt', type: 'textarea', showInTable: false },
      { key: 'publishedAt', label: 'Ngày đăng', type: 'date' },
    ],
    statuses: S_PUB,
    seed: [
      { title: 'Hành trình trị mụn 30 ngày', author: 'Dr. Han', topic: 'Mụn', summary: 'Case study khách hàng...', publishedAt: '2025-01-10', status: 'Đang hiển thị' },
      { title: 'Chống nắng đúng cách', author: 'Dr. Linh', topic: 'Lão hoá', summary: '', publishedAt: '2025-01-20', status: 'Đang hiển thị' },
      { title: 'Dưỡng ẩm mùa lạnh', author: 'Dr. Han', topic: 'Dưỡng ẩm', summary: '', publishedAt: '2025-02-01', status: 'Bản nháp' },
    ],
  },
  mindfulness: {
    title: 'Quản lý Chương trình Mindfulness',
    breadcrumbLabel: 'Mindfulness',
    addLabel: 'Thêm chương trình',
    publicPath: '/spa2/mindfulness',
    fields: [
      { key: 'name', label: 'Tên', type: 'text' },
      { key: 'type', label: 'Loại', type: 'select', options: ['Thiền', 'Yoga', 'Breathwork', 'Sound bath'] },
      { key: 'duration', label: 'Thời lượng', type: 'text' },
      { key: 'instructor', label: 'Giảng viên', type: 'text' },
    ],
    statuses: S_PUB,
    seed: [
      { name: 'Morning Mindfulness', type: 'Thiền', duration: '30 phút', instructor: 'Master Bao', status: 'Đang hiển thị' },
      { name: 'Vinyasa Flow', type: 'Yoga', duration: '60 phút', instructor: 'Ms. Trang', status: 'Đang hiển thị' },
      { name: 'Sound Bath Deep', type: 'Sound bath', duration: '75 phút', instructor: 'Mr. Kai', status: 'Bản nháp' },
    ],
  },
  'medical-spa': {
    title: 'Quản lý Dịch vụ Medical Spa',
    breadcrumbLabel: 'Medical Spa',
    addLabel: 'Thêm dịch vụ',
    publicPath: '/spa2/medical-spa',
    fields: [
      { key: 'service', label: 'Dịch vụ', type: 'text' },
      { key: 'doctor', label: 'Bác sĩ', type: 'text' },
      { key: 'duration', label: 'Thời lượng', type: 'text' },
      { key: 'price', label: 'Giá (VND)', type: 'number' },
      { key: 'notes', label: 'Ghi chú y tế', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      { service: 'HIFU nâng cơ', doctor: 'BS. Minh', duration: '60 phút', price: 15000000, notes: 'Chỉ định > 30 tuổi', status: 'Đang hiển thị' },
      { service: 'Laser tái tạo da', doctor: 'BS. An', duration: '45 phút', price: 8000000, notes: '', status: 'Đang hiển thị' },
      { service: 'Botox', doctor: 'BS. Minh', duration: '30 phút', price: 6000000, notes: 'Tư vấn trước', status: 'Bản nháp' },
    ],
  },
  'spa-etiquette': {
    title: 'Quản lý Quy tắc ứng xử',
    breadcrumbLabel: 'Spa Etiquette',
    addLabel: 'Thêm quy tắc',
    publicPath: '/spa2/spa-etiquette',
    fields: [
      { key: 'rule', label: 'Quy tắc', type: 'text' },
      { key: 'category', label: 'Nhóm', type: 'select', options: ['Trước khi đến', 'Trong buổi trị liệu', 'Sau buổi trị liệu'] },
      { key: 'description', label: 'Mô tả', type: 'textarea', showInTable: false },
      { key: 'order', label: 'Thứ tự', type: 'number' },
    ],
    statuses: S_PUB,
    seed: [
      { rule: 'Đến sớm 15 phút', category: 'Trước khi đến', description: 'Để chuẩn bị và làm thủ tục', order: 1, status: 'Đang hiển thị' },
      { rule: 'Tắt chuông điện thoại', category: 'Trong buổi trị liệu', description: 'Giữ không gian yên tĩnh', order: 2, status: 'Đang hiển thị' },
      { rule: 'Uống nhiều nước', category: 'Sau buổi trị liệu', description: 'Hỗ trợ thải độc', order: 3, status: 'Đang hiển thị' },
    ],
  },
  'loyalty-rewards': {
    title: 'Quản lý Loyalty Rewards',
    breadcrumbLabel: 'Loyalty',
    addLabel: 'Thêm phần thưởng',
    publicPath: '/spa2/loyalty-rewards',
    fields: [
      { key: 'reward', label: 'Phần thưởng', type: 'text' },
      { key: 'points', label: 'Điểm cần', type: 'number' },
      { key: 'tier', label: 'Hạng tối thiểu', type: 'select', options: ['Silver', 'Gold', 'Platinum', 'Diamond'] },
      { key: 'description', label: 'Mô tả', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      { reward: 'Voucher 300k', points: 500, tier: 'Silver', description: 'Áp dụng mọi liệu trình', status: 'Đang hiển thị' },
      { reward: 'Free facial', points: 1200, tier: 'Gold', description: '60 phút', status: 'Đang hiển thị' },
      { reward: 'VIP suite 1 ngày', points: 5000, tier: 'Platinum', description: '', status: 'Bản nháp' },
    ],
  },
  review: {
    title: 'Quản lý Đánh giá',
    breadcrumbLabel: 'Review',
    addLabel: 'Thêm đánh giá',
    publicPath: '/spa2/review',
    fields: [
      { key: 'customer', label: 'Khách hàng', type: 'text' },
      { key: 'service', label: 'Dịch vụ', type: 'text' },
      { key: 'rating', label: 'Điểm', type: 'number' },
      { key: 'comment', label: 'Nhận xét', type: 'textarea', showInTable: false },
      { key: 'date', label: 'Ngày', type: 'date' },
    ],
    statuses: S_APV,
    approvable: true,
    seed: [
      { customer: 'Anna Nguyen', service: 'Facial vàng', rating: 5, comment: 'Rất tuyệt vời!', date: '2025-01-20', status: 'Đã duyệt' },
      { customer: 'Minh Tran', service: 'Massage đá nóng', rating: 4, comment: 'Ổn nhưng hơi ngắn', date: '2025-01-25', status: 'Chờ duyệt' },
      { customer: 'July Le', service: 'Body wrap', rating: 5, comment: 'Sẽ quay lại', date: '2025-02-01', status: 'Chờ duyệt' },
    ],
  },
  'seasonal-package': {
    title: 'Quản lý Gói theo mùa',
    breadcrumbLabel: 'Seasonal',
    addLabel: 'Thêm gói',
    publicPath: '/spa2/seasonal-package',
    fields: [
      { key: 'name', label: 'Tên gói', type: 'text' },
      { key: 'season', label: 'Mùa', type: 'select', options: ['Xuân', 'Hạ', 'Thu', 'Đông'] },
      { key: 'price', label: 'Giá (VND)', type: 'number' },
      { key: 'validUntil', label: 'Đến ngày', type: 'date' },
      { key: 'description', label: 'Mô tả', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      { name: 'Xuân tươi mới', season: 'Xuân', price: 2500000, validUntil: '2025-04-30', description: '', status: 'Đang hiển thị' },
      { name: 'Hạ mát lành', season: 'Hạ', price: 2800000, validUntil: '2025-08-30', description: '', status: 'Bản nháp' },
      { name: 'Thu ấm áp', season: 'Thu', price: 2600000, validUntil: '2025-11-30', description: '', status: 'Bản nháp' },
    ],
  },
  nutrition: {
    title: 'Quản lý Chương trình dinh dưỡng',
    breadcrumbLabel: 'Nutrition',
    addLabel: 'Thêm chương trình',
    publicPath: '/spa2/nutrition',
    fields: [
      { key: 'name', label: 'Tên', type: 'text' },
      { key: 'goal', label: 'Mục tiêu', type: 'select', options: ['Giảm cân', 'Detox', 'Tăng cơ', 'Cân bằng'] },
      { key: 'duration', label: 'Thời gian', type: 'text' },
      { key: 'nutritionist', label: 'Chuyên gia', type: 'text' },
      { key: 'menu', label: 'Thực đơn mẫu', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      { name: 'Detox 7 ngày', goal: 'Detox', duration: '7 ngày', nutritionist: 'Ms. Ngoc', menu: 'Nước ép, salad...', status: 'Đang hiển thị' },
      { name: 'Slim 30', goal: 'Giảm cân', duration: '30 ngày', nutritionist: 'Ms. Ngoc', menu: '', status: 'Đang hiển thị' },
      { name: 'Balance Plus', goal: 'Cân bằng', duration: '14 ngày', nutritionist: 'Ms. Ha', menu: '', status: 'Bản nháp' },
    ],
  },
  consultation: {
    title: 'Quản lý Tư vấn',
    breadcrumbLabel: 'Tư vấn',
    addLabel: 'Thêm lịch tư vấn',
    publicPath: '/spa2/consultation',
    fields: [
      { key: 'customer', label: 'Khách hàng', type: 'text' },
      { key: 'topic', label: 'Chủ đề', type: 'text' },
      { key: 'expert', label: 'Chuyên gia', type: 'text' },
      { key: 'date', label: 'Ngày', type: 'date' },
      { key: 'notes', label: 'Ghi chú', type: 'textarea', showInTable: false },
    ],
    statuses: S_ORDER,
    approvable: true,
    seed: [
      { customer: 'Anna N.', topic: 'Trị mụn', expert: 'BS. Han', date: '2025-02-20', notes: '', status: 'Mới' },
      { customer: 'Minh T.', topic: 'Chống lão hoá', expert: 'BS. Linh', date: '2025-02-22', notes: '', status: 'Đang xử lý' },
      { customer: 'July L.', topic: 'Chăm sóc tóc', expert: 'BS. An', date: '2025-02-18', notes: 'Đã hoàn tất', status: 'Hoàn tất' },
    ],
  },
  'vip-room': {
    title: 'Quản lý Phòng VIP',
    breadcrumbLabel: 'VIP Room',
    addLabel: 'Thêm phòng',
    publicPath: '/spa2/vip-room',
    fields: [
      { key: 'image', label: 'Ảnh', type: 'image' },
      { key: 'name', label: 'Tên phòng', type: 'text' },
      { key: 'capacity', label: 'Sức chứa', type: 'number' },
      { key: 'amenities', label: 'Tiện nghi', type: 'text' },
      { key: 'pricePerHour', label: 'Giá/giờ (VND)', type: 'number' },
    ],
    statuses: [
      { value: 'Sẵn sàng', color: 'success' as const },
      { value: 'Đang sử dụng', color: 'warning' as const },
      { value: 'Bảo trì', color: 'error' as const },
    ],
    seed: [
      { image: img('photo-1600585154340-be6161a56a0c'), name: 'Suite Lotus', capacity: 2, amenities: 'Jacuzzi, sauna', pricePerHour: 2500000, status: 'Sẵn sàng' },
      { image: img('photo-1571003123894-1f0594d2b5d9'), name: 'Suite Orchid', capacity: 4, amenities: 'Hồ nước nóng riêng', pricePerHour: 4000000, status: 'Đang sử dụng' },
      { image: img('photo-1578683010236-d716f9a3f461'), name: 'Suite Bamboo', capacity: 2, amenities: 'View vườn', pricePerHour: 2200000, status: 'Bảo trì' },
    ],
  },
  'package-builder': {
    title: 'Quản lý Package Builder',
    breadcrumbLabel: 'Package Builder',
    addLabel: 'Thêm mô-đun',
    publicPath: '/spa2/package-builder',
    fields: [
      { key: 'module', label: 'Mô-đun', type: 'text' },
      { key: 'category', label: 'Nhóm', type: 'select', options: ['Facial', 'Body', 'Massage', 'Wellness'] },
      { key: 'duration', label: 'Thời lượng', type: 'text' },
      { key: 'price', label: 'Giá (VND)', type: 'number' },
    ],
    statuses: S_PUB,
    seed: [
      { module: 'Facial Basic', category: 'Facial', duration: '45 phút', price: 750000, status: 'Đang hiển thị' },
      { module: 'Full body massage', category: 'Massage', duration: '90 phút', price: 1200000, status: 'Đang hiển thị' },
      { module: 'Sound bath', category: 'Wellness', duration: '60 phút', price: 850000, status: 'Đang hiển thị' },
    ],
  },
  appointment: {
    title: 'Quản lý Lịch hẹn',
    breadcrumbLabel: 'Lịch hẹn',
    addLabel: 'Thêm lịch',
    publicPath: '/spa2/appointment',
    fields: [
      { key: 'customer', label: 'Khách hàng', type: 'text' },
      { key: 'service', label: 'Dịch vụ', type: 'text' },
      { key: 'therapist', label: 'KTV', type: 'text' },
      { key: 'date', label: 'Ngày', type: 'date' },
      { key: 'time', label: 'Giờ', type: 'text' },
    ],
    statuses: S_ORDER,
    approvable: true,
    seed: [
      { customer: 'Anna N.', service: 'Facial vàng', therapist: 'Ms. Hoa', date: '2025-02-20', time: '10:00', status: 'Mới' },
      { customer: 'Minh T.', service: 'Massage đá nóng', therapist: 'Mr. Long', date: '2025-02-20', time: '14:00', status: 'Đang xử lý' },
      { customer: 'July L.', service: 'Body wrap', therapist: 'Ms. Trang', date: '2025-02-19', time: '16:30', status: 'Hoàn tất' },
    ],
  },
  newsletter: {
    title: 'Quản lý Newsletter',
    breadcrumbLabel: 'Newsletter',
    addLabel: 'Thêm bản tin',
    publicPath: '/spa2/newsletter',
    fields: [
      { key: 'subject', label: 'Tiêu đề', type: 'text' },
      { key: 'segment', label: 'Đối tượng', type: 'select', options: ['Tất cả', 'Thành viên', 'Khách VIP', 'Mới'] },
      { key: 'sendDate', label: 'Ngày gửi', type: 'date' },
      { key: 'content', label: 'Nội dung', type: 'textarea', showInTable: false },
    ],
    statuses: [
      { value: 'Bản nháp', color: 'default' as const },
      { value: 'Đã lên lịch', color: 'info' as const },
      { value: 'Đã gửi', color: 'success' as const },
    ],
    seed: [
      { subject: 'Ưu đãi tháng 3', segment: 'Tất cả', sendDate: '2025-03-01', content: '...', status: 'Đã lên lịch' },
      { subject: 'Cảm ơn thành viên', segment: 'Thành viên', sendDate: '2025-02-14', content: '...', status: 'Đã gửi' },
      { subject: 'Ra mắt sản phẩm mới', segment: 'Khách VIP', sendDate: '2025-03-10', content: '', status: 'Bản nháp' },
    ],
  },
  press: {
    title: 'Quản lý Bài báo chí',
    breadcrumbLabel: 'Press',
    addLabel: 'Thêm bài viết',
    publicPath: '/spa2/press',
    fields: [
      { key: 'title', label: 'Tiêu đề', type: 'text' },
      { key: 'publisher', label: 'Đơn vị', type: 'text' },
      { key: 'date', label: 'Ngày', type: 'date' },
      { key: 'link', label: 'Đường dẫn', type: 'text' },
      { key: 'summary', label: 'Tóm tắt', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      { title: 'Nature Spa mở CN mới', publisher: 'VnExpress', date: '2025-01-15', link: 'https://vnexpress.net/...', summary: '', status: 'Đang hiển thị' },
      { title: 'Xu hướng wellness 2025', publisher: 'Elle', date: '2025-01-20', link: 'https://elle.vn/...', summary: '', status: 'Đang hiển thị' },
      { title: 'Sản phẩm bền vững', publisher: 'Vogue', date: '2025-02-01', link: 'https://vogue.vn/...', summary: '', status: 'Bản nháp' },
    ],
  },
  affiliate: {
    title: 'Quản lý Đối tác Affiliate',
    breadcrumbLabel: 'Affiliate',
    addLabel: 'Thêm affiliate',
    publicPath: '/spa2/affiliate',
    fields: [
      { key: 'name', label: 'Tên', type: 'text' },
      { key: 'channel', label: 'Kênh', type: 'select', options: ['Instagram', 'TikTok', 'YouTube', 'Blog'] },
      { key: 'commission', label: 'Hoa hồng (%)', type: 'number' },
      { key: 'earnings', label: 'Thu nhập (VND)', type: 'number' },
    ],
    statuses: S_APV,
    approvable: true,
    seed: [
      { name: 'Anna Beauty', channel: 'Instagram', commission: 15, earnings: 12500000, status: 'Đã duyệt' },
      { name: 'Skincare Diary', channel: 'TikTok', commission: 12, earnings: 8200000, status: 'Đã duyệt' },
      { name: 'Wellness With Ha', channel: 'YouTube', commission: 20, earnings: 0, status: 'Chờ duyệt' },
    ],
  },
  'spa-finder': {
    title: 'Quản lý Spa Finder',
    breadcrumbLabel: 'Spa Finder',
    addLabel: 'Thêm địa điểm',
    publicPath: '/spa2/spa-finder',
    fields: [
      { key: 'name', label: 'Tên chi nhánh', type: 'text' },
      { key: 'city', label: 'Thành phố', type: 'text' },
      { key: 'address', label: 'Địa chỉ', type: 'textarea', showInTable: false },
      { key: 'phone', label: 'Điện thoại', type: 'text' },
      { key: 'lat', label: 'Lat', type: 'number', showInTable: false },
      { key: 'lng', label: 'Lng', type: 'number', showInTable: false },
    ],
    statuses: [
      { value: 'Đang mở', color: 'success' as const },
      { value: 'Sắp khai trương', color: 'info' as const },
      { value: 'Đã đóng', color: 'default' as const },
    ],
    seed: [
      { name: 'CN Quận 1', city: 'HCM', address: '123 Lê Lợi, Q1', phone: '028 1234', lat: 10.77, lng: 106.7, status: 'Đang mở' },
      { name: 'CN Thảo Điền', city: 'HCM', address: '45 Xuân Thuỷ, Q2', phone: '028 5678', lat: 10.8, lng: 106.73, status: 'Đang mở' },
      { name: 'CN Hoàn Kiếm', city: 'HN', address: '10 Tràng Tiền', phone: '024 4321', lat: 21.02, lng: 105.85, status: 'Sắp khai trương' },
    ],
  },
  'spa-menu': {
    title: 'Quản lý Spa Menu',
    breadcrumbLabel: 'Spa Menu',
    addLabel: 'Thêm mục',
    publicPath: '/spa2/spa-menu',
    fields: [
      { key: 'name', label: 'Tên', type: 'text' },
      { key: 'category', label: 'Danh mục', type: 'select', options: ['Signature', 'Facial', 'Body', 'Massage', 'Add-on'] },
      { key: 'duration', label: 'Thời lượng', type: 'text' },
      { key: 'price', label: 'Giá (VND)', type: 'number' },
      { key: 'description', label: 'Mô tả', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      { name: 'Signature Ritual', category: 'Signature', duration: '150 phút', price: 3500000, description: 'Trải nghiệm đặc trưng', status: 'Đang hiển thị' },
      { name: 'Facial vàng 24K', category: 'Facial', duration: '90 phút', price: 2200000, description: '', status: 'Đang hiển thị' },
      { name: 'Body scrub cafe', category: 'Body', duration: '60 phút', price: 850000, description: '', status: 'Đang hiển thị' },
    ],
  },
  'ingredient-guide': {
    title: 'Quản lý Ingredient Guide',
    breadcrumbLabel: 'Ingredient Guide',
    addLabel: 'Thêm thành phần',
    publicPath: '/spa2/ingredient-guide',
    fields: [
      { key: 'name', label: 'Thành phần', type: 'text' },
      { key: 'benefit', label: 'Công dụng', type: 'text' },
      { key: 'origin', label: 'Nguồn gốc', type: 'text' },
      { key: 'suitableFor', label: 'Phù hợp cho', type: 'text' },
      { key: 'description', label: 'Chi tiết', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      { name: 'Hyaluronic Acid', benefit: 'Cấp ẩm sâu', origin: 'Tổng hợp', suitableFor: 'Mọi loại da', description: '', status: 'Đang hiển thị' },
      { name: 'Retinol', benefit: 'Chống lão hoá', origin: 'Vitamin A', suitableFor: 'Da > 25', description: '', status: 'Đang hiển thị' },
      { name: 'Trà xanh', benefit: 'Kháng viêm', origin: 'Bảo Lộc', suitableFor: 'Da mụn', description: '', status: 'Đang hiển thị' },
    ],
  },
  'skin-school': {
    title: 'Quản lý Skin School',
    breadcrumbLabel: 'Skin School',
    addLabel: 'Thêm khoá học',
    publicPath: '/spa2/skin-school',
    fields: [
      { key: 'name', label: 'Khoá học', type: 'text' },
      { key: 'level', label: 'Cấp độ', type: 'select', options: ['Cơ bản', 'Nâng cao', 'Chuyên sâu'] },
      { key: 'duration', label: 'Thời lượng', type: 'text' },
      { key: 'instructor', label: 'Giảng viên', type: 'text' },
      { key: 'price', label: 'Học phí (VND)', type: 'number' },
    ],
    statuses: S_PUB,
    seed: [
      { name: 'Skincare 101', level: 'Cơ bản', duration: '4 buổi', instructor: 'Dr. Han', price: 2500000, status: 'Đang hiển thị' },
      { name: 'Chuyên đề trị mụn', level: 'Nâng cao', duration: '6 buổi', instructor: 'Dr. Linh', price: 4500000, status: 'Đang hiển thị' },
      { name: 'Aesthetic Master', level: 'Chuyên sâu', duration: '12 buổi', instructor: 'Dr. An', price: 15000000, status: 'Bản nháp' },
    ],
  },
  'therapist-profile': {
    title: 'Quản lý Hồ sơ KTV',
    breadcrumbLabel: 'Therapist',
    addLabel: 'Thêm KTV',
    publicPath: '/spa2/therapist-profile',
    fields: [
      { key: 'image', label: 'Ảnh', type: 'image' },
      { key: 'name', label: 'Họ tên', type: 'text' },
      { key: 'specialty', label: 'Chuyên môn', type: 'text' },
      { key: 'experience', label: 'Kinh nghiệm (năm)', type: 'number' },
      { key: 'rating', label: 'Đánh giá', type: 'number' },
      { key: 'bio', label: 'Giới thiệu', type: 'textarea', showInTable: false },
    ],
    statuses: [
      { value: 'Đang làm việc', color: 'success' as const },
      { value: 'Nghỉ phép', color: 'warning' as const },
      { value: 'Đã nghỉ', color: 'default' as const },
    ],
    seed: [
      { image: img('photo-1544005313-94ddf0286df2'), name: 'Ms. Hoa', specialty: 'Facial', experience: 8, rating: 4.9, bio: '', status: 'Đang làm việc' },
      { image: img('photo-1580489944761-15a19d654956'), name: 'Ms. Trang', specialty: 'Body', experience: 5, rating: 4.7, bio: '', status: 'Đang làm việc' },
      { image: img('photo-1573497019940-1c28c88b4f3e'), name: 'Mr. Long', specialty: 'Massage đá nóng', experience: 10, rating: 4.8, bio: '', status: 'Nghỉ phép' },
    ],
  },
  'sleep-wellness': {
    title: 'Quản lý Sleep Wellness',
    breadcrumbLabel: 'Sleep Wellness',
    addLabel: 'Thêm chương trình',
    publicPath: '/spa2/sleep-wellness',
    fields: [
      { key: 'name', label: 'Tên', type: 'text' },
      { key: 'technique', label: 'Kỹ thuật', type: 'text' },
      { key: 'duration', label: 'Thời lượng', type: 'text' },
      { key: 'price', label: 'Giá (VND)', type: 'number' },
      { key: 'description', label: 'Mô tả', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      { name: 'Deep Sleep Ritual', technique: 'Aromatherapy + massage', duration: '90 phút', price: 1500000, description: '', status: 'Đang hiển thị' },
      { name: 'Sleep Coaching', technique: 'Tư vấn 1-1', duration: '60 phút', price: 850000, description: '', status: 'Đang hiển thị' },
      { name: 'Overnight Wellness', technique: 'Lưu trú', duration: '12 giờ', price: 5500000, description: '', status: 'Bản nháp' },
    ],
  },
  'prenatal-spa': {
    title: 'Quản lý Prenatal Spa',
    breadcrumbLabel: 'Prenatal',
    addLabel: 'Thêm liệu trình',
    publicPath: '/spa2/prenatal-spa',
    fields: [
      { key: 'name', label: 'Liệu trình', type: 'text' },
      { key: 'trimester', label: 'Tam cá nguyệt', type: 'select', options: ['1', '2', '3'] },
      { key: 'duration', label: 'Thời lượng', type: 'text' },
      { key: 'price', label: 'Giá (VND)', type: 'number' },
      { key: 'notes', label: 'Ghi chú y tế', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      { name: 'Prenatal Massage', trimester: '2', duration: '60 phút', price: 950000, notes: 'Không dùng tinh dầu mạnh', status: 'Đang hiển thị' },
      { name: 'Bụng bầu chăm sóc', trimester: '3', duration: '75 phút', price: 1100000, notes: '', status: 'Đang hiển thị' },
      { name: 'Postnatal Recovery', trimester: '3', duration: '90 phút', price: 1350000, notes: 'Sau sinh 6 tuần', status: 'Bản nháp' },
    ],
  },
  'wellness-assessment': {
    title: 'Quản lý Đánh giá Wellness',
    breadcrumbLabel: 'Wellness Assessment',
    addLabel: 'Thêm bộ đánh giá',
    publicPath: '/spa2/wellness-assessment',
    fields: [
      { key: 'name', label: 'Bộ đánh giá', type: 'text' },
      { key: 'category', label: 'Nhóm', type: 'select', options: ['Da', 'Cơ thể', 'Tinh thần', 'Dinh dưỡng'] },
      { key: 'questions', label: 'Số câu', type: 'number' },
      { key: 'duration', label: 'Thời gian ước tính', type: 'text' },
      { key: 'description', label: 'Mô tả', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      { name: 'Skin Health Check', category: 'Da', questions: 15, duration: '5 phút', description: '', status: 'Đang hiển thị' },
      { name: 'Stress Level Test', category: 'Tinh thần', questions: 20, duration: '7 phút', description: '', status: 'Đang hiển thị' },
      { name: 'Nutrition Profile', category: 'Dinh dưỡng', questions: 25, duration: '10 phút', description: '', status: 'Bản nháp' },
    ],
  },
};
