import type { Spa2ManageConfig } from './spa2-generic-manage-view';

// ─────────────────────────────────────────────────────────────────────────────
// Reusable status presets
const S_PUB = [
  { value: 'Bản nháp', color: 'default' as const },
  { value: 'Đang hiển thị', color: 'success' as const },
  { value: 'Ẩn', color: 'warning' as const },
];
const S_APV = [
  { value: 'Chờ duyệt', color: 'warning' as const },
  { value: 'Đã duyệt', color: 'success' as const },
  { value: 'Từ chối', color: 'error' as const },
];
const S_ORDER = [
  { value: 'Mới', color: 'info' as const },
  { value: 'Đang xử lý', color: 'warning' as const },
  { value: 'Hoàn tất', color: 'success' as const },
  { value: 'Đã huỷ', color: 'error' as const },
];

const img = (seed: string) => `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=400&q=60`;

// ─────────────────────────────────────────────────────────────────────────────

// NOTE: 'membership' / 'gift-card' / 'wellness-package' / 'skin-quiz' /
// 'corporate' / 'shop' / 'sustainability' / 'events' / 'referral' /
// 'app-download' / 'special-occasions' / 'home-service' / 'skin-diary' /
// 'mindfulness' / 'medical-spa' / 'spa-etiquette' / 'loyalty-rewards' /
// 'review' / 'seasonal-package' / 'nutrition' / 'consultation' /
// 'vip-room' / 'package-builder' / 'appointment' / 'newsletter' / 'press' /
// 'affiliate' / 'spa-finder' / 'spa-menu' / 'ingredient-guide' used to be
// generic flat-table configs here, but now have bespoke manage views (see
// spa2-membership-manage-view.tsx / spa2-gift-card-manage-view.tsx /
// spa2-wellness-package-manage-view.tsx / spa2-skin-quiz-manage-view.tsx /
// spa2-corporate-manage-view.tsx / spa2-shop-manage-view.tsx /
// spa2-sustainability-manage-view.tsx / spa2-events-manage-view.tsx /
// spa2-referral-manage-view.tsx / spa2-app-download-manage-view.tsx /
// spa2-special-occasions-manage-view.tsx / spa2-home-service-manage-view.tsx /
// spa2-skin-diary-manage-view.tsx / spa2-mindfulness-manage-view.tsx /
// spa2-medical-spa-manage-view.tsx / spa2-spa-etiquette-manage-view.tsx /
// spa2-loyalty-rewards-manage-view.tsx / spa2-review-manage-view.tsx /
// spa2-seasonal-package-manage-view.tsx / spa2-nutrition-manage-view.tsx /
// spa2-consultation-manage-view.tsx / spa2-vip-room-manage-view.tsx /
// spa2-package-builder-manage-view.tsx / spa2-appointment-manage-view.tsx /
// spa2-newsletter-manage-view.tsx / spa2-press-manage-view.tsx /
// spa2-affiliate-manage-view.tsx / spa2-spa-finder-manage-view.tsx /
// spa2-spa-menu-manage-view.tsx / spa2-ingredient-guide-manage-view.tsx)
// that share their catalog data with the public pages via src/_mock/_spa2 -
// so they were removed from this map.

export const SPA2_MANAGE_CONFIGS: Record<string, Spa2ManageConfig> = {
  'skin-school': {
    title: 'Quản lý Skin School',
    breadcrumbLabel: 'Skin School',
    addLabel: 'Thêm khoá học',
    publicPath: '/spa2/skin-school',
    fields: [
      { key: 'name', label: 'Khoá học', type: 'text' },
      {
        key: 'level',
        label: 'Cấp độ',
        type: 'select',
        options: ['Cơ bản', 'Nâng cao', 'Chuyên sâu'],
      },
      { key: 'duration', label: 'Thời lượng', type: 'text' },
      { key: 'instructor', label: 'Giảng viên', type: 'text' },
      { key: 'price', label: 'Học phí (VND)', type: 'number' },
    ],
    statuses: S_PUB,
    seed: [
      {
        name: 'Skincare 101',
        level: 'Cơ bản',
        duration: '4 buổi',
        instructor: 'Dr. Han',
        price: 2500000,
        status: 'Đang hiển thị',
      },
      {
        name: 'Chuyên đề trị mụn',
        level: 'Nâng cao',
        duration: '6 buổi',
        instructor: 'Dr. Linh',
        price: 4500000,
        status: 'Đang hiển thị',
      },
      {
        name: 'Aesthetic Master',
        level: 'Chuyên sâu',
        duration: '12 buổi',
        instructor: 'Dr. An',
        price: 15000000,
        status: 'Bản nháp',
      },
    ],
  },
  'therapist-profile': {
    title: 'Quản lý Hồ sơ KTV',
    breadcrumbLabel: 'Therapist',
    addLabel: 'Thêm KTV',
    publicPath: '/spa2/therapist-profile',
    fields: [
      { key: 'image', label: 'Ảnh', type: 'image' },
      { key: 'name', label: 'Họ tên', type: 'text' },
      { key: 'specialty', label: 'Chuyên môn', type: 'text' },
      { key: 'experience', label: 'Kinh nghiệm (năm)', type: 'number' },
      { key: 'rating', label: 'Đánh giá', type: 'number' },
      { key: 'bio', label: 'Giới thiệu', type: 'textarea', showInTable: false },
    ],
    statuses: [
      { value: 'Đang làm việc', color: 'success' as const },
      { value: 'Nghỉ phép', color: 'warning' as const },
      { value: 'Đã nghỉ', color: 'default' as const },
    ],
    seed: [
      {
        image: img('photo-1544005313-94ddf0286df2'),
        name: 'Ms. Hoa',
        specialty: 'Facial',
        experience: 8,
        rating: 4.9,
        bio: '',
        status: 'Đang làm việc',
      },
      {
        image: img('photo-1580489944761-15a19d654956'),
        name: 'Ms. Trang',
        specialty: 'Body',
        experience: 5,
        rating: 4.7,
        bio: '',
        status: 'Đang làm việc',
      },
      {
        image: img('photo-1573497019940-1c28c88b4f3e'),
        name: 'Mr. Long',
        specialty: 'Massage đá nóng',
        experience: 10,
        rating: 4.8,
        bio: '',
        status: 'Nghỉ phép',
      },
    ],
  },
  'sleep-wellness': {
    title: 'Quản lý Sleep Wellness',
    breadcrumbLabel: 'Sleep Wellness',
    addLabel: 'Thêm chương trình',
    publicPath: '/spa2/sleep-wellness',
    fields: [
      { key: 'name', label: 'Tên', type: 'text' },
      { key: 'technique', label: 'Kỹ thuật', type: 'text' },
      { key: 'duration', label: 'Thời lượng', type: 'text' },
      { key: 'price', label: 'Giá (VND)', type: 'number' },
      { key: 'description', label: 'Mô tả', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      {
        name: 'Deep Sleep Ritual',
        technique: 'Aromatherapy + massage',
        duration: '90 phút',
        price: 1500000,
        description: '',
        status: 'Đang hiển thị',
      },
      {
        name: 'Sleep Coaching',
        technique: 'Tư vấn 1-1',
        duration: '60 phút',
        price: 850000,
        description: '',
        status: 'Đang hiển thị',
      },
      {
        name: 'Overnight Wellness',
        technique: 'Lưu trú',
        duration: '12 giờ',
        price: 5500000,
        description: '',
        status: 'Bản nháp',
      },
    ],
  },
  'prenatal-spa': {
    title: 'Quản lý Prenatal Spa',
    breadcrumbLabel: 'Prenatal',
    addLabel: 'Thêm liệu trình',
    publicPath: '/spa2/prenatal-spa',
    fields: [
      { key: 'name', label: 'Liệu trình', type: 'text' },
      { key: 'trimester', label: 'Tam cá nguyệt', type: 'select', options: ['1', '2', '3'] },
      { key: 'duration', label: 'Thời lượng', type: 'text' },
      { key: 'price', label: 'Giá (VND)', type: 'number' },
      { key: 'notes', label: 'Ghi chú y tế', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      {
        name: 'Prenatal Massage',
        trimester: '2',
        duration: '60 phút',
        price: 950000,
        notes: 'Không dùng tinh dầu mạnh',
        status: 'Đang hiển thị',
      },
      {
        name: 'Bụng bầu chăm sóc',
        trimester: '3',
        duration: '75 phút',
        price: 1100000,
        notes: '',
        status: 'Đang hiển thị',
      },
      {
        name: 'Postnatal Recovery',
        trimester: '3',
        duration: '90 phút',
        price: 1350000,
        notes: 'Sau sinh 6 tuần',
        status: 'Bản nháp',
      },
    ],
  },
  'wellness-assessment': {
    title: 'Quản lý Đánh giá Wellness',
    breadcrumbLabel: 'Wellness Assessment',
    addLabel: 'Thêm bộ đánh giá',
    publicPath: '/spa2/wellness-assessment',
    fields: [
      { key: 'name', label: 'Bộ đánh giá', type: 'text' },
      {
        key: 'category',
        label: 'Nhóm',
        type: 'select',
        options: ['Da', 'Cơ thể', 'Tinh thần', 'Dinh dưỡng'],
      },
      { key: 'questions', label: 'Số câu', type: 'number' },
      { key: 'duration', label: 'Thời gian ước tính', type: 'text' },
      { key: 'description', label: 'Mô tả', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      {
        name: 'Skin Health Check',
        category: 'Da',
        questions: 15,
        duration: '5 phút',
        description: '',
        status: 'Đang hiển thị',
      },
      {
        name: 'Stress Level Test',
        category: 'Tinh thần',
        questions: 20,
        duration: '7 phút',
        description: '',
        status: 'Đang hiển thị',
      },
      {
        name: 'Nutrition Profile',
        category: 'Dinh dưỡng',
        questions: 25,
        duration: '10 phút',
        description: '',
        status: 'Bản nháp',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 8 new management pages: franchise · group-booking · certificate-wall
  // video-guide · price-list · wait-list · voucher-check · accessibility
  // ─────────────────────────────────────────────────────────────────────────────

  franchise: {
    title: 'Quản lý Nhượng quyền',
    breadcrumbLabel: 'Nhượng quyền',
    addLabel: 'Thêm đơn ứng tuyển',
    publicPath: '/spa2/franchise',
    fields: [
      { key: 'name', label: 'Người liên hệ', type: 'text', required: true },
      { key: 'company', label: 'Công ty / Cá nhân', type: 'text' },
      { key: 'city', label: 'Tỉnh/TP mở chi nhánh', type: 'text' },
      {
        key: 'model',
        label: 'Mô hình',
        type: 'select',
        options: ['Starter', 'Standard', 'Premium'],
      },
      { key: 'phone', label: 'Điện thoại', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'investment', label: 'Nguồn vốn dự kiến', type: 'text' },
      { key: 'notes', label: 'Ghi chú', type: 'textarea', showInTable: false },
    ],
    statuses: S_APV,
    approvable: true,
    seed: [
      {
        name: 'Nguyễn Văn A',
        company: 'FutureSpa Co.',
        city: 'Đà Nẵng',
        model: 'Standard',
        phone: '0901 234 567',
        email: 'a@futurespa.vn',
        investment: '2–3 tỷ',
        notes: '',
        status: 'Chờ duyệt',
      },
      {
        name: 'Trần Thị B',
        company: 'B Beauty Group',
        city: 'Cần Thơ',
        model: 'Starter',
        phone: '0912 345 678',
        email: 'b@beautygr.vn',
        investment: '1–2 tỷ',
        notes: 'Đã có kinh nghiệm spa 3 năm',
        status: 'Đã duyệt',
      },
      {
        name: 'Lê Minh C',
        company: 'Premium Wellness',
        city: 'Hà Nội',
        model: 'Premium',
        phone: '0987 654 321',
        email: 'c@premiumwl.vn',
        investment: '5–8 tỷ',
        notes: 'Đầu tư bất động sản sẵn có',
        status: 'Đã duyệt',
      },
      {
        name: 'Phạm Thị D',
        company: '',
        city: 'Vũng Tàu',
        model: 'Starter',
        phone: '0908 111 222',
        email: 'd@gmail.com',
        investment: '<1 tỷ',
        notes: 'Cần tư vấn thêm điều khoản',
        status: 'Chờ duyệt',
      },
    ],
  },

  'group-booking': {
    title: 'Quản lý Đặt lịch nhóm',
    breadcrumbLabel: 'Đặt lịch nhóm',
    addLabel: 'Thêm đặt lịch nhóm',
    publicPath: '/spa2/group-booking',
    fields: [
      { key: 'groupName', label: 'Tên nhóm / Công ty', type: 'text', required: true },
      {
        key: 'occasion',
        label: 'Dịp',
        type: 'select',
        options: [
          'Team Building',
          'Tiệc công ty',
          'Hội bạn thân',
          'Gia đình đoàn tụ',
          'Sinh nhật',
          'Khác',
        ],
      },
      { key: 'size', label: 'Số người', type: 'number' },
      { key: 'service', label: 'Dịch vụ', type: 'text' },
      { key: 'branch', label: 'Chi nhánh', type: 'text' },
      { key: 'date', label: 'Ngày', type: 'date' },
      { key: 'contact', label: 'Người đặt', type: 'text' },
      { key: 'phone', label: 'Điện thoại', type: 'text' },
      { key: 'notes', label: 'Yêu cầu đặc biệt', type: 'textarea', showInTable: false },
    ],
    statuses: S_ORDER,
    approvable: true,
    seed: [
      {
        groupName: 'FPT Software HCM',
        occasion: 'Team Building',
        size: 25,
        service: 'Massage + Facial',
        branch: 'Quận 1',
        date: '2026-08-20',
        contact: 'Ms. Hà Phương',
        phone: '0901 111 222',
        notes: 'Cần hội trường nhỏ 20 chỗ',
        status: 'Đang xử lý',
      },
      {
        groupName: 'Hội bạn Lê Quý Đôn K35',
        occasion: 'Hội bạn thân',
        size: 8,
        service: 'Facial + Body scrub',
        branch: 'Thảo Điền',
        date: '2026-08-25',
        contact: 'Ms. Lan Anh',
        phone: '0912 333 444',
        notes: '',
        status: 'Mới',
      },
      {
        groupName: 'VNG Corporation',
        occasion: 'Tiệc công ty',
        size: 40,
        service: 'Massage toàn thân',
        branch: 'Quận 1',
        date: '2026-09-01',
        contact: 'Mr. Minh Hùng',
        phone: '0987 555 666',
        notes: 'Year-end party kết hợp tiệc nhẹ',
        status: 'Hoàn tất',
      },
      {
        groupName: 'Gia đình Trần – 3 thế hệ',
        occasion: 'Gia đình đoàn tụ',
        size: 12,
        service: 'Mẹ & Bé Spa Together',
        branch: 'Hà Nội',
        date: '2026-09-10',
        contact: 'Mr. Trần Quân',
        phone: '0908 999 000',
        notes: 'Có 4 trẻ em 5–12 tuổi',
        status: 'Mới',
      },
    ],
  },

  'certificate-wall': {
    title: 'Quản lý Tường chứng nhận',
    breadcrumbLabel: 'Certificate Wall',
    addLabel: 'Thêm chứng nhận',
    publicPath: '/spa2/certificate-wall',
    fields: [
      { key: 'name', label: 'Tên chứng nhận', type: 'text', required: true },
      { key: 'issuer', label: 'Đơn vị cấp', type: 'text' },
      { key: 'issuedTo', label: 'Cấp cho', type: 'text' },
      { key: 'code', label: 'Mã chứng nhận', type: 'text' },
      { key: 'issueDate', label: 'Ngày cấp', type: 'date' },
      { key: 'expiry', label: 'Ngày hết hạn', type: 'date' },
      {
        key: 'category',
        label: 'Loại',
        type: 'select',
        options: [
          'Chất lượng dịch vụ',
          'An toàn & Vệ sinh',
          'Đào tạo nhân sự',
          'Thương hiệu',
          'Quốc tế',
        ],
      },
      { key: 'description', label: 'Mô tả', type: 'textarea', showInTable: false },
    ],
    statuses: [
      { value: 'Còn hiệu lực', color: 'success' as const },
      { value: 'Sắp hết hạn', color: 'warning' as const },
      { value: 'Hết hạn', color: 'error' as const },
      { value: 'Chờ cấp mới', color: 'info' as const },
    ],
    seed: [
      {
        name: 'ISO 9001:2015 — Quản lý chất lượng',
        issuer: 'Bureau Veritas',
        issuedTo: 'Nature Spa Vietnam',
        code: 'BV-ISO-2024-001',
        issueDate: '2024-01-15',
        expiry: '2027-01-14',
        category: 'Chất lượng dịch vụ',
        description: 'Hệ thống quản lý chất lượng dịch vụ spa theo tiêu chuẩn quốc tế',
        status: 'Còn hiệu lực',
      },
      {
        name: 'Organic Spa Certification',
        issuer: 'IOAS Vietnam',
        issuedTo: 'Nature Spa Vietnam',
        code: 'IOAS-2024-089',
        issueDate: '2024-03-01',
        expiry: '2026-02-28',
        category: 'Thương hiệu',
        description: 'Spa hữu cơ được kiểm định độc lập',
        status: 'Còn hiệu lực',
      },
      {
        name: 'AHLEI Spa Management',
        issuer: 'AHLEI USA',
        issuedTo: 'Ms. Hoa — Giám đốc kỹ thuật',
        code: 'AHLEI-2022-345',
        issueDate: '2022-05-10',
        expiry: '2025-05-09',
        category: 'Đào tạo nhân sự',
        description: 'Chứng chỉ quản lý spa quốc tế AHLEI',
        status: 'Sắp hết hạn',
      },
      {
        name: 'HACCP An toàn vệ sinh',
        issuer: 'SGS Vietnam',
        issuedTo: 'Nature Spa Vietnam',
        code: 'SGS-HACCP-2021-NV',
        issueDate: '2021-08-20',
        expiry: '2024-08-19',
        category: 'An toàn & Vệ sinh',
        description: 'Quy trình kiểm soát vệ sinh an toàn sản phẩm',
        status: 'Hết hạn',
      },
    ],
  },

  'video-guide': {
    title: 'Quản lý Video hướng dẫn',
    breadcrumbLabel: 'Video Guide',
    addLabel: 'Thêm video',
    publicPath: '/spa2/video-guide',
    fields: [
      { key: 'title', label: 'Tiêu đề', type: 'text', required: true },
      {
        key: 'category',
        label: 'Danh mục',
        type: 'select',
        options: [
          'Chuẩn bị trước liệu trình',
          'Chăm sóc sau liệu trình',
          'Hướng dẫn sản phẩm',
          'Skincare routine',
          'FAQ video',
        ],
      },
      { key: 'thumbnail', label: 'Ảnh bìa', type: 'image' },
      { key: 'videoUrl', label: 'URL Video (YouTube/Vimeo)', type: 'text' },
      { key: 'duration', label: 'Thời lượng', type: 'text' },
      { key: 'order', label: 'Thứ tự hiển thị', type: 'number' },
      { key: 'description', label: 'Mô tả ngắn', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      {
        title: 'Chuẩn bị gì trước khi đến spa?',
        category: 'Chuẩn bị trước liệu trình',
        thumbnail: img('photo-1540555700478-4be289fbecef'),
        videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        duration: '3:24',
        order: 1,
        description: 'Những điều cần biết trước buổi spa đầu tiên.',
        status: 'Đang hiển thị',
      },
      {
        title: 'Chăm sóc da sau Facial đúng cách',
        category: 'Chăm sóc sau liệu trình',
        thumbnail: img('photo-1596178060810-72660ee8d1ae'),
        videoUrl: 'https://www.youtube.com/watch?v=abc123',
        duration: '5:12',
        order: 2,
        description: 'Hướng dẫn bước skincare 24h sau facial.',
        status: 'Đang hiển thị',
      },
      {
        title: 'Cách dùng Serum Vitamin C hiệu quả',
        category: 'Hướng dẫn sản phẩm',
        thumbnail: img('photo-1556228720-195a672e8a03'),
        videoUrl: 'https://www.youtube.com/watch?v=xyz789',
        duration: '4:45',
        order: 3,
        description: 'Demo thực hành cùng chuyên gia.',
        status: 'Đang hiển thị',
      },
      {
        title: 'Morning Skincare Routine 5 bước',
        category: 'Skincare routine',
        thumbnail: img('photo-1512290923902-8a9f81dc236c'),
        videoUrl: 'https://www.youtube.com/watch?v=morning',
        duration: '7:30',
        order: 4,
        description: '',
        status: 'Bản nháp',
      },
    ],
  },

  'price-list': {
    title: 'Quản lý Bảng giá',
    breadcrumbLabel: 'Bảng giá',
    addLabel: 'Thêm mục giá',
    publicPath: '/spa2/price-list',
    fields: [
      { key: 'name', label: 'Tên dịch vụ / Liệu trình', type: 'text', required: true },
      {
        key: 'category',
        label: 'Danh mục',
        type: 'select',
        options: ['Dịch vụ lẻ', 'Liệu trình', 'Gói combo', 'Add-on', 'Sản phẩm'],
      },
      { key: 'price', label: 'Giá (VND)', type: 'number' },
      { key: 'duration', label: 'Thời lượng / Số buổi', type: 'text' },
      { key: 'note', label: 'Ghi chú', type: 'text' },
      { key: 'order', label: 'Thứ tự', type: 'number', showInTable: false },
      { key: 'description', label: 'Mô tả đầy đủ', type: 'textarea', showInTable: false },
    ],
    statuses: S_PUB,
    seed: [
      {
        name: 'Deep Clean Facial For Men',
        category: 'Dịch vụ lẻ',
        price: 790000,
        duration: '60 phút',
        note: '',
        order: 1,
        description: '',
        status: 'Đang hiển thị',
      },
      {
        name: 'Sports Recovery Massage',
        category: 'Dịch vụ lẻ',
        price: 890000,
        duration: '75 phút',
        note: 'Dành cho nam',
        order: 2,
        description: '',
        status: 'Đang hiển thị',
      },
      {
        name: 'Collagen Renewal 4 buổi',
        category: 'Liệu trình',
        price: 4990000,
        duration: '4 buổi × 75 phút',
        note: 'Tiết kiệm 15%',
        order: 3,
        description: '',
        status: 'Đang hiển thị',
      },
      {
        name: 'Spa Escape Weeknight',
        category: 'Gói combo',
        price: 3900000,
        duration: '1 đêm',
        note: 'Bao gồm khách sạn + 2 liệu trình',
        order: 4,
        description: '',
        status: 'Đang hiển thị',
      },
      {
        name: 'Aromatherapy Add-on',
        category: 'Add-on',
        price: 150000,
        duration: '+15 phút',
        note: 'Thêm vào bất kỳ liệu trình nào',
        order: 5,
        description: '',
        status: 'Đang hiển thị',
      },
    ],
  },

  'wait-list': {
    title: 'Quản lý Danh sách chờ',
    breadcrumbLabel: 'Danh sách chờ',
    addLabel: 'Thêm vào danh sách chờ',
    publicPath: '/spa2/wait-list',
    fields: [
      { key: 'customer', label: 'Khách hàng', type: 'text', required: true },
      { key: 'phone', label: 'Điện thoại', type: 'text' },
      { key: 'service', label: 'Dịch vụ mong muốn', type: 'text' },
      { key: 'branch', label: 'Chi nhánh', type: 'text' },
      { key: 'preferredDate', label: 'Ngày mong muốn', type: 'date' },
      { key: 'flexible', label: 'Linh hoạt thời gian?', type: 'select', options: ['Có', 'Không'] },
      { key: 'notes', label: 'Ghi chú / Yêu cầu', type: 'textarea', showInTable: false },
    ],
    statuses: [
      { value: 'Đang chờ', color: 'info' as const },
      { value: 'Đã thông báo', color: 'warning' as const },
      { value: 'Đã xác nhận', color: 'success' as const },
      { value: 'Đã huỷ', color: 'error' as const },
    ],
    approvable: true,
    seed: [
      {
        customer: 'Nguyễn Thị Lan',
        phone: '0901 234 567',
        service: 'Facial Organic',
        branch: 'Quận 1',
        preferredDate: '2026-07-20',
        flexible: 'Có',
        notes: '',
        status: 'Đang chờ',
      },
      {
        customer: 'Trần Minh Quang',
        phone: '0912 345 678',
        service: 'Massage Thảo Dược',
        branch: 'Hà Nội',
        preferredDate: '2026-07-22',
        flexible: 'Không',
        notes: 'Chỉ buổi sáng thứ 7',
        status: 'Đã thông báo',
      },
      {
        customer: 'Lê Hương Giang',
        phone: '0987 654 321',
        service: 'Spa Đôi',
        branch: 'Quận 1',
        preferredDate: '2026-07-25',
        flexible: 'Có',
        notes: 'Kỷ niệm 3 năm',
        status: 'Đã xác nhận',
      },
      {
        customer: 'Phan Thúy An',
        phone: '0908 765 432',
        service: 'Detox 3 ngày',
        branch: 'Nha Trang',
        preferredDate: '2026-08-01',
        flexible: 'Không',
        notes: 'Cần phòng view biển',
        status: 'Đang chờ',
      },
    ],
  },

  'voucher-check': {
    title: 'Quản lý Voucher & Thẻ quà tặng',
    breadcrumbLabel: 'Voucher & Thẻ quà',
    addLabel: 'Tạo voucher mới',
    publicPath: '/spa2/voucher-check',
    fields: [
      { key: 'code', label: 'Mã voucher', type: 'text', required: true },
      {
        key: 'type',
        label: 'Loại',
        type: 'select',
        options: [
          'Voucher dịch vụ',
          'Thẻ quà tặng',
          'Voucher giảm giá',
          'Voucher sinh nhật',
          'Voucher doanh nghiệp',
        ],
      },
      { key: 'value', label: 'Mệnh giá (VND)', type: 'number' },
      { key: 'balance', label: 'Số dư còn lại (VND)', type: 'number' },
      { key: 'expiry', label: 'Ngày hết hạn', type: 'date' },
      { key: 'issuedTo', label: 'Cấp cho', type: 'text' },
      { key: 'note', label: 'Ghi chú', type: 'textarea', showInTable: false },
    ],
    statuses: [
      { value: 'Còn hiệu lực', color: 'success' as const },
      { value: 'Đã dùng hết', color: 'default' as const },
      { value: 'Hết hạn', color: 'error' as const },
      { value: 'Đã thu hồi', color: 'warning' as const },
    ],
    seed: [
      {
        code: 'VCH-2026-001',
        type: 'Voucher dịch vụ',
        value: 500000,
        balance: 500000,
        expiry: '2027-06-30',
        issuedTo: 'Anna Nguyen',
        note: 'Tặng thành viên VIP',
        status: 'Còn hiệu lực',
      },
      {
        code: 'GIFT-BDAY-002',
        type: 'Voucher sinh nhật',
        value: 300000,
        balance: 300000,
        expiry: '2026-09-01',
        issuedTo: 'Minh Tran',
        note: 'Sinh nhật tháng 9',
        status: 'Còn hiệu lực',
      },
      {
        code: 'VCH-SALE-003',
        type: 'Voucher giảm giá',
        value: 200000,
        balance: 0,
        expiry: '2026-06-30',
        issuedTo: 'July Le',
        note: 'Flash sale tháng 6',
        status: 'Đã dùng hết',
      },
      {
        code: 'GIFTCARD-FPT',
        type: 'Voucher doanh nghiệp',
        value: 1000000,
        balance: 350000,
        expiry: '2025-12-31',
        issuedTo: 'Group FPT Software',
        note: 'Tặng nhân viên xuất sắc Q4',
        status: 'Hết hạn',
      },
    ],
  },

  accessibility: {
    title: 'Quản lý Tính năng Tiếp cận',
    breadcrumbLabel: 'Accessibility',
    addLabel: 'Thêm tính năng',
    publicPath: '/spa2/accessibility',
    fields: [
      { key: 'feature', label: 'Tính năng', type: 'text', required: true },
      {
        key: 'category',
        label: 'Nhóm',
        type: 'select',
        options: ['Vận động', 'Thị giác', 'Thính giác', 'Nhận thức', 'Hỗ trợ đặc biệt'],
      },
      { key: 'availability', label: 'Có tại', type: 'text' },
      { key: 'order', label: 'Thứ tự hiển thị', type: 'number', showInTable: false },
      { key: 'description', label: 'Mô tả chi tiết', type: 'textarea', showInTable: false },
    ],
    statuses: [
      { value: 'Đang cung cấp', color: 'success' as const },
      { value: 'Đang nâng cấp', color: 'warning' as const },
      { value: 'Tạm dừng', color: 'default' as const },
    ],
    seed: [
      {
        feature: 'Lối vào xe lăn',
        category: 'Vận động',
        availability: 'Tất cả chi nhánh',
        order: 1,
        description:
          'Toàn bộ khu vực không bậc thềm, đường dốc nhẹ dẫn vào, thang máy tại 2 chi nhánh nhiều tầng.',
        status: 'Đang cung cấp',
      },
      {
        feature: 'Giường massage điều chỉnh chiều cao',
        category: 'Vận động',
        availability: 'Tất cả chi nhánh',
        order: 2,
        description: 'Giường hạ/nâng điện tử từ 30–90 cm, phù hợp người khuyết tật vận động.',
        status: 'Đang cung cấp',
      },
      {
        feature: 'Hướng dẫn chữ nổi Braille',
        category: 'Thị giác',
        availability: 'Quận 1, Thảo Điền',
        order: 3,
        description: 'Menu dịch vụ và biển chỉ dẫn phòng có phiên bản chữ nổi Braille.',
        status: 'Đang nâng cấp',
      },
      {
        feature: 'Đồng hồ rung nhắc giờ liệu trình',
        category: 'Thính giác',
        availability: 'Tất cả chi nhánh',
        order: 4,
        description: 'Đồng hồ rung không dây cho khách khiếm thính, nhắc giờ bắt đầu và kết thúc.',
        status: 'Đang cung cấp',
      },
      {
        feature: 'Nhân viên hỗ trợ đặc biệt',
        category: 'Hỗ trợ đặc biệt',
        availability: 'Theo yêu cầu (đặt trước 48h)',
        order: 5,
        description: 'Đội ngũ được đào tạo chuyên sâu về hỗ trợ khách có nhu cầu đặc biệt.',
        status: 'Đang cung cấp',
      },
    ],
  },
};
