export type SpasLang = 'en' | 'vi' | 'fr' | 'cn' | 'ar';

export type SpaFilter = 'all' | 'asian' | 'european' | 'nature' | 'luxury' | 'tech';

export const FILTER_LABELS: Record<SpaFilter, Record<SpasLang, string>> = {
  all: { vi: 'Tất cả', en: 'All', fr: 'Tous', cn: '全部', ar: 'الكل' },
  asian: { vi: 'Châu Á', en: 'Asian', fr: 'Asiatique', cn: '亚洲', ar: 'آسيوي' },
  european: { vi: 'Châu Âu', en: 'European', fr: 'Européen', cn: '欧洲', ar: 'أوروبي' },
  nature: { vi: 'Thiên nhiên', en: 'Nature', fr: 'Nature', cn: '自然', ar: 'طبيعة' },
  luxury: { vi: 'Xa xỉ', en: 'Luxury', fr: 'Luxe', cn: '奢华', ar: 'فاخر' },
  tech: { vi: 'Công nghệ', en: 'Tech', fr: 'Tech', cn: '科技', ar: 'تقنية' },
};

export interface SpaCard {
  id: string;
  slug: string;
  name: string;
  tagline: Record<SpasLang, string>;
  description: Record<SpasLang, string>;
  concept: Record<SpasLang, string>;
  tags: SpaFilter[];
  palette: string[];
  accentColor: string;
  bgColor: string;
  textColor: string;
  image: string;
  badge?: Record<SpasLang, string>;
}

export const ALL_SPAS: SpaCard[] = [
  {
    id: 'spa',
    slug: '/spa',
    name: 'Serenity Spa',
    tagline: {
      vi: 'Zen & Cân bằng',
      en: 'Zen & Balance',
      fr: 'Zen & Équilibre',
      cn: '禅与平衡',
      ar: 'الزن والتوازن',
    },
    description: {
      vi: 'Wellness thuần Việt truyền thống — xông lá, massage thư giãn và tinh dầu thiên nhiên.',
      en: 'Traditional Vietnamese wellness — herbal steam, relaxation massage and natural essential oils.',
      fr: 'Bien-être vietnamien traditionnel — bain de vapeur aux herbes, massage relaxant et huiles essentielles naturelles.',
      cn: '传统越南养生——草本蒸汽、放松按摩与天然精油。',
      ar: 'عافية فيتنامية تقليدية — بخار الأعشاب وتدليك الاسترخاء والزيوت العطرية الطبيعية.',
    },
    concept: {
      vi: 'Thư giãn cổ truyền',
      en: 'Traditional relaxation',
      fr: 'Détente traditionnelle',
      cn: '传统放松',
      ar: 'استرخاء تقليدي',
    },
    tags: ['asian', 'nature'],
    palette: ['#1B4332', '#52B788', '#D8F3DC'],
    accentColor: '#52B788',
    bgColor: '#1B4332',
    textColor: '#D8F3DC',
    image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=600&q=80',
  },
  {
    id: 'spa4',
    slug: '/spa4',
    name: 'Jade Blossom',
    tagline: {
      vi: 'K-Beauty & Ngọc bích',
      en: 'K-Beauty & Jade',
      fr: 'K-Beauty & Jade',
      cn: 'K-美容与玉石',
      ar: 'جمال كوري ويشم',
    },
    description: {
      vi: 'Chăm sóc da Hàn Quốc với thạch ngọc bích, hoa anh đào và collagen.',
      en: 'Korean skincare with jade stone, cherry blossom and collagen.',
      fr: 'Soins de la peau coréens à la pierre de jade, fleur de cerisier et collagène.',
      cn: '韩式护肤，搭配玉石、樱花与胶原蛋白。',
      ar: 'العناية بالبشرة الكورية مع حجر اليشم وزهر الكرز والكولاجين.',
    },
    concept: {
      vi: 'Làm đẹp K-Beauty',
      en: 'K-Beauty skincare',
      fr: 'Soins K-Beauty',
      cn: 'K-美容护肤',
      ar: 'عناية كي-بيوتي',
    },
    tags: ['asian', 'tech'],
    palette: ['#2D6A4F', '#D4AF37', '#F8E8D0'],
    accentColor: '#D4AF37',
    bgColor: '#1B4030',
    textColor: '#F8E8D0',
    image: 'https://plus.unsplash.com/premium_photo-1661574718355-82659c0c74cc?w=600&q=80',
  },
  {
    id: 'spa5',
    slug: '/spa5',
    name: 'Lumière Balnéo',
    tagline: {
      vi: 'Hydrotherapy Pháp',
      en: 'French Hydrotherapy',
      fr: 'Hydrothérapie française',
      cn: '法式水疗',
      ar: 'العلاج المائي الفرنسي',
    },
    description: {
      vi: 'Liệu pháp thủy trị cao cấp Pháp với bể tắm khoáng nước ngọt và tắm bùn.',
      en: 'Premium French hydrotherapy with freshwater mineral pools and mud baths.',
      fr: "Hydrothérapie française haut de gamme avec bassins d'eau minérale douce et bains de boue.",
      cn: '高端法式水疗，配有淡水矿泉池与泥浴。',
      ar: 'علاج مائي فرنسي فاخر مع أحواض معدنية عذبة وحمامات طينية.',
    },
    concept: {
      vi: 'Spa nước Pháp',
      en: 'French water spa',
      fr: 'Spa aquatique français',
      cn: '法式水疗中心',
      ar: 'سبا مائي فرنسي',
    },
    tags: ['european', 'luxury'],
    palette: ['#0A1E3D', '#C9A55A', '#F5F0E8'],
    accentColor: '#C9A55A',
    bgColor: '#0A1E3D',
    textColor: '#F5F0E8',
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=600&q=80',
  },
  {
    id: 'spa6',
    slug: '/spa6',
    name: 'Terra Heal',
    tagline: {
      vi: 'Eco Bali & Ayurveda',
      en: 'Eco Bali & Ayurveda',
      fr: 'Éco Bali & Ayurveda',
      cn: '生态巴厘与阿育吠陀',
      ar: 'بالي البيئية والأيورفيدا',
    },
    description: {
      vi: 'Chữa lành sinh thái Bali kết hợp Ayurveda Ấn Độ — tinh dầu, đất sét và thảo mộc.',
      en: 'Eco Balinese healing combined with Indian Ayurveda — essential oils, clay and herbs.',
      fr: "Guérison balinaise écologique alliée à l'Ayurveda indien — huiles essentielles, argile et herbes.",
      cn: '生态巴厘疗愈融合印度阿育吠陀——精油、黏土与草本。',
      ar: 'شفاء بالي البيئي ممزوجًا بالأيورفيدا الهندية — زيوت عطرية وطين وأعشاب.',
    },
    concept: {
      vi: 'Sinh thái & Thảo mộc',
      en: 'Eco & Herbal',
      fr: 'Éco & Herbes',
      cn: '生态与草本',
      ar: 'بيئي وعشبي',
    },
    tags: ['asian', 'nature'],
    palette: ['#8B4513', '#2D6A4F', '#FFF8F0'],
    accentColor: '#8B4513',
    bgColor: '#1A0A00',
    textColor: '#FFF8F0',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80',
  },
  {
    id: 'spa7',
    slug: '/spa7',
    name: 'Noir & Rose',
    tagline: {
      vi: 'Seoul Beauty Tech',
      en: 'Seoul Beauty Tech',
      fr: 'Tech Beauté Séoul',
      cn: '首尔美容科技',
      ar: 'تقنية جمال سيول',
    },
    description: {
      vi: 'Công nghệ làm đẹp đỉnh cao Seoul-NYC: LED, RF Micro-Needling, HIFU, Cryotherapy.',
      en: 'Seoul-NYC cutting-edge beauty tech: LED, RF Micro-Needling, HIFU, Cryotherapy.',
      fr: 'Technologie beauté de pointe Séoul-NYC : LED, micro-aiguilletage RF, HIFU, cryothérapie.',
      cn: '首尔-纽约尖端美容科技：LED、射频微针、HIFU、冷冻疗法。',
      ar: 'تقنية جمال متطورة من سيول ونيويورك: LED، الوخز الدقيق بالترددات الراديوية، هايفو، العلاج بالتبريد.',
    },
    concept: {
      vi: 'Beauty clinic',
      en: 'Beauty clinic',
      fr: 'Clinique beauté',
      cn: '美容诊所',
      ar: 'عيادة تجميل',
    },
    tags: ['asian', 'tech', 'luxury'],
    palette: ['#0D0D0D', '#F4A7B9', '#FAFAFA'],
    accentColor: '#F4A7B9',
    bgColor: '#0D0D0D',
    textColor: '#FAFAFA',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80',
    badge: {
      vi: 'Glass Skin',
      en: 'Glass Skin',
      fr: 'Glass Skin',
      cn: '玻璃肌',
      ar: 'بشرة زجاجية',
    },
  },
  {
    id: 'spa8',
    slug: '/spa8',
    name: 'Amaya Onsen あまや温泉',
    tagline: {
      vi: 'Ryokan Nhật Bản',
      en: 'Japanese Ryokan',
      fr: 'Ryokan japonais',
      cn: '日式旅馆',
      ar: 'ريوكان ياباني',
    },
    description: {
      vi: 'Onsen khoáng nóng, shiatsu và 4 nghi lễ theo mùa theo triết lý Wabi-sabi Nhật Bản.',
      en: 'Hot mineral onsen, shiatsu and 4 seasonal rituals following Japanese Wabi-sabi philosophy.',
      fr: 'Onsen minéral chaud, shiatsu et 4 rituels saisonniers selon la philosophie japonaise Wabi-sabi.',
      cn: '温热矿物温泉、指压按摩与遵循日本侘寂哲学的四季仪式。',
      ar: 'أونسن معدني ساخن، شياتسو و4 طقوس موسمية وفق فلسفة وابي-سابي اليابانية.',
    },
    concept: {
      vi: 'Onsen & Shiatsu',
      en: 'Onsen & Shiatsu',
      fr: 'Onsen & Shiatsu',
      cn: '温泉与指压',
      ar: 'أونسن وشياتسو',
    },
    tags: ['asian', 'nature', 'luxury'],
    palette: ['#1A0A2E', '#C8A951', '#FFB7C5'],
    accentColor: '#C8A951',
    bgColor: '#1A0A2E',
    textColor: '#FFF8F0',
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&q=80',
  },
  {
    id: 'spa9',
    slug: '/spa9',
    name: 'Soleil Méditerranée',
    tagline: {
      vi: 'Địa Trung Hải coastal',
      en: 'Mediterranean coastal',
      fr: 'Côte méditerranéenne',
      cn: '地中海海岸',
      ar: 'ساحل البحر المتوسط',
    },
    description: {
      vi: 'Roman Bath, dầu olive Hy Lạp, muối biển Camargue và Day Pass từ bình minh đến hoàng hôn.',
      en: 'Roman Bath, Greek olive oil, Camargue sea salt and Day Pass from dawn to sunset.',
      fr: "Bain romain, huile d'olive grecque, sel de mer de Camargue et Day Pass de l'aube au coucher du soleil.",
      cn: '罗马浴、希腊橄榄油、卡马格海盐，以及从日出到日落的日间通票。',
      ar: 'حمام روماني، زيت زيتون يوناني، ملح بحر كامارغ وتذكرة نهارية من الفجر حتى الغروب.',
    },
    concept: {
      vi: 'Coastal wellness',
      en: 'Coastal wellness',
      fr: 'Bien-être côtier',
      cn: '海岸养生',
      ar: 'عافية ساحلية',
    },
    tags: ['european', 'nature'],
    palette: ['#1B6CA8', '#F5A623', '#FDF5E6'],
    accentColor: '#F5A623',
    bgColor: '#0A2840',
    textColor: '#FDF5E6',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
  },
  {
    id: 'spa10',
    slug: '/spa10',
    name: 'Aurora Nordic Spa',
    tagline: {
      vi: 'Scandinavian Forest',
      en: 'Scandinavian Forest',
      fr: 'Forêt scandinave',
      cn: '斯堪的纳维亚森林',
      ar: 'غابة إسكندنافية',
    },
    description: {
      vi: 'Sauna bạch dương 80°C, cold plunge 4°C và tắm rừng Friluftsliv của người Bắc Âu.',
      en: 'Birch sauna 80°C, cold plunge 4°C and Friluftsliv forest bathing of the Nordic people.',
      fr: 'Sauna au bouleau à 80°C, bain froid à 4°C et bain de forêt Friluftsliv des peuples nordiques.',
      cn: '80°C桦木桑拿、4°C冷水浴与北欧Friluftsliv森林浴。',
      ar: 'ساونا البتولا 80°م، الغطس البارد 4°م وحمام الغابة فريلوفتسليف لدى الشعوب الإسكندنافية.',
    },
    concept: {
      vi: 'Sauna & Cold plunge',
      en: 'Sauna & Cold plunge',
      fr: 'Sauna & Bain froid',
      cn: '桑拿与冷水浴',
      ar: 'ساونا وغطس بارد',
    },
    tags: ['european', 'nature'],
    palette: ['#0B1D35', '#00C9A7', '#EAF9F6'],
    accentColor: '#00C9A7',
    bgColor: '#0B1D35',
    textColor: '#EAF9F6',
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80',
    badge: { vi: 'Nordic', en: 'Nordic', fr: 'Nordique', cn: '北欧', ar: 'نوردي' },
  },
  {
    id: 'spa11',
    slug: '/spa11',
    name: 'Hammam Marrakech',
    tagline: {
      vi: 'Hammam Morocco',
      en: 'Moroccan Hammam',
      fr: 'Hammam marocain',
      cn: '摩洛哥哈曼浴',
      ar: 'حمام مغربي',
    },
    description: {
      vi: 'Nghi lễ Hammam 4 bước Morocco: Beldi, Kessa, Rhassoul và dưỡng argan Agadir.',
      en: '4-step Moroccan Hammam ritual: Beldi, Kessa, Rhassoul and Agadir argan nourishment.',
      fr: "Rituel hammam marocain en 4 étapes : Beldi, Kessa, Rhassoul et nutrition à l'argan d'Agadir.",
      cn: '四步摩洛哥哈曼仪式：Beldi、Kessa、Rhassoul与阿加迪尔阿甘油滋养。',
      ar: 'طقس الحمام المغربي من 4 خطوات: البلدي، الكيس، الغاسول وتغذية أركان أغادير.',
    },
    concept: {
      vi: 'Hammam & Argan',
      en: 'Hammam & Argan',
      fr: 'Hammam & Argan',
      cn: '哈曼与阿甘',
      ar: 'حمام وأركان',
    },
    tags: ['asian', 'nature'],
    palette: ['#C24B2E', '#D4A017', '#1A3A6B'],
    accentColor: '#D4A017',
    bgColor: '#1E0C05',
    textColor: '#FDF3E3',
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80',
  },
  {
    id: 'spa12',
    slug: '/spa12',
    name: 'Pearl Luminary',
    tagline: {
      vi: 'Ultra-luxury Beauty',
      en: 'Ultra-luxury Beauty',
      fr: 'Beauté ultra-luxe',
      cn: '超奢华美容',
      ar: 'جمال فائق الفخامة',
    },
    description: {
      vi: 'Thánh địa làm đẹp xa xỉ: bột ngọc trai Nhật, 24K gold facial, tế bào gốc. By appointment.',
      en: 'Luxury beauty sanctuary: Japanese pearl powder, 24K gold facial, stem cells. By appointment.',
      fr: "Sanctuaire de beauté de luxe : poudre de perle japonaise, soin visage à l'or 24K, cellules souches. Sur rendez-vous.",
      cn: '奢华美容圣殿：日本珍珠粉、24K黄金面部护理、干细胞。预约制。',
      ar: 'ملاذ الجمال الفاخر: مسحوق اللؤلؤ الياباني، عناية بالوجه بالذهب عيار 24، الخلايا الجذعية. بموعد مسبق.',
    },
    concept: {
      vi: 'Pearl & Gold Luxury',
      en: 'Pearl & Gold Luxury',
      fr: 'Luxe perle & or',
      cn: '珍珠与黄金奢华',
      ar: 'فخامة اللؤلؤ والذهب',
    },
    tags: ['luxury', 'tech'],
    palette: ['#D4AF37', '#0A1628', '#F9F6EE'],
    accentColor: '#D4AF37',
    bgColor: '#0A1628',
    textColor: '#F9F6EE',
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&q=80',
    badge: { vi: 'Exclusive', en: 'Exclusive', fr: 'Exclusif', cn: '尊享', ar: 'حصري' },
  },
  {
    id: 'spa13',
    slug: '/spa13',
    name: 'Amazônia Selvagem',
    tagline: {
      vi: 'Amazon Brazil',
      en: 'Amazon Brazil',
      fr: 'Amazonie Brésil',
      cn: '巴西亚马逊',
      ar: 'الأمازون البرازيل',
    },
    description: {
      vi: 'Thảo mộc Amazon: açaí scrub, andiroba oil, bơ tucumã và đất sét argila trắng nguyên sinh.',
      en: 'Amazon botanicals: açaí scrub, andiroba oil, tucumã butter and pristine white argila clay.',
      fr: "Plantes d'Amazonie : gommage açaí, huile d'andiroba, beurre de tucumã et argile blanche argila vierge.",
      cn: '亚马逊植物：阿萨伊磨砂、安迪罗巴油、图库马黄油与原生白色argila黏土。',
      ar: 'نباتات الأمازون: مقشر الأساي، زيت الأنديروبا، زبدة التوكوما وطين الأرجيلا الأبيض النقي.',
    },
    concept: {
      vi: 'Botanical & Eco',
      en: 'Botanical & Eco',
      fr: 'Botanique & Éco',
      cn: '植物与生态',
      ar: 'نباتي وبيئي',
    },
    tags: ['nature'],
    palette: ['#0D4A2A', '#F7C948', '#E05D2A'],
    accentColor: '#F7C948',
    bgColor: '#0D4A2A',
    textColor: '#F0FFF4',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80',
  },
  {
    id: 'spa14',
    slug: '/spa14',
    name: 'Imperial Vienna',
    tagline: {
      vi: 'Belle Époque Wellness',
      en: 'Belle Époque Wellness',
      fr: 'Bien-être Belle Époque',
      cn: '美好年代养生',
      ar: 'عافية البيل إيبوك',
    },
    description: {
      vi: 'Di sản Áo-Hung: Vinotherapy rượu vang Áo, khoáng Bad Gastein và nghi lễ Hoàng hậu Sisi.',
      en: 'Austro-Hungarian heritage: Austrian Vinotherapy, Bad Gastein minerals and Empress Sisi rituals.',
      fr: "Héritage austro-hongrois : vinothérapie autrichienne, minéraux de Bad Gastein et rituels de l'impératrice Sissi.",
      cn: '奥匈帝国遗产：奥地利葡萄酒疗法、巴特加施泰因矿物与茜茜皇后仪式。',
      ar: 'إرث نمساوي مجري: العلاج بالنبيذ النمساوي، معادن باد غاشتاين وطقوس الإمبراطورة سيسي.',
    },
    concept: {
      vi: 'Vinotherapy & Hoàng gia',
      en: 'Vinotherapy & Royal',
      fr: 'Vinothérapie & Royal',
      cn: '葡萄酒疗法与皇室',
      ar: 'العلاج بالنبيذ والملكية',
    },
    tags: ['european', 'luxury'],
    palette: ['#8B1A2F', '#C9A55A', '#FAF0E6'],
    accentColor: '#C9A55A',
    bgColor: '#1A0A12',
    textColor: '#FAF0E6',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    badge: { vi: 'Heritage', en: 'Heritage', fr: 'Patrimoine', cn: '传承', ar: 'تراث' },
  },
];
